### ISSUE TITLE
Lookup: add new feature to help writing Greek words

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#104]
In Loeb Classics site, there is a keyboard button that offers Greek letters to help writing greek words in the search field. We should implement this for the lookup.

**Comment by balmas** [comment]
@irina060981 wondering if you want to take a stab at this, following the approach from http://perseidas.fclar.unesp.br/2x/

(the source for it is here and can be reused https://github.com/aniseferreira/Grc-Por-DigDict/blob/master/greekport-clean-code2x/front-end/js/greekcode.js )

**Comment by irina060981** [comment]
I believe it is an interesting feature.
I love that we have such interesting tasks :)

**Comment by irina060981** [comment]
But I believe that the most problem here is not in chained replace commands.
but how to place properly annotation - what signs are converted to what signs

And I like the way it uses autocomplit.
I think that we could easily implement it - using for example full definitions index file from client-adapters - @balmas , what do you think?

I could take this task

**Comment by balmas** [comment]
ok, great.

Re the autocomplete -- I'm not sure about using the full definitions file, since that is lemmas only and not the forms people will likely be searching on.  

A better solution might be to use the Logeion site's search api

https://api-v2.logeion.org//search?q=<letters typed>

e.g. 

https://api-v2.logeion.org//search?q=lat
or 
https://api-v2.logeion.org//search?q=λεξ

**Comment by irina060981** [comment]
Merged first step with greek autochange beta codes to greek chars

![image](https://user-images.githubusercontent.com/12377640/78735011-09ccfc80-798d-11ea-956d-bbc743ab9d40.png)

**Comment by balmas** [comment]
@monzug fyi, the first part of this, the keyboard, is in Alpheios Components 3.3.0-qa.20200410462

Autocomplete features in the next build.

**Comment by irina060981** [comment]
Added autocomplete feature - merged and closed

**Comment by monzug** [comment]
1) q/esqai for θέσθαι -> it worked!!!! I did try few Greek words and it works fine. for πρὸς, shall we add the p is r? or is it redundant?

2) by clicking on the ? the sample characters are displayed, no matter if I checked or unchecked the enable checkbox first. how is this supposed to work? I think if we check the box we should automatically generate the sample characters.

3) if I change language from Greek to Latin the sample characters are still visible. they should be only available when the feature is enabled. Indeed they dissapear if I unchecked the check box and then change language.  
![greek-betacode](https://user-images.githubusercontent.com/41396793/79752215-f0f40d80-82e1-11ea-97c6-1b521647e78f.JPG)

**Comment by monzug** [comment]
I just tried to enter  εἶναι     I tried the I with the accent as =I or +I and didn't work. I think we are missing the ἶ

**Comment by balmas** [comment]
>q/esqai for θέσθαι -> it worked!!!! I did try few Greek words and it works fine. for πρὸς, shall we add that p is r? or is it redundant?

Yes I think we should add that. All chars that are converted should be listed.

**Comment by balmas** [comment]
>by clicking on the ? the sample characters are displayed, no matter if I checked or unchecked the enable checkbox first. how is this supposed to work? I think if we check the box we should automatically generate the sample characters.

I think the ? should display the sample chars, regardless of whether the box is checked.  I agree that when the state of the checkbox is changed from unchecked to checked it would be nice to show them then too.  

Also, I noticed that the  formatting needs a little cleanup, because the ? is wrapping to the next line. We might need to increase the min width of the lookup box. 

![0428eea6-b6b0-44cf-be3c-7fccd73d0b4c](https://user-images.githubusercontent.com/644870/79758280-349f4500-82eb-11ea-9f78-4cfca253bb7e.png)

**Comment by balmas** [comment]
> I change language from Greek to Latin the sample characters are still visible. they should be only available when the feature is enabled. Indeed they dissapear if I unchecked the check box and then change language.

Agree this should be fixed.

**Comment by balmas** [comment]
> I just tried to enter εἶναι I tried the I with the accent as =I or +I and didn't work. I think we are missing the ἶ

this should be fixed too.

**Comment by monzug** [comment]
to simplify I would remove the ? - what do you think?

**Comment by balmas** [comment]
If we remove the ? then there isn't really any way to hide the input key.  I don't think we always want it disabled when the checkbox is enabled, do we? it takes up a lot of room, and once they learn how to do it it shouldn't be necessary. I might have misunderstood your suggestion about the checkbox - I was thinking it might be good to display it if they change the checkbox from checked to unchecked, but not whenever it is checked. What do you think @irina060981 ?

**Comment by monzug** [comment]
yes, I meant that - but also I am not so keen on the ?

**Comment by monzug** [comment]
maybe we can do as follow: display the ? or other icon, only when user checks the checkbox  to enable the feature

**Comment by balmas** [comment]
hmm. but then they don't know what checking it does.  what if we replaced the question mark with a small i icon ?

**Comment by monzug** [comment]
inspiring by https://github.com/alpheios-project/alpheios-core/issues/246, we used the Options also for the Latin word usage examples. how about if we do the same for enabling this feature with the option of displaying the sample characters. the pro is that we do have a cleaner lookup (right now  it is pretty busy with the autocomplete too). what do you think @balmas and @irina060981 ?

**Comment by balmas** [comment]
I think that's a good idea. It's not likely to be something they change with each lookup.

**Comment by balmas** [comment]
I suspect @abrasax would agree too

**Comment by balmas** [comment]
> add that p is r? or is it redundant?

this one will be addressed via #276

**Comment by balmas** [comment]
>inspiring by #246, we used the Options also for the Latin word usage examples. how about if we do the same for enabling this feature with the option of displaying the sample characters. the pro is that we do have a cleaner lookup (right now it is pretty busy with the autocomplete too). what do you think @balmas and @irina060981 ?

@monzug I'm just thinking about the 2nd part of this: "with the option of displaying the sample characters."  are you suggesting that option be part of enabling the feature? I.e two options

- [ ] enable betacode in input
- [ ] show betacode sample characters 

?

**Comment by monzug** [comment]
in Options, right? yes. what do you think?

**Comment by balmas** [comment]
I'm not sure, I feel like the switch to show or hide the betacode instructions should be on the lookup box. Maybe we could have a link there but only if betacode input has been enabled in options?

**Comment by irina060981** [comment]
I think that the best way would be to have an ability to hide beta codes information if it is comfortable for user.
But it should be a user's choice, so it should be shown by default

As for enableBetaCodes - I think that it doesn't use much space.

I believe that it would be useful to get some real use cases from users.
It is from my point of view :)

**Comment by irina060981** [comment]
@balmas , should I do here anything discussed ? what do you think?

**Comment by balmas** [comment]
I would like to get feedback from @abrasax on this one.   I will be talking to him later this week.

**Comment by monzug** [comment]
agree.

**Comment by balmas** [comment]
ok, per discussion with @abrasax we'd like to move all three of the new choices on the lookup box to Options:

Enable Betacode Input
Show Betacode to Unicode Mappings
Enable Autocomplete with Logeion

And in doing so, we should make both Enable Betacode Input and Enable Autocomplete with Logeion turned on by default.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
@irina060981 - in latest build, I do still see the issue #3 (if I change language from Greek to Latin the sample characters are still visible. they should be only available when the feature is enabled. Indeed they dissapear if I unchecked the check box and then change language.) I see that the status is waiting_build, but I just want to know if issue 3 will be fixed also. Thanks

**Comment by irina060981** [comment]
@monzug, I added additional check to showing beta codes info panel
so now - it checks for the setting and for the language
I could see it in the curent master branch.

So I believe it should work after build.

**Comment by monzug** [comment]
wonderful. Thanks

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
the ἶ in  εἶναι is  )=i
