### ISSUE TITLE
Application wide configuration

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/alpheios-core#140]
There is a need to have a configuration that will be read by all components of the Alpheios application. One of the examples of such config data can be a URL of a Lexis CS service. This URL is used currently by client adapters and components, and we might need to specify different URLs for dev, QA, and prod environments.

It would be also important to be able to change (reload) configuration without rebuilding an Alpheios application. This might be required, for example, to put a cache and load-balancer in front of the morphology and lexical services, or do other changes within an infrastructure.

Please see an excerpt from a Slack's discussion of the matter:

@balmas: What might be really nice would be to have a url-providing service like a catalog that we could call whenever we need a url for a remote service and we could have all the environments there (dev, qa, prod). I think the more services we add, the more we need this. For example, I'd really like to put a proxy in front of the concordance service (which we don't control), but I can't do that without a release.

@kirlat: The only drawback I see with it is that it can become a single point of failure. But we can probably have a backup configuration within our build or something like that.

@balmas: I think we could address the single point of failure in 2 ways:
(1) having backing defaults in the build config
(2) having redundancy on the service itself
it would be a very simple service to write -- and it's quite possible that there is already something open source that we could just use as-is

@kirlat: We maybe can implement it in the simplest way possible: put a JSON configuration file on a server (as we do with CEDICT data), fetch it and store to IndexedDB or to the local storage. We also could have a matching backup JSON incorporated into our build. If the remote config is not available, we will use a backup JSON from a bundle

@balmas: I like the idea of storing it locally, although we would need to be sure to check for updates

@kirlat: Config file can have a version. Every time Alpheios is loaded it will check if the newer config is available (similar to CEDICT) and will re-download it if necessary.

@balmas: I would also like to leave open the possibility that some urls might be specific to the user or environment. For example, a deployment of the embedded library might want to be able to override certain urls.

@kirlat: So maybe inside this config files we will have different "environments": sets of configuration parameters (dev/QA/production). An Alpheios instance will know which environment it is in and will use the corresponding config data. We can even add a URL params that will specify an environment. That will allow us to switch Alpheios from one mode to the other dynamically. We can also tie other things to the environment. For example, if app is in dev environment, it will print more debug messages and if in production it will not.

@balmas: Yes. I think maybe we would add another layer on top, e.g. called "site" which could override anything in the base config. Say a site which uses the Alpheios embedded library wants to use its own version of one of our services. Or, maybe add in additional options. The most likely scenarios for this, and one we have been asked to support at some point, is a site-specific dictionary for full and short definitions. Another is site-specific inflection tables (but we aren't there yet with remote inflection tables). So, in these cases, the urls are really probably in addition to the ones we have in our config. It's less likely that someone will want to override one of our services, but it's not inconceivable. It's also possible, if we continue to develop the reading environment, that we ourselves might want to use a specific service for something when users access Alpheios on that site, versus when they are using the browser extensions. We have already seen some instances of site-specific configuration options in the embedded library, with the various things we had to add in there for configuration of the menus, etc.

@kirlat: With sites, we can probably detect a URL and apply setting depending on that. So we might list in our config URLs that would make a specific configuration set to be activated. And we can combine this with a manual startup (or URL) parameter.

@balmas: Maybe, but I'm not sure if we want to have to register sites on our side.

@kirlat: Yes, lists of sites can become hard to maintain

@balmas: i.e. to have the site urls in our config, it means a site which uses the embedded library has to communicate that to us. There can be advantages in that of course, and we might need to do that at some point anyway, particularly if we want to make user-level features available to 3rd party users of the embedded library. I.e. I think at some point we will have to require users to request api keys. So we don't necessarily have to (and possibly should not) try to engineer the site config solution just yet. But I think it's important to keep in mind.

@kirlat: I think we can probably piggyback on Webpack experience because they have complex configurations that can be combined or overriden. We can even maybe employ tools Webpack uses to merge configurations.

@balmas: that's an interesting idea

@kirlat: Here's is the tool I'm talking about: https://github.com/survivejs/webpack-merge. We're using it in `node-build`. It is created for Webpack, but it's mentioned it can be used beyond. We need to examine if it will work for us.

**Comment by balmas** [comment]
Let's get started with this in phases:

Phase 1)  for the urls configured for the messaging service (i.e. in https://github.com/alpheios-project/alpheios-messaging/blob/master/src/configurations/destinations.js) and then look into 

Phase 2) expanding the design for the urls in the client adapter config

So user stories for Phase 1)

1. As a QA person I want to be able to specify which configuration to use for testing a specific build so that I can test that the code works with a specific service
2. As a developer I want to be able to specify whic configuration to use for development testing so that I can develop without impacting qa and production environments
3. As an admin I want to be able to set the configuration to be used by a specific release of an Alpheios application
4. As an admin I would like to be able to point released applications at different configurations without releasing a new version of the application.
5. As an admin I want to be able to have more than 1 "production" version of a configuration live at one time (i.e. to support current and prior release of an application)

@kirlat can you think of any I'm missing before I move on to suggesting a design?

**Comment by kirlat** [comment]
I think all cases are covered pretty well. The only one I can think of depends on how would we handle fallbacks. If we decide to do it on the client side then a config server could provide the main config along with the fallback one. The latter will be used by our app if the main one is not available. We could achieve the same with an "always on" proxy that will redirect to the fallback server but managing that proxy server would probably an extra trouble and an extra expense. What do you think?

**Comment by balmas** [comment]
I'm not sure what you mean by fallbacks. Can you provide an example for this scenario @kirlat ?

**Comment by kirlat** [comment]
> Can you provide an example for this scenario @kirlat ?

I was thinking that we might want to specify failover servers that will be used when the main server is not available. One way to do that, I thought, would be for the config server to provide not one, but several configurations for the same type of service. The "main" configuration will be marked with a property value.

Alpheios app will use a "main" config by default. But if the service specified in the  "main" config is not available (i.e. if that server is down), Alpheios app will try to use a server from the "failover" config instead. Is this a viable scenario?

This can also be useful if we want to replace the main server with another one. We can add a fallback server to the config, wait while app instances will load the updated config file, and bring the main server down. The apps will switch to the failover servers. Then we can bring a replacement main server up and update config with its location coordinates. After that Alpheios apps will gradually start using the "new" main server.

Would we ever have situations like that? Since we're designing a config service from scratch it might be beneficial to think about all possible usage scenarios and incorporate features needed for that now, to avoid a painful change in the config file format later. What do you think?

**Comment by kirlat** [comment]
Another important thing we should think about is how would we handle a change in the format of a config file. I can think of two ways to handle that:
1. Add a "version" attribute to the file and update it every time the format changes;
2. Use a different URL from where the config file will be downloaded. If we change the file format, we will create a new URL that will serve config files in a new format. Files in an old format will be served from the old URL. This way we will know how many clients are still using the old format.

**Comment by balmas** [comment]
>I was thinking that we might want to specify failover servers that will be used when the main server is not available. One way to do that, I thought, would be for the config server to provide not one, but several configurations for the same type of service. The "main" configuration will be marked with a property value.

> Alpheios app will use a "main" config by default. But if the service specified in the "main" config is not available (i.e. if that server is down), Alpheios app will try to use a server from the "failover" config instead. Is this a viable scenario?

We could also handle this with a load balancer/failover solution on the server deployment side, which might be simpler

**Comment by balmas** [comment]
> Another important thing we should think about is how would we handle a change in the format of a config file. I can think of two ways to handle that:
> 
> 1. Add a "version" attribute to the file and update it every time the format changes;
> 2. Use a different URL from where the config file will be downloaded. If we change the file format, we will create a new URL that will serve config files in a new format. Files in an old format will be served from the old URL. This way we will know how many clients are still using the old format.

I definitely think we should version the file. I think that changing the URL also has some benefits but it might conflict with other requirements (such as this use case: "As an admin I would like to be able to point released applications at different configurations without releasing a new version of the application.")

**Comment by balmas** [comment]
Updated list of user stories

1. As a QA person I want to be able to specify which configuration to use for testing a specific build so that I can test that the code works with a specific service
2. As a developer I want to be able to specify which configuration to use for development testing so that I can develop without impacting qa and production environments
3. As an admin I want to be able to set the configuration to be used by a specific release of an Alpheios application
4. As an admin I would like to be able to point released applications at different configurations without releasing a new version of the application.
5. As an admin I want to be able to have more than 1 "production" version of a configuration live at one time (i.e. to support current and prior release of an application)
6. As an admin/developer I would like to be able to know when I can deprecate old versions of the configuration file when they are no longer being used.
7. As an application, I would like to be able to use a cached copy of the configuration if the live version is unavailable.

**Comment by balmas** [comment]
@kirlat what do you think about the supporting the following workflow on the config service? 

A request to the service to GET the config would have the following REQUIRED inputs:

clientId
appName
version
build branch
build number

and the following OPTIONAL inputs:

configName


![configworkflow](https://user-images.githubusercontent.com/644870/78033177-0950b800-7334-11ea-967a-cb821ec8658b.png)


To start with, we could just have configs for the default workflow (i.e. that applied to all apps and clientIds)

But if we end up having a need for client specific or app specific implementations, we could add them as needed.

I think I would leave it to the deployment infrastructure to deal with failover and redundancy for actually serving the data.

The initial implementation could be as simple as just static JSON files in different folders, and we could build it out to add a database and interface for managing the config data in the future as needed.

**Comment by balmas** [comment]
a prototype service which implements the above business logic is deployed at 

https://4wvouc833c.execute-api.us-east-2.amazonaws.com/prod/config

Sample query
https://4wvouc833c.execute-api.us-east-2.amazonaws.com/prod/config?clientId=myClient&appName=Alpheios+Reading+Tools&appVersion=3.3.0&buildBranch=qa&buildNumber=20200401123

**Comment by kirlat** [comment]
I've added the code that uses the new prototype service and it works well for me. The only thing I wish be different is the presence of dash in a property name (i.e. `lexis-cs`). This requires to use quotes in the code to access it. Maybe we can use something like camelCase in prop names in order to match JS naming conventions? Or, as an alternative, we can use underscores. What do you think?

**Comment by irina060981** [comment]
I have some thoughts about the described workflow.
The described workflow is similiar to the creating profiles for some conditions (as used for creating virtual hosts for example).

We could have some profile hierarchy  - 
    base options that would be differed rarely (for example urls for existed morph services or cdn links to our services)
    custom options that could be differed often (for example urls for source that are already in production and that are in tests momemnt for now)
    It could reduce the amount of configuration files

We could track the authors of created configuration files (similiar to branches and PR) and this way authors could control their config files and remove already unuseful ones.

So may be it is useful to create a specific repo with config files and we could track changes, authors of changes there.

**Comment by balmas** [comment]
I think these are good suggestions, and as we expand the number of configuration settings we manage this way, we are going to need to improve upon the service prototype to handle a hierarchical merge structure such as you describe.

At the moment, the service implementation (https://github.com/alpheios-project/alpheios-config-api) also contains the json config files (https://github.com/alpheios-project/alpheios-config-api/tree/master/config) and they are full repeated at each level that they are needed. This is okay for a file with a single setting, but not once we need to add to them.

**Comment by balmas** [comment]
Remaining to be done before release:

1. Verify final deployment url of lexis-cs
2. Update configuration file to have the correct settings

**Comment by balmas** [comment]
I'm closing this issue and will enter new issues for remaining items.
