### ISSUE TITLE
treebank disambiguation of lemma should be case-insensitive and deal with sense values

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#143]
e.g. see Αἰγύπτου in Aeschylus Suppliant Woman https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg001.alpheios-text-grc1/passage/1-30

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/876#issuecomment-575286343_

**Comment by monzug** [comment]
fixed in Alpheios Embedded Library 3.1.6-qa.20200527420
Alpheios Components 3.3.0-qa.20200605311

![Screen Shot 2020-06-09 at 2 33 44 PM](https://user-images.githubusercontent.com/41396793/84148467-5604ed80-aa5f-11ea-896c-e03b3022981d.png)
