### ISSUE TITLE
highlight disambiguated result in popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#147]
if we use treebank (or other) data to disambiguate parser results in the popup, we should visually indicate that in some way.

**Comment by balmas** [comment]
@kirlat I don't have a good idea of how this should look so suggest what you think would work. thanks!

**Comment by balmas** [comment]
in Alpheios Components 3.3.0-qa.20200410462 but wait on #221 before testing

**Comment by balmas** [comment]
Ok, this can be tested now in the texts-test environment with Alpheios Components 3.3.0-qa.20200423418

A lexeme which has been disamibugated by the treebank data should have a little arrow and a tree diagram next to it, e.g.:

![745f3f07-880d-419f-93dd-7091394365c2](https://user-images.githubusercontent.com/644870/80135654-7986de00-856e-11ea-851c-7417b958f7a3.png)

**Comment by balmas** [comment]
(I think maybe there are some css alignment issues to work out still...)

**Comment by balmas** [comment]
to investigate -- sometimes we aren't getting the disambiguated symbol when using the Alpheios data

e.g. φθίνωσιν at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30

**Comment by balmas** [comment]
I have found 2 scenarios so far where we aren't getting the disamibugation marker when I would have expected it:

(1) when the morphology service doesn't produce results -- i.e. in that case the treebank data is the ONLY data. That's the case for φθίνωσιν at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30

(2) when the treebank data is missing a part of speech (this is due to data errors per alpheios-project/alpheios-trees#4) That's the case for ἐμπρέποντας at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30

The latter should be fixed with the data. The former I'm not sure about.  Will discuss with @abrasax

**Comment by balmas** [comment]
In the meantime, @kirlat can you look into the alignment issue I'm seeing in the alpheios_nemo_ui environment? It doesn't occur on the embed-lib demo page, so I am guessing it's style bleeding from the underlying page causing the slight misalignment.

**Comment by kirlat** [comment]
Definitely, will look at it

**Comment by kirlat** [comment]
This is a tricky one. The disambiguated icon SVG height is 22 pixels in both cases, but the parent div (a base element for tooltip) is 26px in embed lib and only 22.16px in Nemo UI. Cannot figure why. Both those elements seem to have parameters that affecting dimensions the same.

**Comment by kirlat** [comment]
Oh, found it, that's because SVG has a `display: inline-block` and in that case browser reserves space for descenders (the bits that hang off the bottom of 'y' and 'p'). We have to set it to `display: block` for them to have an equal height.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by balmas** [comment]
test with Alpheios Components 3.3.0-qa.20200504341

**Comment by monzug** [comment]
alignment and issue 2 have been fixed.
issue 1) is still reproducible. see screenshot

![missing-treebank-icon](https://user-images.githubusercontent.com/41396793/82332495-79360300-99b3-11ea-8582-e9d1cc2fcc9d.JPG)

**Comment by balmas** [comment]
I think issue (1) may be resolved by my latest use case to be fixed in #166 : https://github.com/alpheios-project/alpheios-core/issues/166#issuecomment-630417237

**Comment by monzug** [comment]
1) will be tested in issue #166
