### ISSUE TITLE
simplify process of linking a text to a tree

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#148]
Currently it is a fairly tedious process to link a word on an HTML page to a tree for Alpheios. You define the location of the repository once per page:

```
    <meta name="alpheios-v2-treebank-diagram-url" data-alpheios_tb_src="https://perseids-publications.github.io/treebank-template/embed/DOC/SENTENCE?w=WORD">
```
and then define the location of the tree in the repository on each word you want to link:
```
<span data-alpheios_tb_ref="on-the-murder-of-eratosthenes-1-50#1-1">περὶ</span> . . .
      <span data-alpheios_tb_ref="on-the-murder-of-eratosthenes-1-50#1-26">πεπονθότες</span> ·
```

Make it possible to:
Define the tree linkages at the sentence level. E.g. 
```
<div data-alpheios_tb_ref="on-the-murder-of-eratosthenes-1-50#1">περὶ πολλοῦ ἂν ποιησαίμην , ὦ ἄνδρες , τὸ...</div>
```
Define the source document at a higher level. Eg. for a text which is split into 2 treebank files, you could have
```
        <div data-alpheios_tb_src_doc>="on-the-crown-1-50>
		  <div data-alpheios_tb_ref="1">πρῶτον μέν , ὦ ἄνδρες Ἀθηναῖοι ...</div>
 	 	...
		</div>
		<div data-alpheios_tb_src_doc>="on-the-crown-51-100>
		  <div data-alpheios_tb_ref="1">καίτοι φιλίαν γε καὶ ξενίαν αὐτὴν ὀνομάζει , καὶ νῦν εἶπέ που λέγων ὁ τὴν Ἀλεξάνδρου ξενίαν ὀνειδίζων ἐμοί .</div>
		  ...
		</div>
```

**Comment by balmas** [comment]
to be implemented along with #221

**Comment by kirlat** [comment]
This is implemented in #257.

**Comment by balmas** [comment]
@kirlat in my testing, the first call to findWord after a page is loaded always seems to fail.

**Comment by kirlat** [comment]
> in my testing, the first call to findWord after a page is loaded always seems to fail.

The only scenario when I was able to reproduce this was when a page is loaded, but the treebank template app is not (it takes several seconds in my tests). In a situation like that, when user starts a new lexical request fast enough, it does not go to treebank because the treebank is not available yet. Is that the case you're describing? If it is, I'm not sure how to handle user requests in cases like these. Do you have any ideas?

**Comment by balmas** [comment]
Hmm let me test a bit more and think about it.

**Comment by balmas** [comment]
It works better in the latest build with the fixes the flashing tree diagram so I think it's okay as is for now.

**Comment by balmas** [comment]
I still need to make a test page available for @monzug to test with...

**Comment by balmas** [comment]
this can be verified using the test page at https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/index.html

**Comment by monzug** [comment]
two things  that I experienced
1) in the Text and treebank aligned by sentence sample, when I switch from Latin to Greek, the first few words had no tree icon. then it started loading properly, there was a delay.
2) in Error Scenario - Failed Request, the first lookup takes really a loooong time to load. any subsequent lookup is super fast.
is it ok?

**Comment by balmas** [comment]
Both of these are expected.

>in the Text and treebank aligned by sentence sample, when I switch from Latin to Greek, the first few words had no tree icon. then it started loading properly, there was a delay.

This is because it has to load the new document. Not much we can do about it, but I think the scenario where a page uses multiple documents is not going to be common.

>in Error Scenario - Failed Request, the first lookup takes really a loooong time to load. any subsequent lookup is super fast.

This is because it's retrying the failed request until the max retry count is reached. Both the retry count and the delay in between requests are configurable by the page, but I just realized I didn't create an updated embedded library package which has the support for that in it. I will do that and then it would be good to retest to see if it improves this scenario.

**Comment by monzug** [comment]
ok

**Comment by balmas** [comment]
ok, please retest the failed request error scenario in the test page with 

Alpheios Embedded Library 3.1.6-qa.20200527420
Alpheios Components 3.3.0-qa.20200527404

The page is configured to have a retry count of 3 instead of 5 and a delay between requests of 100ms instead of 200ms. It should be somewhat faster.

**Comment by monzug** [comment]
yes, it 's definitely faster
