### ISSUE TITLE
update config for lexdata to its own domain

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#15]
We should separate deployment of the lexicon data files from the lexicon service.

**Comment by balmas** [comment]
@monzug you can verify this through the various issues for testing the alpheios-enabled lookups in the Greek short definitions.  Those 4 short defs files (major+ml+logeion, major+lsj, lsj and ml) all now are being retrieved from different places in the release code (i.e alpheios-components Alpheios Components 3.3.1-20200821376) and the qa build (Alpheios Components 3.3.1-qa.20210108437)

**Comment by monzug** [comment]
I used the major+ml+logeion with  ὠκύπος  and  Τριτοπατρῆς ,  then Liddell   with.  βακχιάς , then  major+lsj  with  ὑκερός ,  last LSJ  with  τύριμνος .

@balmas, is this enough or should I do more testing?

**Comment by balmas** [comment]
I think that's enough, thank you!

**Comment by monzug** [comment]
ok.
