### ISSUE TITLE
display appropriate error for unintialized database

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#154]
Right now in the chineseloc adapter, if the _fetchCedictData call fails due to an uninitialized database, we return on MORPH_UNKNOWN_ERROR, which the lexical query then displays as a results not found.  We should explicitly catch the uninitialized database error in the client adapter, and then display a more appropriate message to the user.

related to alpheios-project/alpheios-core#122 

will also require a change in the client adapter

**Comment by balmas** [comment]
I think this was addressed with alpheios-project/lexis-cs#9 is that correct @kirlat ?

**Comment by kirlat** [comment]
> 
> 
> I think this was addressed with [alpheios-project/lexis-cs#9](https://github.com/alpheios-project/lexis-cs/issues/9) is that correct @kirlat ?

Yes, I think it does. The database will always be uninitialized initially now, and it will return a specific error in this case. We will display a corresponding message to the user.

**Comment by balmas** [comment]
will be tested via #199
