### ISSUE TITLE
Improve the Greek short definitions

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#155]
User request: make data from The Bridge (https://bridge.haverford.edu/) available as resources in Alpheios

**Comment by balmas** [comment]
There is a new short definitions resource, Major Plus, which is built from the Major Core Greek Vocabulary for 1st 2 years and LSJ (when the term wasn't in Major).  Credits should show which source it came from.  There are also a few definitions from Vanessa Gorman.  Eventually we want a solution which dynamically pulls from the sources, but this is a workaround for now.

This could be a little odd combined with the full definitions. Please test that and see if the behavior is generally reasonable @monzug . Thanks!

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
short definitions and full definitions can be selected from dropdown in Options so the new addition is not changing this behavior. 
as per the credits, I saw Vanessa a few times (e.g. Ἀλέξανδρος) but for all the other words I have only seen this one, see attachment

- Ἀθηναῖος is still missing the definition


![new-sdef](https://user-images.githubusercontent.com/41396793/76338162-b2c10280-62ce-11ea-8f9c-2e22a6e64860.JPG)

**Comment by balmas** [comment]
>as per the credits, I saw Vanessa a few times (e.g. Ἀλέξανδρος) but for all the other words I have only seen this, see attachment. is it ok or should I get others sources in credits?

that is correct - the credit for this word is "Wilfred E. Major, Core Greek Vocabulary..."
you will see LSJ for other words not in that set

**Comment by balmas** [comment]
>Ἀθηναῖος is still missing the definition

There are lots of missing proper names still. But I'm not sure why I missed this one from Vanessa's list, so I will add it.

**Comment by monzug** [comment]
so should I also see the LSJ because I haven't yet. I did test about 15/20
words from Vanessa's list and few others from Aeschylus.

**Comment by balmas** [comment]
yes. it would make sense that you wouldn't see it on the words from Vanessa's list, because those are all among the common words for early greek learners, which is covered by the Major list.  You can check the index file itself for words to test: https://github.com/alpheios-project/majorplus/blob/master/dat/grc-mjp-defs.dat

**Comment by monzug** [comment]
also   Ἀθηναῖος   is still missing the definition  and  ἀμφί has the cases and definitions on the same line see screenshot
![one-line](https://user-images.githubusercontent.com/41396793/76420879-346d6a80-6379-11ea-98ed-36db66b629bc.JPG)

Credits shows LSJ for words from the index file.

**Comment by balmas** [comment]
> Ἀθηναῖος

I haven't pushed that update to the server yet

> ἀμφί has the cases and definitions on the same line see screenshot

I think this might be related to #157 

In any event, Harry has asked that I create a major+middle liddle short defs file too, and to make that the preferred one, so I'll take this back.

**Comment by balmas** [comment]
Per request from @abrasax I have now added another short definition file, which is also now the default: Major + Middle Liddell

Major + LSJ remains available

I have also changed the way the credits appear. The source is either ML or Major (or LSJ or Major) and for both, there is an additional line in the credits stating "Edits and additions provided by Vanessa Gorman, University of Nebraska."

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
lookup for  αἱμάσσω :
1) Credits if Wilfred Major Core Greek Vocabulary + Middle Liddell is selected. see attachement
![credit2](https://user-images.githubusercontent.com/41396793/78038020-4d46bb80-733a-11ea-8a9b-9e5e02242f70.JPG)

2) Credits if Wilfred Major Core Greek Vocabulary + LSJ is selected. see attachement
![credits1](https://user-images.githubusercontent.com/41396793/78038158-7ff0b400-733a-11ea-9e83-e08227e31347.JPG)
