### ISSUE TITLE
Should we add the lemma to verbpdgm50 and verbpdgm51 in rules.csv?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#158]
Lookup for ἔδομεν
it will generate 4 tables instead of 3 because verbpdgm50 and verbpdgm51 share the same stemtype ath_w_aor. 
we should add the lemma to each table as following
verbpdgm50	1	verb	ath_w_aor	γιγνώσκω 					
verbpdgm51	1	verb	ath_w_aor       ἁλίσκομαι
but if we do so, then  ἔδομεν   whose lemma is δίδωμι  will not have a match with these tables.
uhm... most likely we will keep as is

**Comment by balmas** [comment]
>Lookup for ἔδομεν
it will generate 4 tables instead of 3 because verbpdgm50 and verbpdgm51 share the same stemtype ath_w_aor.

@monzug I need help -- which tables should  ἔδομεν match exactly? which one is not correct

**Comment by monzug** [comment]
@balmas, I don't know!!!! verbpdgm50 and verbpdgm51 	share the same stemtype  ath_w_aor	
it might be that ἁλίσκομαι: Aorist System is more epic but I am not sure. I will try to research a little on Smyth. my point is that if we add the lemma, only the verbs whose lemma is associated with the table will have a match, correct? or we can remove one table.

**Comment by balmas** [comment]
we might be able to get the desired behavior with a combination of rules. 

Are you saying that ἔδομεν should match *either* table 50 *or* table 51 but not both and you're not sure which of the two it should be?

**Comment by monzug** [comment]
exactly. well, the matching works fine as it does pull out all the tables as per rules.csv. the point is: should we display both tables as they share the same stemtype or should we limit to one table (if so, we should eliminate one)? I don't think that adding the lemma could be the solution.

**Comment by monzug** [comment]
so, in the Smyth section 679, we have the following explanation: "Most verbs in -ω inflect the second aorist according to the ω-conjugation; some inflect it according to the μι-conjugation. "
section 681: “A number of ω-verbs form their second aorists without a thematic vowel, herein agreeing with the second aorists of μι-verbs. Cp. ἔδῡν p. 140. The second aorist of γι-γνώ-σκω know is inflected as follows. ..“
section 687: “The following ω-verbs have second aorists of the μι form.
ἁλίσκομαι (ἁλ-ο-) am captured, ἑά̄λων or ἥλων (ἁλῶ, ἁλοίην, ἁλῶναι, ἁλούς). ...“
 
as γι-γνώ-σκω is inflected in Smyth too, a workaround would be to add the lemmas to verbpdgm51 for ἁλίσκομαι so rules.csv would be updates sa follow:
verbpdgm50	1	verb	ath_w_aor						
verbpdgm51	1	verb	ath_w_aor   ἁλίσκομαι

**Comment by balmas** [comment]
that seems like a good plan.

**Comment by monzug** [comment]
I think so. Thanks

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
it works well. Thanks
