### ISSUE TITLE
numeric greek headword should not result in error

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#16]
lookup for     χρῆ   - it kept loading and loading and loading

console says: 
Unhandled Promise Rejection: TypeError: e.normalize is not a function. (In 'e.normalize("NFC")', 'e.normalize' is undefined)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
I can say that pop-up is generated right away
