### ISSUE TITLE
we don't have an ami_aor middle table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#160]
lookup for ἐπτάμην   (found in the Smyth section 687 of aorist middle verbs). we do not have the inflection icon because the stemtype is ami_aor  middle. in rules.csv we only have ami_aor active which is verbpdgm42. 
from Irina's tool
πέτομαι 
1. verb, singular, aorist, middle, indicative, 1st, ami_aor, a_stem

**Comment by balmas** [comment]
@monzug is there a table that we do have that would be worth showing for ami_aor_middle verbs?

**Comment by monzug** [comment]
well, we don't have this table. I would say any aorist middle such as verbpdgm39 δίδωμι: Aorist System Middle. I don't think we want to add an other table, right?

**Comment by balmas** [comment]
> well, we don't have this table. I would say any aorist middle such as verbpdgm39 δίδωμι: Aorist System Middle. I don't think we want to add an other table, right?

right. Ok, I'll add a rule for ami_aor_middle to go to table 39. thanks!

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
we have now a inflection icon for ἐπτάμην
