### ISSUE TITLE
support html in short defs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#167]
sometimes short definitions reference words in either the source language, or another language. It would be nice to be able to enable double-click to look up those words (when #96 is fixed ), so we should support the ability for a short definition to identify the language of a word e.g. in `<span/>` tags that include a lang attribute.

**Comment by balmas** [comment]
Using LSJ short defs can be verified with short definition for οἶδα (which has a span tag in it now -- prior to this fix the span tag would show up

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
I don't see the span tag anymore.
