### ISSUE TITLE
change for selenium tests broke click handler on toolbar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#181]
I think in the commit edc6c93f870618e6a8d1091fc1ce7d03e3b4992f the click handler on the tools icon in the toolbar was moved to just the icon and not the surrounding area, but we want the little arrow that appears below the tools icon to remain clickable.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
if you are talking about the little arrow below the additional resources icon, it works fine in build Alpheios Reading Tools 3.1.0 build qa.20200309459
Alpheios Components 3.3.0-qa.20200309431 build qa.20200309431

**Comment by monzug** [comment]
confirm that the little arrow and surrounding area are still working in latest build. tested in Chrome
