### ISSUE TITLE
Corrections to short definitions

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/alpheios-core#182]
lemma | current   def | Beginning   Definition | NOTE
-- | -- | -- | --
ἄργυρος | white   metal | silver |  
διατρίβω | rub   hard, etc. | ADD:   delay |  
εὐθύς [ADV] | straight | directly,   immediately | gives   the meaning for the adjective instead of the adverb
χρῆμα | a   thing that one uses | thing, money |  
πρέσβυς | an   old man | an   old man; ambassador |  
τυραννεύω | to   be a | to   be a tyrant |  
ὁπλίζω | to   make or get ready | to   make or get ready, arm |  
ἄρχω | to   be first | to   be first, rule |  
δίκη | custom,   usage | order,   right; judgment, trial, penalty |  
ἀγορά | an   assembly of people | market-place |  
ἀρχαῖος | from   the beginning | ancient,   old |

**Comment by balmas** [comment]
where these suggestions from Vanessa differ substantially from the major+middel liddel and or major+lsj definition, I have added them.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
ἄργυρος --> white metal in Wilfred Major Core Greek Vocabulary + LSJ
               --> silver in Wilfred Major Core Greek Vocabulary + Middle Liddell

διατρίβω  --> consume, spend time in Wilfred Major Core Greek Vocabulary + Middle Liddell   and   in Wilfred Major Core Greek Vocabulary + LSJ

ὁπλίζω    --> missing arm in Wilfred Major Core Greek Vocabulary + LSJ

ἄρχω  --> rule in both

**Comment by balmas** [comment]
Ah, I should probably fix these:

ἄργυρος --> white metal in Wilfred Major Core Greek Vocabulary + LSJ
(should be silver)

διατρίβω --> consume, spend time 
(add delay)

ὁπλίζω 
(add arm in LSL)


Thanks

**Comment by balmas** [comment]
those fixes are made and deployed.

**Comment by monzug** [comment]
yes.
