### ISSUE TITLE
test greek noun, adjective paradigms

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#186]
these were added via alpheios-project/inflection-tables#289

Can be tested in Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
how do I test this? If I enter a noun in the lookup, I do still get the noun declension or the simplified declension. If I enter a noun in Irina's tool, I do only get Morpheus output. Please advise

**Comment by balmas** [comment]
hmm. Maybe we need to do more work to finish this, I was thinking it was done, but will reopen and investigate. Thanks.

**Comment by balmas** [comment]
@irina060981 can you investigate? Not sure what remains to be done here. Thanks!

**Comment by irina060981** [comment]
My tool could check only verbs and participles - because it extracts only paradigms.
That's why for nouns it shows nothing.
@balmas , @monzug, Do we need to expand the tool for all type of inflection tables?

**Comment by balmas** [comment]
this is not the inflection-input tool, but the actual alpheios application (webextension/embed-lib) that @monzug is testing (I think anyway)

**Comment by irina060981** [comment]
>how do I test this? If I enter a noun in the lookup, I do still get the noun declension or the simplified declension. If I enter a noun in Irina's tool, I do only get Morpheus output. Please advise

@balmas, then I am not sure - what exactly I should investigate here? The described workflow is as it exists now upon the requirements in issues. Or Should I point my attention to anything here?

**Comment by balmas** [comment]
let me take another look. thanks!

**Comment by balmas** [comment]
ok, here's what I think needs to be done still:

1. Add the new noun and adjective paradigms to the inflection browser 
2. Change the logic so that when you look up a noun or adjective that returns a paradigm table, it returns the paradigm table *in addition to* as the regular endings tables (right now it returns only the paradigm table if a paradigm table matched)

Thanks!

**Comment by irina060981** [comment]
You are right, I have forgotten about the fact I added paradigm tables for other part of speech myself :)
Will add them here too :)

**Comment by irina060981** [comment]
Add the new noun and adjective paradigms to the inflection browser
Change the logic so that when you look up a noun or adjective that returns a paradigm table, it returns the paradigm table in addition to as the regular endings tables (right now it returns only the paradigm table if a paradigm table matched)

Both features are released

**Comment by irina060981** [comment]
I believe that I could close it

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
Irina and Bridget, i have a question. I double click on φροντίδα and only the noun declension and simplified declension is displayed (same for ὄρνις and φυγάς). I checked on Morpheus and its stemptype is <stemtype>is_idos</stemtype>, then I check the noun rules.csv, and it should also list the Consonant-Declension Nouns: dental plosive stems (masc. and fem.) table as per
nounpdgm6 | 1 | noun | is_idos | 3rd |   | ἀσπίς

Is there any reason why we are restricting the matching by lemma too?

**Comment by monzug** [comment]
and an other one: why is singular not repeated in each line, while dual and plural are? I would do as the mastronarde tables: one singular, one dual, one plural
![Screen Shot 2020-05-21 at 2 58 46 PM](https://user-images.githubusercontent.com/41396793/82561718-2192c580-9b74-11ea-89c3-defdd6b4f4ed.png)

**Comment by balmas** [comment]
> Irina and Bridget, i have a question. I double click on φροντίδα and only the noun declension and simplified declension is displayed (same for ὄρνις and φυγάς). I checked on Morpheus and its stemptype is is_idos, then I check the noun rules.csv, and it should also list the Consonant-Declension Nouns: dental plosive stems (masc. and fem.) table as per
> nounpdgm6 | 1 | noun | is_idos | 3rd |   | ἀσπίς
> 
> Is there any reason why we are restricting the matching by lemma too?

I think we weren't sure to what extent the stemtypes were valid for the nouns and adjectives. I agree that we should try removing the restrictions and see how it does.

**Comment by balmas** [comment]
> and an other one: why is singular not repeated in each line, while dual and plural are? I would do as the mastronarde tables: one singular, one dual, one plural

agree

**Comment by monzug** [comment]
Test: lookup for φύλακος when we remove the restriction, it should be listed an other table: nounpdgm1

**Comment by monzug** [comment]
lookup for λαγώ  - we do not highlight the dual nom, voc,acc, I think we should add the following in rules.csv


nounpdgm17 | 1 | noun | os_ou | 2nd |   | λαγῶς

**Comment by balmas** [comment]
I see one reason why we initially restricted all the rules by lemma: our matching logic runs into trouble when trying to calculate a full match on the cells both for the scenario when we DO have a lemma match and when we DON'T.  e.g. for χώρᾱ and γνώμη , when the word is one of those two, if we restrict the cell match on the lemma, we know which one to highlight, but we don't if we don't restrict it by lemma.  We could probably rewrite the logic to deal with that, but not for this release probably.

So for right now it's a choice between getting the cell matching right or matching more words into the tables 

@monzug what do you think?

**Comment by monzug** [comment]
I am ok with releasing with the restriction but we should improve the logic for later.  need extensive testing...

**Comment by balmas** [comment]
> I am ok with releasing with the restriction but we should improve the logic for later. need extensive testing...

ok thanks!

**Comment by balmas** [comment]
closing this again. remaining issues will be handled separately.
