### ISSUE TITLE
don't display redundant build number

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#188]
in order to publish multiple builds of alpheios-components and alpheios-embedded release versions to npm, we need to include the build number in the package json files, In this case, display of the build number with the package version is redundant.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
I do see this now:
Alpheios Reading Tools 3.1.0 build qa.20200320411
Alpheios Components 3.3.0-qa.20200320403

where should I look for the redundant version numbers?

**Comment by balmas** [comment]
there -- so they are gone now :-)
