### ISSUE TITLE
irregular verb table broken

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#195]
>we did also lost the style for the verbs. see attachment

I didn't see the problems with styles in inflections, but according to the old version in https://texts.alpheios.net/
inflection table for latin irregular verbs are broken

![image](https://user-images.githubusercontent.com/12377640/76590875-4b0eef80-653a-11ea-9dfb-a60de75b0d9a.png)

@monzug , do you mean this problem?

_Originally posted by @irina060981 in https://github.com/alpheios-project/alpheios-core/issues/157#issuecomment-598547702_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
Now the irregular tables are displayed correctly. tested in build qa.20200320411
