### ISSUE TITLE
test greek elision support

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#20]
from alpheios-project/data-models#96 
>There are greek contractions which sometimes use an apostrophe in place of the vowel
e.g.
δ’ = δέ, τ’ = τε and so on.
Morpheus, the greek parser, does already normally produce the correct results for such contractions (e.g. both δέ and δ’ parse correctly) but we aren't giving it the chance, because we are stripping out the punctuation. 
The problem is actually caused by the use of a right quotation (\u2019) in place of the greek koronis (\u1fbd). Our code correctly handles \u1fbd or \u0027 (apostrophe) but the right quotation (\u2019) is being stripped as punctuation.

This is fixed and waiting verification 

webextension v3.0.6-qa.3

**Comment by monzug** [comment]
lookup works fine for the following:
δ’
τ’
δι’
