### ISSUE TITLE
Moving the pop-up goes partially out of screen and cannot see the top nav

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#205]
I did experience this issue multiple times in the last builds: sometimes (not always) when I move the pop-up on top of the screen, the top nav is not visible and when I move it down the screen and release, it goes again up. pretty annoying. However I do not have a reproducible scenario. Anyone has seen this?

**Comment by balmas** [comment]
yes I think I saw that too. Giving to @irina060981 to debug.

**Comment by balmas** [comment]
reassigned to @kirlat

**Comment by kirlat** [comment]
@balams: Strangely, I cannot reproduce this with the latest version of `alpheios-core` (`i140-app-wide-config`). There was an `interactjs` update there so maybe, hopefully, it fixed that. Or maybe I'm just not following the right steps for it to appear. 

Can you please verify that it still exists for you in this version? Thanks!

**Comment by balmas** [comment]
ok, will ask @monzug to retest with the next build.

**Comment by balmas** [comment]
@monzug can you retest in Alpheios Components 3.3.0-qa.20200410462 ?

**Comment by monzug** [comment]
Just experienced this issue again in Chrome on latest build: Alpheios Reading Tools 3.1.0 build qa.20200420272
Alpheios Components 3.3.0-qa.20200420262
see screenshot
![pop-up-move-up](https://user-images.githubusercontent.com/41396793/79871792-e6557900-83b2-11ea-92c5-9c20e29a9adc.JPG)

to repro: lookup for caro. then go to the bottom of the pop-up and click on Credits. Cannot see the top nav any longer. If I move to the top nav and release, the pop-up will go back to show only the bottom part so I am not able to close the pop-up.

**Comment by kirlat** [comment]
@monzug: thanks for a detailed description! I see the problem now, will fix.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
tested in Chrome on PC, build Alpheios Reading Tools 3.1.0 build qa.20200423423
Alpheios Components 3.3.0-qa.20200423418
it works well in Loeb classics but not in latin library.
I am still able to repro the above scenario (lookup for caro and expand the credits, then can't reach the top nav)

**Comment by kirlat** [comment]
> it works well in Loeb classics but not in latin library.
> I am still able to repro the above scenario (lookup for caro and expand the credits, then can't reach the top nav)

Hmm, cannot see this in my tests somehow. This is how it looks in my case:
![image](https://user-images.githubusercontent.com/18631055/80240866-a2dd6200-8673-11ea-8b59-f11f43fab45f.png)
It openes initially with the header just below the browser's URL bar and the bottom just above the bottom of the screen (you can see thin lines that represent parts of them). It is already showing a scroll bar inside a popup because content does not fit in. When I open credits, it does not change much: just the scrollbar handle becomes a little shorter because the scrollable content becomes a tad longer. No matter how I try to drag the popup (up or down), it returns to position shown on the image above.

Are you testing it with webextension? What browser and operating system are you using? What is your screen resolution?

**Comment by kirlat** [comment]
@balmas, can you reproduce this?

**Comment by monzug** [comment]
Chrome on PC,  resolution 1920x1080 (default)
note that in my test case the scroll bars are not available.

**Comment by monzug** [comment]
actually with or without scrolling bars, it does go out of screen in latin
library.

**Comment by balmas** [comment]
@kirlat I could not reproduce in Chrome on Linux, but I can in Windows in Chrome 81.0.4044.122 with display at 1920x1080

**Comment by balmas** [comment]
I think it might have to do with whether the popup is too big to fit on the screen to start or not. I'm able to get it back down if I resize the popup from the bottom so that it is smaller than the screen, then I can drag it down.  @monzug does that work for you?

**Comment by monzug** [comment]
yes it does.

**Comment by balmas** [comment]
ok, so @kirlat I guess the question is whether we can detect that the popup is too large to be displayed and automatically resize to prevent this problem from occuring.

**Comment by kirlat** [comment]
> I guess the question is whether we can detect that the popup is too large to be displayed and automatically resize to prevent this problem from occuring.

It should already been taken care of by the `max-height` CSS rule that is set for the popup: https://github.com/alpheios-project/alpheios-core/blob/master/packages/components/src/vue/components/popup.vue#L224. It does work for me in my test scenarios, but it seems to be not always be the case. Please note: the max height value is computed once, when the page is loaded, and is not recalculated when a browser window size is changed after the page is opened (that will complicate logic by size tracking and I think it is not the case we need to worry about much: users, I think, do not change sizes of their windows often, and if the do, a page refresh will return a correct size of an adjusted window).

@monzug, @balmas: can you please check if a `max-heigh` inline rule is present for the popup in your case and if it is, what is the value. It should be set for the popup container with the `alpheios-popup-inner` ID and it's value should match the browser's viewport size. Thanks!

**Comment by balmas** [comment]
For me, the max-height is set to 1178px, so larger than the resolution height of 1080..

```<div id="alpheios-popup-inner" data-alpheios-ignore="all" class="alpheios-popup alpheios-content" style="left: 0px; top: 0px; width: auto; height: auto; z-index: 2000; max-height: 1178px; transform: translate(587.286px, -372.6px);">```

**Comment by kirlat** [comment]
> For me, the max-height is set to 1178px, so larger than the resolution height of 1080..

Thank you! Then, I think, this is a problem. What page is that on?

**Comment by balmas** [comment]
that was just on the main page of the latin library

http://thelatinlibrary.com/

**Comment by monzug** [comment]
<div id="alpheios-popup-inner" data-alpheios-ignore="all"
class="alpheios-popup alpheios-content" style="left: 0px; top: 0px; width:
auto; height: auto; z-index: 2000; max-height: 10228px; transform:
translate(119.216px, 175.894px);">

**Comment by kirlat** [comment]
Thanks!

**Comment by monzug** [comment]
No problem. hope it can help.

**Comment by kirlat** [comment]
The Latin Library has no `<DOCTYPE>` directive on its HTML text pages. As a result, browser renders it in a "quirks" (i.e. dating back to pre-2000) mode. In that mode, `document.documentElement.clientHeight` that we're relying upon, returns not the viewport height, but the height of the document: https://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#dom-element-clientheight.

I will experiment with some ways to make it work in both "quirks" and "standard" modes.

**Comment by balmas** [comment]
ugh, ok thanks.

**Comment by balmas** [comment]
(if it were any site but the Latin Library I'd say forget it...)

**Comment by kirlat** [comment]
I think I've found a simple solution that seems to work. Let me try that...

**Comment by balmas** [comment]
@kirlat is this one ready for testing with the next build?

**Comment by kirlat** [comment]
Yes, it does

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
in Chrome all good.
in FF 76  build Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327 

can't move the pop-up, it has a fixed position. see screenshot

![FF-popup-still](https://user-images.githubusercontent.com/41396793/81708868-85fca900-943f-11ea-9c59-e93851951cd1.JPG)

**Comment by kirlat** [comment]
> can't move the pop-up, it has a fixed position. see screenshot

@monzug, can you please verify if it is in a webextension or in an embed lib. If it is a webextension, can you please check if it is working in embed-lib and vise versa. I suspect it might be webextension-related.

**Comment by monzug** [comment]
@kirlat, tested in both latin library and loeb classics in FF. On the first double click, the pop-up  can be moved, after that it has fixed position. In texts-test.alpheios.net in FF, the pop-up can be moved around the page after the second double click, so yes it's webext-related.

**Comment by kirlat** [comment]
Thanks!

**Comment by kirlat** [comment]
A fix has been merged into master of `webextension`.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200522460
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
tested in FF. it works fine however I was able to move the pop-up outside the window. it came back only by reloading the page. lookup for caro, then I scrolled down and up the pop-up and moved around the page on top, right, left, bottom. then all the way to the bottom till it does disappear, but this time it did not come back. I had to reload the page.
see screenshot

![Screen Shot 2020-05-25 at 2 37 39 PM](https://user-images.githubusercontent.com/41396793/82813511-82344200-9e95-11ea-8a83-e93373357049.png)

**Comment by kirlat** [comment]
I'm trying to reproduce it and I cannot repeat the last step:
> all the way to the bottom till it does disappear
I'm dragging it by the header bar, and, in order to move outside of the screen at the bottom, I have to move a mouse pointer that is within the header area all the way to the bottom so that it will go outside. But I, however, cannot do that. The browser does not allow me to move a mouse pointer outside of the screen if I move it to the bottom. This is the lowest I can get:
![image](https://user-images.githubusercontent.com/18631055/82906563-82f0d500-9f76-11ea-9a72-0127a64bb191.png)

**Comment by balmas** [comment]
I wasn't able to reproduce this one either. Tested in FF 76 on Linux and Windows.

I was able to drag it fully outside of the window but it popped back immediately.

@monzug what version of Firefox are you using? on Mac or Windows?

**Comment by monzug** [comment]
FF 76 on Mac
I was able to repro the scenario described above. windows goes all the way off the screen. on double clicking on a new word, the top of pop-up was visible from the screen so I was able to drag it back to the center and since then it works fine.
1) outside the visible screen
![Screen Shot 2020-06-01 at 3 19 52 PM](https://user-images.githubusercontent.com/41396793/83413335-f03fb280-a41b-11ea-9d8a-ef78b4f1d748.png)
2) top of pop-up is visible for subsequent double click
![Screen Shot 2020-06-01 at 3 20 10 PM](https://user-images.githubusercontent.com/41396793/83413401-106f7180-a41c-11ea-9509-79a926703b69.png)

**Comment by balmas** [comment]
ok, I'm going to say we can live with this. FF on Mac is a very low percentage of our user base and I don't think it's worth the time. We can put it in the FAQ. @monzug are you okay with that?

**Comment by monzug** [comment]
Actually, I wouldn't put it in the FAQ. but I still need to check FF on PC

**Comment by balmas** [comment]
ok.

**Comment by monzug** [comment]
I can't repro it in FF on PC. pop-up does always bounce back

**Comment by monzug** [comment]
tested in release, Chrome on Mac
I was able to move the pop-up out of the visible screen. it come back up only by reloading the page. see screeshot
