### ISSUE TITLE
endings highlighted in the browser

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#220]
while testing the Greek pronouns, I realized that the endings are still highlighted after few lookups. 
is this an acceptable behavior? 
see screenshot
![pronoun-highlighted](https://user-images.githubusercontent.com/41396793/78027573-993e3400-732b-11ea-8181-cba832bfe949.JPG)

**Comment by balmas** [comment]
no... the state needs to e cleared between lookups.  this is a bug. Thank you!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
the endings are not longer highlighted in the inflection tables browser
