### ISSUE TITLE
More better definitions

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/alpheios-core#222]
ἀντίπαλος | wrestling against | matched, balanced |  
-- | -- | -- | --
ἀπορία | difficulty of passing | difficulty, perplexity, being at   a loss |  
ἀρέσκω | to make good, make up | make amends, please |  
διαρπάζω | tear to pieces | plunder |  
δόρυ | a stem, tree | a stem, tree, spear shaft |  
ἐκμίτνω | NDF | see ἐκπίπτω [fall out, be driven   out] |  
ἐξαγγέλλω | sendout | proclaim | current meaning is wrong
ἔξοδος | a going out | expedition, procession |  
ἐπιτήδεια | made for an end of purpose | useful, necessary |  
εὐώνυμος | of good name, honoured | of good name, on the left side |  
ἴδιος | one's own, pertaining to oneself | private, personal |  
καταλέγω | v. καταλέχομαι. | recount, reckon | There is a καταλέγω (a) and   (b).  Only (a) shows up.
κέρας | the horn of an animal | the horn of an animal, the wing   of an army |  
λήγω | stay, abate | end, stop |  
λόφος | the back of the nexk | crest, ridge |  
λόχος | ambush | ambush, armed band |  
μέτοικος | changing one's abode (etc) | metic, resident alien |  
ὄνομα | "by name" | "name" | Should not have "by"   in the definition.
παμπλήθης | NDF | numerous |  
πρίαμαι | have | buy |  
συντρίβω | rub together | shatter, crush |  
τάξις | an arranging | deployment, order of battle |  
τροπαῖος   [ADJ] | of or for defeat | τρόπαιον [noun]: trophy | Should link to separate entry   for the noun
ὕποπτος | looked at from beneath | suspected, viewed with jealousy |  
ψηφίζω | to count or reckon | vote |  
ὥρα | period | season, time | ὥρα C) is NOT in the long LSJ   entry that comes up
ὥστ' | Not found | as a result, therefore | Adverb or conjugation

**Comment by vgorman1** [comment]
I should have said, the second column is the current definition, the third is what it should read, and the fourth is miscellaneous notes.
Thanks!
Vanessa

**Comment by balmas** [comment]
ἐκμίτνω and παμπλήθης require #239

**Comment by balmas** [comment]
these changes have been made in the major+middle liddle and major+lsj short defs files, where appropriate. 

Additional fixes to be made via #239 and #198

**Comment by monzug** [comment]
ἀρέσκω  I do only have please or pleasing (as adj)
ἔξοδος  as an adjective we have promoting the passage  (verb is ok)
ἴδιος  as an adj we have violent heat, sweat   (verb is ok)

confirmed that ἐκμίτνω   and   παμπλήθης   are not fixed  as per above comment

**Comment by balmas** [comment]
I think those variations are ok.
