### ISSUE TITLE
fix HtmlSelector treebank attribute test

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#224]
this test is probably broken by changes in #219 . Will enter an issue to fix.

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios-core/pull/223_

**Comment by balmas** [comment]
@kirlat is this fixed now?

**Comment by kirlat** [comment]
Yes, I think so. All tests are passing successfully now.

**Comment by balmas** [comment]
ok.
