### ISSUE TITLE
arethusaAdapter map person property values

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#226]
For Greek, Arethusa may report the following values for person

'first person'
'second person'
'third person'

these need to be mapped to the standard values

'1st'
'2nd'
'3rd'

**Comment by balmas** [comment]
in Alpheios Components 3.3.0-qa.20200410462 but wait on #221 before testing

**Comment by monzug** [comment]
I see 2nd and 3rd person so I am assuming it should work also for 1st
