### ISSUE TITLE
support multiple values in data-alpheios_tbref

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#234]
In the the switch from alpheiosTbAdapter to the arethusaTbAdapter we lost the ability to support multiple references in a treebank morph query.  This needs to be added back (because sometimes a single token in a source text is linked to multiple tokens in a treebank, as is the case with enclytics like "virumque". 

This requires changes to the Arethusa api, and the workflow

See also related item  #135

**Comment by balmas** [comment]
to be implemented along with #221 

Note that this will require multiple calls to the Arethusa getMorph api. Although I could change that API to support multiple words in input, I think that implies larger changes for the schema that I don't want to make right now.

The full solution for this requires #135 but as we did for the chinese, I'd like to manage this via workaround for now, and just put all the returned words into a single Homonym object.

@kirlat I'm guessing you'll have questions about this one, and it's probably easier to discuss in chat.

**Comment by kirlat** [comment]
Should be solved with #257.

**Comment by balmas** [comment]
test page at https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/index.html

**Comment by monzug** [comment]
compare neque in release vs test env, both ne and que are highlighted in test env.
