### ISSUE TITLE
include TONOS in diacritics stripped in greek alternate encodings?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#239]
reported in #222 

we don't find a definition for "παμπλήθης" because it is indexed in lsj/ml under "παμπληθής"  (using Unicode Character 'GREEK SMALL LETTER ETA WITH TONOS' (U+03AE) rather than Unicode Character 'GREEK SMALL LETTER ETA' (U+03B7)

To fix this we could add the tonos to the characters stripped for alternate encodings for lexical lookups.

**Comment by balmas** [comment]
another example from #222 

ἐκπίπτω is not found by looking up ἐκπίπτω because it uses Unicode Character 'GREEK SMALL LETTER IOTA WITH TONOS' (U+03AF) rather than Unicode Character 'GREEK SMALL LETTER IOTA WITH OXIA' (U+1F77)

**Comment by balmas** [comment]
Per https://wiki.digitalclassicist.org/Greek_Unicode_duplicated_vowels oxia and tonos are semantically identical and tonos should be preferred over oxia both both should be processed as equivalent.

**Comment by balmas** [comment]
>ἐκπίπτω is not found by looking up ἐκπίπτω because it uses Unicode Character 'GREEK SMALL LETTER IOTA WITH TONOS' (U+03AF) rather than Unicode Character 'GREEK SMALL LETTER IOTA WITH OXIA' (U+1F77)

Although it turns out the tonos/oxia wasn't the problem here.. there seem to be various variations of ἐκπίπτω

It parses as the lemma ἐκπίτνω
LSJ had a see entry for ἐκπίτνω which points at ἐκπίπτω but that was missing from the short defs file

I had added an entry to the MajorPlusLSJ and MajorPlusML files for a 3rd variation:
ἐκμίτνω

And now have added a see entry for ἐκπίπτω to those files as well as the LSJ short defs file.

**Comment by balmas** [comment]
Per discussion with @rgorman, stripping all diactricts as a fallback is probably worth doing.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200507327

**Comment by monzug** [comment]
as per ἐκμίτνω, the pop-up does only have short def, see attachment

![Screen Shot 2020-05-27 at 4 12 00 PM](https://user-images.githubusercontent.com/41396793/83031543-f8bb7600-a034-11ea-9f39-debada32d419.png)

**Comment by balmas** [comment]
yes, it's okay.
