### ISSUE TITLE
arethusa tree display isn't sized as well as before

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#243]
need to look into whether we can improve the resizing

**Comment by balmas** [comment]
this should be fixed by alpheios-project/arethusa#805

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441 (fix is really in Arethusa but version info is not visible there)

**Comment by balmas** [comment]
test with Alpheios Components 3.3.0-qa.20200504341

**Comment by monzug** [comment]
tested in Alpheios Embedded Library 3.1.6-qa.20200514440
Alpheios Components 3.3.0-qa.20200522457

looks good but the first time I do load the tree diagram, the tree first moves on the side then center than finally in the position like looking for the focus. is it ok?

**Comment by balmas** [comment]
>looks good but the first time I do load the tree diagram, first it moves on the side then center than finally in the position like looking for the focus. is it ok?

Yes, it's trying to find the "perfect" positioning for the current size of the display. Feature not a bug :-D

**Comment by monzug** [comment]
ok.
