### ISSUE TITLE
update chineseloc adapter for alpheios-messaging changes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#245]
I think the recent commits in alpheios-messaging broke the chinese loc client-adapter tests. As @irina060981 noted, they are failing on travis, and when I updated my local environment to the latest alpheios-messaging commit they started failing there as well.

**Comment by kirlat** [comment]
Sure, will do that

**Comment by kirlat** [comment]
Should be fixed with #257

**Comment by balmas** [comment]
@monzug just test to see if the chinese prototype is still working in Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
yes, it does. tested in chrome in Alpheios Reading Tools 3.1.0 build qa.20200423423
Alpheios Components 3.3.0-qa.20200423418
