### ISSUE TITLE
add ability for user to select between multiple grammars

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#246]
we will be adding the Allen and Greenough New Latin Grammar for Latin, and we want to allow users to choose between this and Bennett

**Comment by balmas** [comment]
Can test in  Alpheios Components 3.3.0-qa.20200420262

But see #249 and #248 which remain unfixed

**Comment by monzug** [comment]
I could not select the Bennett anymore in the Browser Grammar - selector works only for New latin Grammar and the Smyth's grammar. see screenshot
![title-grammar-selector](https://user-images.githubusercontent.com/41396793/79870051-59112500-83b0-11ea-9910-b7a83bb8b8cb.JPG)

**Comment by balmas** [comment]
@monzug you have to choose which Latin grammar you want in the options now:

![Screenshot from 2020-04-21 09-16-37](https://user-images.githubusercontent.com/644870/79870339-d472d680-83b0-11ea-93f1-f26d01800854.png)

I didn't think it made sense to list both Latin grammars in the Grammar tab, since I think people will prefer one or the other.

**Comment by monzug** [comment]
let me think about it. I was expecting to be able to chose from the two
latin grammars also in the browse grammar.

**Comment by monzug** [comment]
I got used to it so I am ok with this functionality. just one question: is it ok to have a blank screen when both grammars are not expanded? see screenshot
![both-grammars](https://user-images.githubusercontent.com/41396793/80372579-bfd78800-8861-11ea-99da-689f4ad229de.JPG)

**Comment by balmas** [comment]
I think that's fine.

**Comment by monzug** [comment]
ok - I'll close this one.
