### ISSUE TITLE
grammar title and contents out of sync

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#248]
If you change grammar in resource tab, the title of grammar will be changes in grammar browser, but grammar content won't not change:

![image](https://user-images.githubusercontent.com/12377640/79623488-f0cc0480-815f-11ea-871f-e002805a5f4d.png)

and even if I will open/close grammar inside the tab - grammar content won't be updated

_Originally posted by @irina060981 in https://github.com/alpheios-project/alpheios-core/pull/247#issuecomment-615522530_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
it works in build Alpheios Reading Tools 3.1.0 build qa.20200514494
Alpheios Components 3.3.0-qa.20200514430
if I change to Bennett in Options, then Browse Grammar will show the title and content of the Bennett latin grammar
