### ISSUE TITLE
grammar tab empty after change to language without grammar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#249]
If you change a page language to not Latin or not Greek language (lookup for not Latin or Greek word) - grammar tab would be completely empty. There won't be any grammar browser.

Looks like this way
![image](https://user-images.githubusercontent.com/12377640/79623697-160d4280-8161-11ea-92a4-35b860a01b55.png)

May be this notice would be helpful

_Originally posted by @irina060981 in https://github.com/alpheios-project/alpheios-core/pull/247#issuecomment-615523178_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
Now we have the option to select the greek or latin grammar. tested in FF
see screenshot

![no-grammar](https://user-images.githubusercontent.com/41396793/81957442-9006df00-95da-11ea-90ee-470c76278d1e.JPG)
