### ISSUE TITLE
βαλῶ is missing the option to display the verb inflection table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#250]
while testing issue #74 , I realized that βαλῶ  does not offer anymore the option to display the verb inflection table but only the noun inflection table.
see screenshot
![missing-greek-verb-inflection](https://user-images.githubusercontent.com/41396793/79762189-6bc42500-82f0-11ea-88c4-1909be85ff71.JPG)

tested in Chrome  Alpheios Reading Tools 3.1.0 build qa.20200410484
Alpheios Components 3.3.0-qa.20200410462

**Comment by balmas** [comment]
oops, this was caused by a typo in the stemtype test for verbpdgm 4 Future System (Active and Middle) with contraction in -έω. Will fix it.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
tested in Chrome build Alpheios Reading Tools 3.1.0 build qa.20200423423
Alpheios Components 3.3.0-qa.20200423418
looks good. Thanks
