### ISSUE TITLE
in Loeb Classics, the buttons have a black, not white background

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#251]
see screenshot
![missing-greek-verb-inflection](https://user-images.githubusercontent.com/41396793/79762496-da08e780-82f0-11ea-9d77-4a1761ae14b2.JPG)

**Comment by monzug** [comment]
this is in chrome on mac
![Screen Shot 2020-04-22 at 2 13 46 PM](https://user-images.githubusercontent.com/41396793/79980559-94d8e700-84a3-11ea-887f-603eb35a1bf3.png)

**Comment by monzug** [comment]
also, the buttons in the Browse grammar  look off on the right side.  this is in Chrome on pc and mac
see screenshot
![new-latin-grammar](https://user-images.githubusercontent.com/41396793/80099739-f5683280-853c-11ea-88ff-f4749bc8aa4c.JPG)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
Now we have a white background color but when mouse over Don't ask me again it's still black, see screenshot is #292

**Comment by kirlat** [comment]
> Now we have a white background color but when mouse over Don't ask me again it's still black, see screenshot is #292
> also the two buttons are not aligned as per release

Hope that the latest changes just merged into master would fix this.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
YES, it looks fine
