### ISSUE TITLE
see declension in the participle table does not work

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#252]
I think we had this issue before. anyhow, in the current build, if I click on see declension it does not do anything. on the contrary in the release, it takes to the related participle table (e.g. βουλεύσομαι)
tested in Chrome in Alpheios Reading Tools 3.1.0 build qa.20200410484
Alpheios Components 3.3.0-qa.20200410462

**Comment by balmas** [comment]
I know we've fixed this before. Maybe related to recent changes for subtables. @irina060981 can you investigate?

**Comment by irina060981** [comment]
I need some additional explanations here -  
I used `βουλεύσομαι` for testing (thank you @monzug for this example)

I have tested several elder branches:
`3.0.3.90-branch-for-release`
`3.0.1.82-branch-for-release`

see declension link doesn't do anything visible

I investigated the current code:
and there was missed `navigate` behaviour.
I added it - and it should scroll to suptable `verbpdgm65` that is right under it -

this way - behaviour is not visible, but I believe that it is right.

@balmas and @monzug , am I right? and in this example there wouldn't be any visible result on clicking `see declension`

**Comment by irina060981** [comment]
You could see changes for `navigate` method in PR

**Comment by balmas** [comment]
>in this example there wouldn't be any visible result on clicking see declension

I'm not sure I understand. The result should be the scrolling to the see table

**Comment by irina060981** [comment]
>I'm not sure I understand. The result should be the scrolling to the see table

as I could see from debug - it searches and scrolls

merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
yes, it works in Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327
