### ISSUE TITLE
Do we need to create a separate infinitive and imperative tables for irregular verbs?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#26]
we are missing to match several irregular verbs in the infinitive and imperative inflected tables. e.g. sum: esse is the pres. infinitive active but we do not have a match in the infinitive table.  es and este are the pres. imperative active but we do not have a match. esto and estote for the future imperative do not have a match, but we have a match for sunto (3rd person plural, fut imp act). we do not have a match for posse in the infinitive table, but we have one for potuisse. we do not have a match for malle (malo, male, malui), but we do for maluisse in the infinitive table. we do not have a match for ferto and fertote ( fut. imp) in the imperative table, but we have for ferunto. missing the infinitive matching for ferre.

**Comment by balmas** [comment]
this should be small and we should just do it.

**Comment by monzug** [comment]
we do have the infinitive and imperative in the forms.csv file for irregular verbs. I can copy these information and create a separate file as for participle and supine. @balmas, from your side which one is easier to implement: extract the infinitive and imperative from the big file or from a separate file such as for participle and supine?

**Comment by balmas** [comment]
I think the latter, separate files as for participle and supine, would be easiest. thanks!

**Comment by monzug** [comment]
Great. will do asap.

**Comment by monzug** [comment]
imperative and infinitive tables have been uploaded in github

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
1) We are missing the singular and plural from the imperative irregular  (see fer and ferte, they are on the same column)
2) the drop-down says verb-imperative-irregular-voice,  also for the infinitive for some verbs. why voice? see  adiri  vs  ivisse
could it be because one verb has also the passive?

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200804636
Alpheios Components 3.3.0-qa.20200804505

I added the person and number to the imperative irregular tables.

Re the 2nd question, this is because we have 2 distinct sets of views for the irregular verbs -- some of them have a voice column and some do not.  We need to have a different name for them in the code and that's what we came up with. 

Can you suggest a better way to name them that is more meaningful to the end user?

**Comment by monzug** [comment]
all verbs reported in this issue have a match in the imperative or infinitive irregular table.

as per the use of voice in the irregular infinitive/imperative verb, I would rather not add it. if this is not possible due to code constraint, I would add +passive voice.

not sure if this is the right time to suggest a little improvement in the verbs drop-down. see esse: it's verb participle and irregular infinitive. first we have verb participle  and verb, if I select verb, I have infinitive, then verb-irregular, then verb-irregular-infinitive and then all the others. would it be possible at least to have in the verb drop-down, infinitive irregular first, then verb irregular, then infinitive and then all the others?

**Comment by balmas** [comment]
>as per the use of voice in the irregular infinitive/imperative verb, I would rather not add it. if this is not possible due to code constraint, I would add +passive voice.

I will make that change.

**Comment by balmas** [comment]
>not sure if this is the right time to suggest a little improvement in the verbs drop-down. see esse: it's verb participle and irregular infinitive. first we have verb participle and verb, if I select verb, I have infinitive, then verb-irregular, then verb-irregular-infinitive and then all the others. would it be possible at least to have in the verb drop-down, infinitive irregular first, then verb irregular, then infinitive and then all the others? or highlight the verbs with a match in it

I've made a new issue for this. I'm not sure how hard or easy it will be but I will look into it.

**Comment by balmas** [comment]
> > as per the use of voice in the irregular infinitive/imperative verb, I would rather not add it. if this is not possible due to code constraint, I would add +passive voice.
> 
> I will make that change.

Turns out I *can* change the name and title of these views to just say irregular and drop the reference to voice. So I've done that. Will be in the next build.

**Comment by monzug** [comment]
Fantastic. Thanks

**Comment by balmas** [comment]
should be fixed in 
webextension qa.20200807379 
components qa.20200807247

**Comment by monzug** [comment]
can't see the change though. this is a good example of the used of voice and voice data for adeo. we have irregular (active and passive voice), irregular with voice data (active and passive voice), irregular with voice (active and passive voice)
see screenshots
![adeo-voice-data](https://user-images.githubusercontent.com/41396793/89650346-49025000-d890-11ea-9831-67fc0f72f4d4.JPG)
![adeo-voice](https://user-images.githubusercontent.com/41396793/89650361-4e5f9a80-d890-11ea-8d6a-ad78c4a22137.JPG)

**Comment by balmas** [comment]
sigh, I see that I never actually merged any of these changes. next build...

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200807525
Alpheios Components 3.3.0-qa.20200807377

**Comment by monzug** [comment]
yes! adeo has only irregular verbs in the inflection tables.
