### ISSUE TITLE
switching from Latin to Greek, does not refresh the lookup

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#260]
tested in Loeb Classics in Chrome on Mac in build Alpheios Reading Tools 3.1.0 build qa.20200420272
Alpheios Components 3.3.0-qa.20200420262
also, autocomplete is checked.
the latest word I entered in Latin lookup was vetale, then I switched to Greek language and I entered a greek word in lookup, I got the error message that vetale was not found in our greek resources and the greek word entered in the lookup was completed ignored. I had to refresh the page few times before lookup started working again.
see screenshot
![Screen Shot 2020-04-22 at 2 38 01 PM](https://user-images.githubusercontent.com/41396793/79983156-a3c19880-84a7-11ea-8d69-bf44a8c4b247.png)

**Comment by balmas** [comment]
not sure if this is related to the autocomplete/greek input changes or not but it might be.

**Comment by monzug** [comment]
you know, I have the same doubt so I did not enter it in the autocomplete

**Comment by irina060981** [comment]
I have found the problem - it was a bug from my code for autocomplete.
It would be fixed i PR

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
No longer reproducible in Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327
