### ISSUE TITLE
extra table shown with stemtype ath_w_aor for a verb with voice middle

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#267]
while testing issue #81, I checked the matching for some verbs in tables 31, 35 and 39. for δοίμην
we do display 3 tables (in the release we do display even 4!!!) but one of these is an active table while the verb is middle.
lookup for δοίμην
δέομαι 
1. verb, singular, present, mediopassive, optative, 1st, ew_pr, ew_denom, Attic epic Doric
δίδωμι 
1. verb, singular, aorist, middle, optative, 1st, ath_w_aor, epic
2. verb, singular, aorist, middle, optative, 1st, omi_aor
we do correctly display tables 20 and 39, but the verbpdgm50 table is for  - γιγνώσκω: Aorist System Active  and we do not have any active forms in the output.
verbpdgm50 is for ath_w_aor  stemtype with no restriction on the voice, even if it's only aorist active.
so, should we add a restriction on the voice? or is it ok as is?

**Comment by balmas** [comment]
I am fine with adding a restriction on voice to table 50. Will do so.

**Comment by monzug** [comment]
thanks! we can give it a try.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
We do not display table 50 anylonger.
