### ISSUE TITLE
should we add superlative endings to the latin adjective table?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#27]
in investigating alpheios-project/inflection-tables#82 @abrasax reports the following from the Allen and Greenough grammar.

<img width="980" alt="screen shot 2018-08-14 at 8 52 25 am" src="https://user-images.githubusercontent.com/644870/44115032-d5296794-9fda-11e8-8178-6d91b75144b5.png">

We don't currently have the superlative endings in our adjective table. Should we?

@monzug Harry would like to defer to you on this.

**Comment by monzug** [comment]
how do we want to handle this? Whitaker splits the superlative as "acerrimus" ( acerri - mus ), if we follow Allen and Greenough, we should have a superlative column with rimus as ending.

**Comment by monzug** [comment]
Dup of #28
