### ISSUE TITLE
Update usage of lexis.lexicalQuery for wordlist upload

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#271]
From the PR https://github.com/alpheios-project/alpheios-core/pull/266

I'm wondering if there are going to be any unexpected side effects of issuing the lexicalQuery.getData request without going through the regular process of initializing a new lexical request. getData issues a number of events that affect the interface.  It might be that we need to do more here, and suppress events during the lexical query getData when we're doing this sort of background request. I'd like to get some thoughts from @kirlat on this.

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios-core/pull/266_

**Comment by irina060981** [comment]
From my point of view `newLexicalRequest` method change data in ui, app, storage modules.
It is not needed for background process of updating homonym.
I belive that we need only to update homonym object here - that's why I think it is ok.
Would be glad to @kirlat 's opinion.

_Originally posted by @irina060981 in https://github.com/alpheios-project/alpheios-core/pull/266_

**Comment by irina060981** [comment]
@irina060981 I've tried to simplify a number of options of lexical query methods and I think it is important in order to keep it maintainable. Right now we have two types of requests identified by a `source` prop: a get selected text request from a page (identified by a `page` source) and a one initiated by the lookup component (source is `lookup`). It looks to me (please correct me if I'm wrong) that this is a third type of request. So maybe we can use a `source` filed to identify it (i.e. having it set to something like `wordList`)? We can modify a `lookupText()` API method so that it will take `source` as an additional parameter and will pass it through to `lexicalQuery`. Or we can create another special method like `wordListLookup()` that will be similar to `lookupText()` but will use a source of `wordList`. What do you think about that?

_Originally posted by @kirlat in https://github.com/alpheios-project/alpheios-core/pull/266_

**Comment by irina060981** [comment]
as I could see from the code - source is used similiar to my additional variable,
`source` is simply passed to `newLexicalRequest` method, and my variable is simply ignores `newLexicalRequest`

I didn't use source because I was not sure how widely it is used in the code.

I think, that it is useful to create a separate method for page lookup, input lookup and wordlist lookup, because both methods:
  - for input lookup and wordlist lookup doesn't need treebank analysis (because it couldn't have any treebank marks)
  - for wordlist we also don't need any ui events

@kirlat and @balmas , what do you think?

**Comment by kirlat** [comment]
> I think, that it is useful to create a separate method for page lookup, input lookup and wordlist lookup

I think it is a good idea, we have API methods for page and input lookups already (`getSelectedText()` and `lookupText()`), we can add a third one for word list requests. If this method should not have any UI-related business logic such as updating an interface and dealing with treebank data it can call `LexicalQuery.create()` directly. 

I think that dividing code into separate flows simplified maintenance: if we know that a certain method is used by one module only (such as a word list) we may not worry that any change in it will call any side effects in any other modules.

What do you think?

**Comment by balmas** [comment]
this sounds good to me. I think we will probably need to suppress all UI events for the lookup for the wordlist

**Comment by irina060981** [comment]
merged and closed
