### ISSUE TITLE
Resize needed when enabling input in betacode

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#273]
related to issue #104. 
1) If  Resize Options is set to Large, we can't see any longer the top of the Lookup and the enable autocomplete at bottom is off the area.  I have to change the resize option to medium to see the top. see screenshot

![resize-large](https://user-images.githubusercontent.com/41396793/80488799-eb737480-892c-11ea-84e7-156bc33ecb25.JPG)

2) when chars are not expanded, see screenshot
![resize-large-no-chars](https://user-images.githubusercontent.com/41396793/80489055-4c02b180-892d-11ea-9ad5-9a98fcca758e.JPG)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by monzug** [comment]
tested in FF and Chrome. looks good
