### ISSUE TITLE
Comparative and superlative adjective table and Whitaker

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#28]
an example of comparative adjective table could be found at 
http://dcc.dickinson.edu/sites/all/files/comparative_adjectives.pdf
In some latin grammars, the comparative adjective table is identical to the 3rd noun declension: melior, melior-is, melior-i etc.
problem is that Whitaker has different endings: meli-or, meli-oris, meli-ori etc.
If we add a comparative table with the endings as above pdf, we will still not have matches.
I think that Allen and Greenough is also using the endings as per the above pdf.
this also applies for the superlative . 
How do we want to resolve this?

from Allen and Greenough: chapters 122-127

  | melior , better STEM meliōr- for meliōs- |   | plūs , more STEM plūr- for plūs-
-- | -- | -- | --
  |   | SINGULAR
  | M., F. | N. | M., F. | N.
NOM. | melior | melius | ----- | plūs
GEN. | meliōris | meliōris | ----- | plūris
DAT. | meliōrī | meliōrī | ----- | -----
ACC. | meliōrem | melius | ----- | plūs
ABL. | meliōre ( -ī) | meliōre ( -ī) | ----- | plūre
  |   | PLURAL
NOM. | meliōrēs | meliōra | plūrēs | plūra
GEN. | meliōrum | meliōrum | plūrium | plūrium
DAT. | meliōribus | meliōribus | plūribus | plūribus
ACC. | meliōrēs ( -īs) | meliōra | plūrēs (-īs) | plūra
ABL. | meliōribus | meliōribus | plū ibus | plūribus

**Comment by balmas** [comment]
I think we could go ahead and do this but is it a dupe of #27 ?

**Comment by monzug** [comment]
well, it can be a dup if we consider comparative and superlative together. I will update the title

**Comment by monzug** [comment]
a general table for the comparative and one general for the superlative have been added. need to investigate if footnotes need to be added. in Whitaker comparative and superlative are added next to the case, sometimes.

**Comment by monzug** [comment]
footnotes added for comparative and superlative tables.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
@balmas, the comparative table does only display the neuter gender. Could it be that I added the feminine masculine both in the same line under gender? if this is the reason, should I repeat the line for feminine and then for masculine?

**Comment by balmas** [comment]
hmm. no it should work the way it is in the data file. It could be a problem with how I've setup the view. I'll take a look. thanks!

**Comment by balmas** [comment]
Yes, was a mistake in the view setup. Should be fixed now.

Alpheios Reading Tools 3.3.1 build qa.20200804636
Alpheios Components 3.3.0-qa.20200804505

**Comment by balmas** [comment]
@monzug are these tables okay now?

**Comment by monzug** [comment]
I have tested the comparative and are ok. I still have to finish testing
the superlative

**Comment by monzug** [comment]
few comments here. @balmas, let me know what you think and if any of this could be implemented:
1) I would remove the "consonant and i " from the Declension Stem in the comparative
2) I would add the big adjective table as we do with the verbs.
3) some superlative and comparative do not have the exact match in the table in the following cases:
- 1st declension adjective, comparative is 3rd declension
- 3rd declension adjective, superlative is 1st declension
in the Allen and Greenough's grammar, there is a note in section 124:  The comparative and superlative are really new stems, and are not strictly to be regarded as forms of inflection.
so, I would like to know if by removing the declension stem from the table (no reference to 1st declension for the superlative and 3rd declension for comparative) we would still have exact matches and if a 1st declension adjective would have an exact match in the comparative and if a 3rd declension adjective  would have an exact match in the superlative?

Testing should be done soon

**Comment by balmas** [comment]
>I would remove the "consonant and i " from the Declension Stem in the comparative table.

This is easy

> I would add the big adjective table as we do with the verbs.

This is more work but doable

>removing the declension stem from the table (no reference to 1st declension for the superlative and 3rd declension for comparative) we would still have exact matches and if a 1st declension adjective would have an exact match in the comparative and if a 3rd declension adjective would have an exact match in the superlative?

I think it probably does make sense to remove the declension from these tables, since each table only contains 1 declension anyway. It would solve the problem you describe.

**Comment by monzug** [comment]
THANKS!!!
