### ISSUE TITLE
Questions/suggestion on mousemove event

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#288]
related to issue #169
1) if I check mouse over (or move) for Chinese option, the login to save your word message is not longer generated in the pop-up. in Google docs, where mousemove is the default, the message is still generated. why such a difference?

2) to simplify the Mouse Move (or over) event, could we have an advanced section where we can configure the delay, the accuracy, Google docs container id?

3) I did also notice that the two digit words are not always selected on mousemove: sometimes it just ignored it, sometimes it does highlighte the line and generate a wrong pop-up, sometimes it does process the two digit word.
see examples below in Google doc

a) Ὅσοις τῶν ἀνθρώπων ἐκ τῆς αὑτῶν2 ὁρμωμένοις χώρας ὑπερόριοί τε ἀγῶνες καὶ κίνδυνοι συμβαίνουσιν, ἄν τι σφάλμα γένηται
- mousemove on τι  does not do anything. if I enter it in Lookup it says it's a pronoun. to generate the pop-up I need to move the mouse almost over the next word.
- mousemove on ἐκ  or  ἄν   works fine (though, I need to position the mouse at the very end of each word)

b) μάλιστα δὲ πρὸς τὴν φύσιν· ἔστι γὰρ οἷον ἀρχὴ
τῶν ζῴων. Ἐπιζητοῦμεν δὲ θεωρῆσαι καὶ γνῶναι τήν τε 
φύσιν αὐτῆς καὶ τὴν οὐσίαν, εἶθ’ ὅσα συμβέβηκε περὶ αὐτήν
- mousemove on  τε  it does highlight the line and generate a pop-up for the previous word. If I move the mouse at the very end of the two digit word, it does not do anything.
see screenshot
![te-in-popup](https://user-images.githubusercontent.com/41396793/80712292-c82cfe80-8abf-11ea-859a-7073998d010b.JPG)

**Comment by balmas** [comment]
>f I check mouse over (or move) for Chinese option, the login to save your word message is not longer generated in the pop-up. in Google docs, where mousemove is the default, the message is still generated. why such a difference?

That's a good question. @irina060981 can you investigate?

**Comment by balmas** [comment]
>to simplify the Mouse Move (or over) event, could we have an advanced section where we can configure the delay, the accuracy, Google docs container id?

Agree this is a good idea.

**Comment by balmas** [comment]
>I did also notice that the two digit words are not always selected on mousemove: sometimes it just ignored it, sometimes it does highlighte the line and generate a wrong pop-up, sometimes it does process the two digit word.
see examples below in Google doc

I suspect this is due to the mouseover accuracy setting. It's set to 10 pixes by default and it could be that is too small for a 2 character word, particularly depending upon the font.

**Comment by monzug** [comment]
the font is the same for the two digit words in my scenarios

**Comment by irina060981** [comment]
>>f I check mouse over (or move) for Chinese option, the login to save your word message is not longer generated in the pop-up. in Google docs, where mousemove is the default, the message is still generated. why such a difference?

>That's a good question. @irina060981 can you investigate?

Merged and fixed

**Comment by irina060981** [comment]
> simplify the Mouse Move (or over) event, could we have an advanced section where we can configure the delay, the accuracy, Google docs container id?

I have placed it to UI options:
![image](https://user-images.githubusercontent.com/12377640/81146167-1740cb00-8fbb-11ea-803e-7837b76d7720.png)

![image](https://user-images.githubusercontent.com/12377640/81146184-1dcf4280-8fbb-11ea-9092-16340811b84c.png)

**Comment by irina060981** [comment]
from @balmas
>It's okay to merge but I'm not sure about the options change. I was thinking maybe we would have a new "Advanced" options tab, which we could put things like the mousemove and google docs settings that we don't expect people to change, but want to make available in case we need to tell them to.

**Comment by irina060981** [comment]
>I did also notice that the two digit words are not always selected on mousemove: sometimes it just ignored it, sometimes it does highlighte the line and generate a wrong pop-up, sometimes it does process the two digit word.
see examples below in Google doc

There was a problem inside clearing punctuation Regex - now it is fixed
would be glad to get verification

**Comment by monzug** [comment]
Irina, I am ready to test this. where can I find a build with this fix?

**Comment by balmas** [comment]
not made yet ... soon!

**Comment by monzug** [comment]
ok. I thought there was attest environment somewhere. will wait.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200507327

**Comment by monzug** [comment]
Btw, I noticed that we used mouse move on UI and Mouseover in Features

**Comment by balmas** [comment]
> Btw, I noticed that we used mouse move on UI and Mouseover in Features

I thought @irina060981 fixed that via another issue that's pending a build right now but I will check

**Comment by monzug** [comment]
we still have mouseover and mouse move.
also in FF (loeb classics), the frame is not visible, while in FF latin library is barely visible.
see screenshots in Chrome and FF

![mouseover-FF](https://user-images.githubusercontent.com/41396793/81935936-62606c80-95bf-11ea-8bc6-76de7b40b237.JPG)

![mouseover](https://user-images.githubusercontent.com/41396793/81935939-63919980-95bf-11ea-97dd-b5b471285b13.JPG)

![mouse move](https://user-images.githubusercontent.com/41396793/81935941-63919980-95bf-11ea-9fe7-af082e90e555.JPG)

**Comment by irina060981** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/12377640/82035971-a2b90b00-96e3-11ea-99f8-51159c0376e5.png)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

(But you may want to wait until the next build when #361 is available to test this)

**Comment by monzug** [comment]
when is #361 be ready for testing? I see that it's waiting for verification but it is still assigned to Kirlat.

**Comment by balmas** [comment]
sorry, ready now. I missed it.

**Comment by monzug** [comment]
all issues reported have been fixed, including the log in  to save your words message missing when mouse movement was checked.
