### ISSUE TITLE
tege-eris, teg-ere is without accent. should it be?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#29]
considering that all other endings for the other conjugations have accents for this, I think we should add the accent. I did also check online grammars, some have the accent some don't.
Please confirm as in  Allen & Greenough there is no accent.

this is for the PASSIVE voice of the 3rd conjugation INDICATIVE PRESENT 2nd person singular.
also, all the other endings for the indic. pres passive are missing the accent.

**Comment by balmas** [comment]
@monzug I think we have removed other accents too, right?

**Comment by monzug** [comment]
I think I fix this one because we were not having a match. need to check

**Comment by monzug** [comment]
so all other passive forms have an accent in the second singular indicative except in the 3rd conjugation, as in Allen and Greenough's. is it an error or not? I don't know

**Comment by balmas** [comment]
not closed -- caught in the cross-fire of repository merging.

**Comment by monzug** [comment]
let's leave as is. it's controversial so let's embrace the Allen and Greenough's and Bennett's grammars.
