### ISSUE TITLE
vue warning on wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#294]
![Screenshot from 2020-05-01 13-22-39](https://user-images.githubusercontent.com/644870/80825698-e7568980-8bae-11ea-9069-78e049ecb591.png)

@irina060981 might this be related to the recent wordlist changes?

**Comment by irina060981** [comment]
oh - you are right - it is a simple bug - I missed it

**Comment by irina060981** [comment]
merged and closed
