### ISSUE TITLE
popup not displaying

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#295]
for some reason in the latest qa build (Alpheios Components 3.3.0-qa.20200501441)
the popup is not displaying at all. No error in the console, it just never gets displayed. it's size is set to 0 and display none.

@kirlat could this be related to any of the changes for resizing?

**Comment by irina060981** [comment]
@balmas and @kirlat , I am really sorry - it is a silly misspell in my code, I have fixed it!

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200504341

**Comment by monzug** [comment]
no problems with pop-ups in build  Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327
