### ISSUE TITLE
upgrade to the latest version of Auth0 lock library in login form

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#306]
We're currently using lock 11.14 the latest version is 11.23.1 

This is probably needed for Apple signing see alpheios-project/webextension#283
and for addressing same-site cookie warnings see alpheios-project/alpheios_nemo_ui#307

**Comment by balmas** [comment]
Need to schedule a time to do this so that we can test immediately since we don't have a dev login environment yet.

**Comment by balmas** [comment]
@monzug we decided to make this change live. Can you please do some testing on login per request in alpheios-project/webextension#283 ? Thank you!

**Comment by monzug** [comment]
this has been done
