### ISSUE TITLE
new "Advanced" options tab

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#309]
@abrasax and I discussed this and agreed that we would like to have a new "Advanced" options tab, which contains the mousemove and google docs settings. We should also put the Log Level setting there as well.

@irina060981 I understand your concern about it being a bucket of "other" settings, but we think that's better than having them in the UI tab.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
question: we still have Mouse Move in Advanced tab but mouse over in Word Selection: Use Mouseover to Select Words (recommended for Chinese)

**Comment by balmas** [comment]
I will look at all the mouseover text and regularize it.

**Comment by irina060981** [comment]
I am sorry, but I couldn't explain why it is again Mouseover here
from my memory - I changed it twice times, but it continues to be Mouseover
and again I couldn't find this change in my PRs :)

it is some tricky games with my mind!

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

Normalization of mousemove language. Should now say "Mouse movement over text"

**Comment by monzug** [comment]
YES! mouse movement is now used in Features and in Advanced tab.
as per mobile, is there anything that can be done to improve the view of the advanced tab in iPhone 8 and iPhone xr?  in iPhone 11 they are all aligned
![IMG_4547 (1)](https://user-images.githubusercontent.com/41396793/83763013-34ae9680-a646-11ea-9d69-514faf239581.PNG)

**Comment by balmas** [comment]
@irina060981 can you look at the formatting on mobile?

**Comment by irina060981** [comment]
I suggest to reduce the font-size this way

![image](https://user-images.githubusercontent.com/12377640/84140022-481d8f80-aa94-11ea-89ba-831fcbafa1f1.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

**Comment by monzug** [comment]
Looks good now, except when going from Advanced to Resources, the Resources tab is shift to the left. UI, Features and Advanced are displayed correctly.

**Comment by balmas** [comment]
I'm guessing this should be an easy css change...

**Comment by monzug** [comment]
Unfortunately I am not able to upload the jpg in gitthug

**Comment by kirlat** [comment]
I was able to reproduce the issue and is on my way to fix it

**Comment by kirlat** [comment]
I fix for the Resources tab width has been merged to master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200612198
Alpheios Components 3.3.0-qa.20200611509

**Comment by monzug** [comment]
looks good. Thanks
