### ISSUE TITLE
Extra space between searched word and the result

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#316]
related to issue #157 
there is an extra space between the searched word and the result.  
build   Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327 

see screenshot
![extra-space](https://user-images.githubusercontent.com/41396793/81705345-f2c27400-943c-11ea-8874-7caa96de70f0.JPG)

**Comment by balmas** [comment]
@irina060981 can you investigate? Thank you!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200514430 (and later)

**Comment by monzug** [comment]
this is gone in build  Alpheios Reading Tools 3.1.0 build qa.20200514494
Alpheios Components 3.3.0-qa.20200514430
