### ISSUE TITLE
remove time from display of last_updated on wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#317]
in review with @abrasax we decided that it is unnecessary to show the timestamp of the last_updated field to the user. We should definitely save a full timestamp but the display should just show the date.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200514430

**Comment by monzug** [comment]
timestamp is not longer visible in build  Alpheios Reading Tools 3.1.0 build qa.20200514494
Alpheios Components 3.3.0-qa.20200514430
