### ISSUE TITLE
wordlist - remove "by" in dropdown limit labels

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#318]
Currently the wordlist limit drop down is labeled as "Limit to" and then each of the items in the limit list starts with "by", which doesn't make sense grammatically.  We should drop the "by" on the label text for each of the items in the limit dropdown

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
totally agree with this change. Limit to this session, limit to important, limit to lemma etc
