### ISSUE TITLE
support syriac words parsed with meaning but no inflection data

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#319]
for some words sedra returns meanings but no inflection data. We currently are showing no results found for them because they don't have at least a part of speech, the default rule for the adapter. We should allow these for the sedra engine.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
@balmas, do you have a list of words that I can test with this fix? I double click a bunch of words at sedra and they look fine to me.

**Comment by balmas** [comment]
I found it by chance with this one:

ܐܒܪܐ

**Comment by monzug** [comment]
also   ܐܝܬܝܗܘܢ 
they both work now
