### ISSUE TITLE
add lang attribute to lemma in short definition on popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#320]
we don't currently include the lang attribute on the lemma next to the short definition in the morph component, which prevents language-specific font, etc. from being applied.

E.g. see result for ܐܒܪܐ in syriac, font is correct on the form and the top lemma, not on the lemma next to the short def.
![7ac0aa36-ee50-481e-b198-8e099f913d19](https://user-images.githubusercontent.com/644870/81730023-eea54f00-945a-11ea-982b-ca7595f911ae.png)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
tested in Chrome. looks good now

![aramaic](https://user-images.githubusercontent.com/41396793/81937697-f5020b00-95c1-11ea-9fcd-3fec8078e02c.JPG)

**Comment by monzug** [comment]
actually, I ma not so sure about this one:  see screenshot
ܫܘܩܠܐ
![syriac-firstletter](https://user-images.githubusercontent.com/41396793/81939002-c08f4e80-95c3-11ea-91ec-226831559375.JPG)

**Comment by monzug** [comment]
the lookup looks different from the morphology pop-up and from the lemma

![syric-not-sure](https://user-images.githubusercontent.com/41396793/81939312-2ed41100-95c4-11ea-9a87-7bbe68555f45.JPG)

**Comment by monzug** [comment]
![a-syriac-name](https://user-images.githubusercontent.com/41396793/81941063-55934700-95c6-11ea-9ea5-e39b94a531a5.JPG)

**Comment by balmas** [comment]
pfft. I hate the Loeb site. Their font settings are overriding ours.  

So since the problem is not because this item isn't fixed, it's because our font settings are being overruled, I'll enter a new issue for this.

As for the lookup box, yes we probably should apply fonts to that too, we aren't right now. I'll enter an issue for that too. Thanks!

**Comment by balmas** [comment]
Issued raised above are covered in #338 and #339

**Comment by monzug** [comment]
this is fixed in build Alpheios Reading Tools 3.1.0 build qa.20200514494
Alpheios Components 3.3.0-qa.20200514430

![lead-syriac](https://user-images.githubusercontent.com/41396793/82449505-4ce4ba00-9a79-11ea-8145-7b166b149ee6.JPG)
