### ISSUE TITLE
make default max size of popup smaller

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#322]
I think we should make the max default size of the popup smaller than it is, now that we have added the ability for people to configure this (via #263). Currently the default is 1200px which produces a really big popup when definitions or credit text is long.

I think the medium width of 800px would probably work.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200513442

**Comment by monzug** [comment]
is there a way that if we exceed the popup limit, text can wrap to an other line?
see screenshot
![example-adj-dialect](https://user-images.githubusercontent.com/41396793/81947254-55974500-95ce-11ea-90ea-23717075edb8.JPG)
see https://github.com/alpheios-project/alpheios-core/issues/336

**Comment by balmas** [comment]
@kirlat can you look at the wrapping issue? Thanks!

**Comment by kirlat** [comment]
Fixes are merged to master.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
YES!
![pop-up-rewrap](https://user-images.githubusercontent.com/41396793/82822889-84d26f80-9e74-11ea-8165-f47076ea4738.JPG)
