### ISSUE TITLE
Pop-up is slightly different from release

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#328]
related to #251 
I noticed a couple of differences with the release
1) we are missing the semi colon
2) verb participle is not in green
see screenshots
RELEASE

![release-loeb](https://user-images.githubusercontent.com/41396793/81815047-86f11180-94f7-11ea-8a7a-e53afc183216.JPG)

BUILD Alpheios Reading Tools 3.1.0 build qa.20200507338
Alpheios Components 3.3.0-qa.20200507327

![build](https://user-images.githubusercontent.com/41396793/81815311-d1728e00-94f7-11ea-95f0-2ec6623c3fd9.JPG)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200514430 (and later)

**Comment by monzug** [comment]
fixed in  Alpheios Reading Tools 3.1.0 build qa.20200514494
Alpheios Components 3.3.0-qa.20200514430
