### ISSUE TITLE
Can we improve the look of input betacode?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#329]
1) I do not like that the text is not aligned with Word lookup
2) the font is different, also in size
3) the question mark is slightly not aligned and also the style is different from the page
4) Overlapping of the frame of the lookup when expanded with the toolbar
5) check box is input Betacode, the text below starts with Betacode input. Why?
6) can we add an extra space between the sample characters and the separation line?

see screenshot in FF
![betacode-lookup](https://user-images.githubusercontent.com/41396793/81818711-5f507800-94fc-11ea-9f12-9cca3b2c8175.JPG)

**Comment by balmas** [comment]
@monzug this is mostly going to change with the fixes described at https://github.com/alpheios-project/alpheios-core/issues/104#issuecomment-625489286

**Comment by monzug** [comment]
Great. I change to waiting verification and assigned to me when 104 is done.

**Comment by monzug** [comment]
this is all gone with the new Advanced tab in Options.
I wouldn't mind to add extra space between the sample characters and the separation line. @balmas?

**Comment by balmas** [comment]
that's a good idea. @irina060981 can you do that for me? Thank you!
