### ISSUE TITLE
Add extra space between beta chars and the separation line below it

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#334]
I wouldn't mind to add extra space between the sample characters and the separation line. @balmas?

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/329#issuecomment-628598818_

**Comment by irina060981** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/12377640/82034067-042baa80-96e1-11ea-94d8-6074c98bdf7c.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
I don't think this fix is the build  Alpheios Reading Tools 3.1.0 build qa.20200522460
Alpheios Components 3.3.0-qa.20200522457

**Comment by irina060981** [comment]
it is trange - but it is missed in the most last version in repository

**Comment by irina060981** [comment]
and I could see that the height of the lookup box is bigger than in my change.
Will do this changes again to the code

**Comment by irina060981** [comment]
also I could see that border styles for Loeb missed again - will fix them too
![image](https://user-images.githubusercontent.com/12377640/82860061-dace1280-9f5b-11ea-9835-08a94be5cfd0.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
space and border style are fixed. Thanks
