### ISSUE TITLE
Size of Greek lookup is bigger than release

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#337]
I noticed that latin lookup is regular size, it covers the help, lookup and Additional resources. however when I switch to Greek language, the lookup is much larger. it goes below the Browse Inflection tables icon. Is it related to the changes for  betacode input feature? I did previously enable and disable the checkbox for Show Betacode to Unicode Mapping Help

**Comment by irina060981** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12377640/82032914-4f44be00-96df-11ea-9cc6-693f4ff0e634.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
tested in FF and Chrome - fix in build  Alpheios Reading Tools 3.1.0 build qa.20200522460
Alpheios Components 3.3.0-qa.20200522457
