### ISSUE TITLE
language specific font settings being overruled in Loeb Classics

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#338]
![a-syriac-name](https://user-images.githubusercontent.com/41396793/81941063-55934700-95c6-11ea-9ea5-e39b94a531a5.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/320#issuecomment-628639914_

**Comment by irina060981** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/12377640/82032778-186ea800-96df-11ea-82c1-10c321724c0b.png)

![image](https://user-images.githubusercontent.com/12377640/82032855-320fef80-96df-11ea-996d-b2b6901f923b.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
I tested few words in Loeb classics and it looks ok.
