### ISSUE TITLE
can we add the lang attribute to the lookup input box?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#339]
@monzug notes in #320 that the lookup box uses a different font for syriac and arabic than we do on the popup. This is because we use the lang attribute to trigger better fonts for those languages in our css. Is it possible to apply the same to the lookup input box?

**Comment by irina060981** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/12377640/82032778-186ea800-96df-11ea-82c1-10c321724c0b.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
looks ok to me.
