### ISSUE TITLE
Add help for wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#345]
>the arrows should have a tooltip

The problem with tooltips is that they don't work on mobile. So I think we probably do need to have a popup help for the wordlist then.  I will create an issue for that.

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios-core/issues/200#issuecomment-630217861_

**Comment by balmas** [comment]
With the additional limits for most frequent and updated the wordlist display is getting complicated enough that we need some help for it. Tooltips would be ideal but they won't work well on mobile. So I think maybe we need a popup help screen,

**Comment by balmas** [comment]
assigning to myself to define the requirements for this ...

**Comment by balmas** [comment]
Actually, I see that we do already have a mouseover tooltip on the important and delete columns. One difference is those are active items, but I think we could probably just add similar tooltips to the other two columns for now:

for the frequency column:

"The number of times you have looked up this word."

"The date this entry was added or updated."

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
tooltip is not on the column but on each element of the column. is this ok?

![Screen Shot 2020-05-28 at 2 43 07 PM](https://user-images.githubusercontent.com/41396793/83143101-bb68ee00-a0f1-11ea-9385-9145590209c9.png)
![Screen Shot 2020-05-28 at 2 42 57 PM](https://user-images.githubusercontent.com/41396793/83143105-bc9a1b00-a0f1-11ea-8fd0-e24ed6bd6399.png)

**Comment by irina060981** [comment]
>tooltip is not on the column but on each element of the column.

I have created it similiar other columns, you could see that each icon has its own tooltip in the row

**Comment by balmas** [comment]
Yes I think it's fine the way it is.
