### ISSUE TITLE
update Syriac punctuation list

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#347]
actually, I have a question here. if I double click on desiderat.  it takes also the dot as the page language is syriac. interesting, in the wordlist it's displayed with the dot first. it's ok, right?
see wordlist

![desiderat](https://user-images.githubusercontent.com/41396793/82230243-7676d780-98f9-11ea-87ef-7a74c35a0e7d.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/346#issuecomment-630253522_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
the dot has been removed.
