### ISSUE TITLE
DOM Warning on duplicate id

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#350]
we have a new DOM warning about duplicate elements with the id #alpheios-lookup-form-input

![Screenshot from 2020-05-18 12-56-31](https://user-images.githubusercontent.com/644870/82239605-0b340200-9907-11ea-8085-66b049d8fd7a.png)

Maybe a result of the autocomplete changes??

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
no warnings anymore in Alpheios Components 3.3.0-qa.20200602383
