### ISSUE TITLE
mousemove preference should be limited to tab

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#352]
> I've also noticed another issue: if there is a Google document opened in a tab, and an Alpheios is activated in it, a mousemove mode becomes activated on all other tabs as well: if to hold mouse over a word, it starts a lexical query, no matter what tab it is. I'm wondering if anyone else can reproduce it or is it just me.

_Originally posted by @kirlat in https://github.com/alpheios-project/alpheios-core/issues/315#issuecomment-630354869_

**Comment by kirlat** [comment]
I can't reproduce it any more. It probably was some random glitch within my environment. 

If nobody else has this problem, this issue can probably be closed.

**Comment by balmas** [comment]
Will ask @monzug to verify

**Comment by monzug** [comment]
I have a note that few times mouse over was activated even if it was disabled in options. I haven't seen it recently but will test your scenario.

**Comment by monzug** [comment]
Nope, I can't reproduce Kirlat's scenario. good.
