### ISSUE TITLE
fix formatting of wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#357]
A couple of points, possibly mentioned already elsewhere:

* I think need to prevent the date from wrapping to a new line
* the sort arrows need to be centered over the data column

![Screenshot from 2020-05-19 13-58-43](https://user-images.githubusercontent.com/644870/82361533-f889fd80-99d8-11ea-8667-42d357e2f4be.png)

**Comment by irina060981** [comment]
Merged and fixed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
looks ok now
![ancora-limit-wordlist](https://user-images.githubusercontent.com/41396793/82830057-b81bfb00-9e82-11ea-8216-c8cd06512031.JPG)
