### ISSUE TITLE
Short def has too much information

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#367]
white testing #186 , I come across this pop-up and noticed a difference with the release.
we added Vanessa's short def, but this one looks weird as it has too much information and not so clear ( ὀδόντων )

![Screen Shot 2020-05-21 at 4 25 26 PM](https://user-images.githubusercontent.com/41396793/82569099-0f1e8900-9b80-11ea-9af8-c025ff408b1c.png)

vs release

![Screen Shot 2020-05-21 at 4 28 47 PM](https://user-images.githubusercontent.com/41396793/82569192-2d848480-9b80-11ea-8e3f-04c81d4342e2.png)

**Comment by balmas** [comment]
this is a short def that was wrong in ML and correct in LSJ.  I've corrected it now, can test once the new index is deployed.

**Comment by balmas** [comment]
updated short defs index is live now.

**Comment by monzug** [comment]
much betetr. now we have ὀδόντων  as tooth and ionic for ὀδous
