### ISSUE TITLE
Paradigm table is different  from Mastronarde table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#368]
white testing #186 , I notice that the Consonant-Declension Nouns: stems in ι or υ has different endings than the one in Mastronarde. Only the first line is identical.

Consonant-Declension Nouns: stems in ι or υ in Alpheios

![Screen Shot 2020-05-21 at 4 52 46 PM](https://user-images.githubusercontent.com/41396793/82572279-67578a00-9b84-11ea-9742-ea246ae2f912.png)

Consonant-Declension Nouns: stems in ι or υ in Mastronarde

![Screen Shot 2020-05-21 at 4 52 23 PM](https://user-images.githubusercontent.com/41396793/82572168-4a22bb80-9b84-11ea-9786-ce788cdc483d.png)

**Comment by irina060981** [comment]
would be fixed in PR

![image](https://user-images.githubusercontent.com/12377640/82966131-6ce22380-a00d-11ea-82c6-afc0d2f143aa.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
fixed in Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404
