### ISSUE TITLE
If Greek gender is missing, we do show (null)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#369]
look for  ἥρωϊ   - we do display null next to noun. is it necessary?  this is also in the release
see screenshot

![Screen Shot 2020-05-21 at 5 23 52 PM](https://user-images.githubusercontent.com/41396793/82574859-016d0180-9b88-11ea-834c-d12deda9eb21.png)

**Comment by balmas** [comment]
this should be an easy fix

**Comment by kirlat** [comment]
Should in that case we remove a `(null)` completely and display just `noun; 3rd declension`?

**Comment by balmas** [comment]
yes

**Comment by kirlat** [comment]
A fix has been merged to master

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
fixed in build Alpheios Reading Tools 3.1.0 build qa.20200522460
Alpheios Components 3.3.0-qa.20200522457
