### ISSUE TITLE
Wrong endings for adj paradigm tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#370]
related to issue #186.
look up for   ἄδικᾰ, it should be plural nom, acc. and voc. (n).    in the Alpheios paradigm table, the accusative is ἀδίκους  in  Vowel-Declension Adjectives with Two Endings table
it should be  ἄδικᾰ

**Comment by monzug** [comment]
an other wrong ending in the Vowel-Declension Adjectives with Contraction (-εος) table 
the nom, voc, plural (neuter) is χαρίεντᾰ  but it should be  χρυσᾶ

**Comment by irina060981** [comment]
First fix
![image](https://user-images.githubusercontent.com/12377640/82966788-078f3200-a00f-11ea-82a8-0d2bb8282c91.png)

**Comment by irina060981** [comment]
Second
Vowel-Declension Adjectives with Contraction (-εος)

![image](https://user-images.githubusercontent.com/12377640/82968997-ec71f180-a011-11ea-8fa3-2b0cf109178c.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
Fixed in Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404
