### ISSUE TITLE
remove stemtype on table and cell matches in Greek Noun and Adj paradigms

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#372]
lookup for λαγώ  - we do not highlight the dual nom, voc,acc, I think we should add the following in rules.csv

nounpdgm17 | 1 | noun | os_ou | 2nd |   | λαγῶς

and also the wn_onos stemtype

we should probably add the following so we have a match for the genitive singular for ἥρως

nounpdgm18 | 1 | noun | ws_oos | 3rd |   | ἥρως

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/186#issuecomment-632143510_

**Comment by balmas** [comment]
it's not actually rules.csv that needs to change here but the paradigm table cell data itself

it looks to me like morpheus can report different stemtypes for a single word

Since for now we are restricting the matching into the tables at all based upon lemma (until #373 is fixed), I think we should probably remove stemtype from both the rules and the cell data.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
they both work in build Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404
