### ISSUE TITLE
Autocomplete broken - Logeion API change

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#385]
it looks like the Logeion API is requiring an API key now. Investigating...

**Comment by balmas** [comment]
ok, we have a key now and the url and the syntax has also changed.

Baseurl for and apikey for logeion requests can now be retrieved from the config service. Settings are described at alpheios-project/alpheios-config-api#3

we can also now add the language to the request so we don't have to filter the wrong language entries out ourselves anymore.

The new syntax is

`<loegion baseurl>?key=<key>q=<query>&lang=<lang>`

**Comment by balmas** [comment]
@irina060981 you can retrieve the logeion and baseurl settings from the UIController.appConfig object (available in state in `api.app.config`). If that object is not defined then the autocomplete feature should be unavailable.

We can eliminate the call to filter out the other language now too, by using the lang parameter.
Let me know if you have any questions. Thanks!

**Comment by irina060981** [comment]
>We can eliminate the call to filter out the other language now too, by using the lang parameter.

@balmas , from my testing we couldn't stop eliminating by language in our code, because logeion API doesn't do it correctly

for example the request:
https://api-v2.logeion.org/logeion2/search?key=<key>&q=male&lang=lat

returns greek words
![image](https://user-images.githubusercontent.com/12377640/83121139-44dde780-a115-11ea-9483-a01a69a86d77.png)

**Comment by balmas** [comment]
![eba4a479-81b2-441d-890d-dffd14984752](https://user-images.githubusercontent.com/644870/83139171-edf6f480-a0b9-11ea-8fe0-b14c1c827219.png)

Yes I see what you mean. Apparently the parameter needs to be set to either 'latin' or 'greek' but that doesn't work either...

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

**Comment by monzug** [comment]
autocomplete is in. tested in Chrome on PC and Mac.
I checked the elimination of words from other languages, but this hasn't been implemented correct?
e.g. car -> carle, cart, Carmo are still in autocomplete

**Comment by balmas** [comment]
>I checked the elimination of words from other languages, but this hasn't been implemented correct?
e.g. car -> carle, cart, Carmo are still in autocomplete

I'm not sure we can do anything about this for non-latin words with characters that are valid latin characters.  I will report to Logeion that the language filter on their end isn't working. On our end, all we can really do is filter out the greek versus the latin by checking the unicode chars

**Comment by monzug** [comment]
so, I haven't tested this! if it has been implemented, I need to check it

**Comment by balmas** [comment]
it might be tough to test -- the Logeion folks tell me they just fixed the language filter...

**Comment by monzug** [comment]
both examples above (male and mou) didn't return any greek or latin words in autocomplete

**Comment by balmas** [comment]
? I don't understand. It works for me

**Comment by monzug** [comment]
sorry, I thought I made it clear but apparently not: male does not return any greek words (only latin or similar), mou returned only greek words

**Comment by balmas** [comment]
ok great. sorry I missed the verified tag.
