### ISSUE TITLE
should we add - (hyphen) to list of punctuation?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#392]
Right now if a word has a hyphen it gets included in the lookup. E.g.

veni-

I think maybe we should consider hyphen punctuation and strip it out.

**Comment by balmas** [comment]
@monzug do you have any thoughts on this? Have you encountered in testing situations where it's important to include the hyphen?

**Comment by monzug** [comment]
uhm, I cannot think of any word right now

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

**Comment by monzug** [comment]
question: if the hyphen is stripped out, shouldn't the e-o double click work? note that lookup for e-o works fine. 
see this site https://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/

**Comment by balmas** [comment]
ahhh, so now I think you might have uncovered why we left the hyphen out of the punctuation list.  

We replace all punctuation with spaces, assuming it's not part of a word.  so e-o in a page will be looked up as "e" . We don't strip punctuation out of the lookup box entry at all.

In the future maybe we should be more intelligent about this, replacing some punctuation with spaces, others stripping it out entirely.   I think it would have to wait for refactoring of our selection code however.

@monzug what do you think? Should we revert to the prior behavior and assume hyphens are valid word characters?  Maybe just for latin for which the parser seems to deal with them as such?

**Comment by monzug** [comment]
I don't know. I have been stuck thinking for a good answer but I haven't come up with one. sorry. maybe reverse this fix?

**Comment by monzug** [comment]
in the https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/index.html,  we have  μὲν—οὐ  with the hyphen  in the treebank too.  what's the best solution for this word?

**Comment by balmas** [comment]
There it's an em-dash (unicode 2014). I'm not really sure what it's meant to represent. 

I am going to reverse the inclusion of the hyphen in the punctuation lists I guess.

**Comment by balmas** [comment]
Reverted in 

Alpheios Reading Tools 3.3.0 build qa.20200605325
Alpheios Components 3.3.0-qa.20200605311

**Comment by monzug** [comment]
reverted and tested in Safari App Extension 3.3.0 build qa.20200605325
Alpheios Components 3.3.0-qa.20200605311

![Screen Shot 2020-06-09 at 2 49 12 PM](https://user-images.githubusercontent.com/41396793/84149266-78e3d180-aa60-11ea-870d-256ebbdd767b.png)
