### ISSUE TITLE
pop-up shrinks and enlarges when downloading to flashcard

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#398]
When downloading a wordlist to flashcard while lexical data message is loading, the pop-up changes in size few times, it shrinks then it enlarges then it shrinks again few times (Chrome on Mac)

**Comment by balmas** [comment]
I can live with the growing/shrinking but the fact that is happening tells me that some state variable is probably being affected by the lookups that is affecting the popup display.  

@irina060981 can you investigate?

**Comment by irina060981** [comment]
yes, I could see this - each word from wordlit update uploads in popup (and it is strange)
will check

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

**Comment by monzug** [comment]
This is not longer reproducible in build  Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383
