### ISSUE TITLE
FF on Mac: no treebank icon is generated 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#405]
tested in FF on Mac. No icon was generated for texts that do normally support treebanking, like Aeschylus and Homer. see issue #258  where it has been initially reported

**Comment by balmas** [comment]
@monzug what version of Firefox on Mac? It worked for me in both FF 75 and FF 77

Which Mac OS also?

**Comment by monzug** [comment]
![Screen Shot 2020-06-03 at 5 45 49 PM](https://user-images.githubusercontent.com/41396793/83658200-2e76d680-a5c2-11ea-9782-38d2868b8dfe.png)

**Comment by balmas** [comment]
This might be an OS issue. I'm using Catalina.

Can you tell me
(1) do Chinese lookups work for you Firefox on the Mac?
(2) are you able to browser the trees here in Firefox on the Mac? http://trees.alpheios.net/

**Comment by monzug** [comment]
I am getting it in Chrome on PC but not in FF on MAC, I get a blank page

**Comment by monzug** [comment]
Chinese lookups work in FF/Mac

**Comment by balmas** [comment]
>I am getting it in Chrome on PC but not in FF on MAC, I get a blank page

Do you mean the trees at http://trees.alpheios.net/ ?

**Comment by monzug** [comment]
yes. trees.alpheios.net -> FF/Mac blank page

**Comment by balmas** [comment]
Actually @monzug can you test one more thing for me? Do the trees here load in FF on Mac?
https://perseids-publications.github.io/treebank-template/
