### ISSUE TITLE
flashcard download - exclude header, fix filename

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#406]
I think we should exclude the header row from the flashcard download and also use the file extension .tsv instead of .csv to make it clear that it is tab-separated.

**Comment by irina060981** [comment]
fixed, merged and closed

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

**Comment by monzug** [comment]
tested in Chrome and FF on PC and Chrome on Mac. confirm that file ext is tsv now. Header is gone but on Mac it looks like the first  of the wordlist is replacing the header. see screenshot

**Comment by balmas** [comment]
@monzug I think that's just how the editor is interpreting it, but that's okay. The Quizlet import assumes no header row.  

![quizletimport](https://user-images.githubusercontent.com/644870/83642451-da95ce80-a57c-11ea-8914-3d177c49c24d.png)

**Comment by monzug** [comment]
ok. I'll close it
