### ISSUE TITLE
Selection for Syriac words doesn't work

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#408]
@balmas , while working on https://github.com/alpheios-project/alpheios-core/issues/404
I have found that here
http://www.tertullian.org/rpearse/thesyriaclibrary/eusebius_of_caesarea_encomium.htm

I couldn't select a Syriac word from the text
it throws a error from our code

![image](https://user-images.githubusercontent.com/12377640/83485591-b4bfe980-a4ea-11ea-88fa-bd27f0f97268.png)

**Comment by irina060981** [comment]
The same problem with embed-lib in demo/index.html

**Comment by balmas** [comment]
oh -- this is my bug. Introduced in PR for #392 It needs to be fixed in all of the language model classes then.

**Comment by irina060981** [comment]
Fixed for all languages, merged and closed
