### ISSUE TITLE
fix the size of the header when repositioning

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#417]
Reported by @abrasax 

If the popup is taller than the screen, when we are calculating the correct position for it there is a phase when the popup header gets smooshed before it returns to its normal size.

This can be seen in the video at 
https://www.awesomescreenshot.com/video/180814?key=3acad7792b77c2f89a9781c26e45b219

@kirlat can we fix this in the CSS somehow?

**Comment by kirlat** [comment]
A fix is in the master now.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200605325
Alpheios Components 3.3.0-qa.20200605311

**Comment by monzug** [comment]
I knew Harry wouldn't like it! fix in latest build  Alpheios Reading Tools 3.3.0 build qa.20200605325
Alpheios Components 3.3.0-qa.20200605311 
tested in Chrome, FF and Safari
