### ISSUE TITLE
cannot select same word twice in a row with Long Tap on Mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#422]
This appears to be a new problem with this release -- I can't reproduce it at texts.alpheios.net, but can reliably at texts-test.alpheios.net

Steps to reproduce:

https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi001.perseus-lat2/passage/1.ep.1-1.ep.4

long tap on "modo"
see the popup appear
close the popup
long tap on "modo" again
no popup
long tap on another word
popup appears
long tap again on "modo"
popup appears

Same sequence at https://texts.alpheios.net/text/urn:cts:latinLit:phi0959.phi001.perseus-lat2/passage/1.ep.1-1.ep.4 does not demonstrate the problem.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

**Comment by monzug** [comment]
I can't repro the issue described above on my iPhone xr.
