### ISSUE TITLE
treebank icon is available for lookup word that is not in the diagram

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#426]
while testing #166, I have noticed that if I enter a latin word in lookup (that is NOT in the diagram) such as caro, the pop-up will offer the diagram icon. when I click on it, it will generate the last seen diagram
to repro: in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.30
double click on mundi and look at the diagram. the close pop-up, go to lookup and enter caro. the pop-up will have the diagram icon and will generate the diagram with mundi.
this is not reproducible in release environment

![caro-with-diagram](https://user-images.githubusercontent.com/41396793/83890967-8163a180-a71a-11ea-8386-d0bd011818f0.JPG)

the icon is not longer generated after I double click on a word with no diagram

**Comment by balmas** [comment]
@kirlat is it possible we broke this with latest changes for #258 (for https://github.com/alpheios-project/alpheios-core/issues/258#issuecomment-634119573) ?

**Comment by kirlat** [comment]
Will look into that

**Comment by kirlat** [comment]
> @kirlat is it possible we broke this with latest changes for #258 (for [#258 (comment)](https://github.com/alpheios-project/alpheios-core/issues/258#issuecomment-634119573))

Yes, that was it and then another. Submitted a fix.

**Comment by kirlat** [comment]
Code that solves this is in master now

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

**Comment by monzug** [comment]
Fixed. Thanks
