### ISSUE TITLE
lemma translations aren't working

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#428]
I'm guessing this broke with the lexical query refactoring, but the request for the lemma translations is not occurring anymore.

**Comment by kirlat** [comment]
A fix is in master now

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

**Comment by monzug** [comment]
tested lemma translations for all languages in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.30
and Chrome
