### ISSUE TITLE
paradigms - subtables not shown in browser

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#43]
the paradigm subtables are not shown in the browser view of a table

See e.g. paradigm 11 Perfect Active System (reported by @monzug  in alpheios-project/inflection-tables#207)

This is related to alpheios-project/inflection-tables#23

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
paradigm 11 Perfect Active System  does show up now in build Alpheios Reading Tools 3.1.0 build qa.20200410484
Alpheios Components 3.3.0-qa.20200410462
