### ISSUE TITLE
Super minor: loeb classics button has wrong background

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#432]
FF on MAC
see screenshot 
![Screen Shot 2020-06-08 at 3 57 06 PM](https://user-images.githubusercontent.com/41396793/84038986-e0d2e300-a9a0-11ea-9ad5-1c7995bdb8a2.png)

**Comment by kirlat** [comment]
A fix has been merged to master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405
