### ISSUE TITLE
problem loading fonts in Safari

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#434]
I was checking the log and got some error messages on fonts.gstatic.com in safari,  see screenshot
![Screen Shot 2020-06-08 at 5 04 08 PM](https://user-images.githubusercontent.com/41396793/84046343-42e41600-a9aa-11ea-9007-83776abf6e80.png)

I was not able to reproduce the character issue in wordlist. sometimes I see that the character is loading and then it displayed correctly, so the fix is verified.
@irina060981 and @balmas, do the errors in the log give you any interesting info?

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/404#issuecomment-640690159_

**Comment by balmas** [comment]
@kirlat can you double check this? I'm not sure if there is a problem with our font url or if Safari doesn't support google fonts, or ...?

**Comment by kirlat** [comment]
Looking at that now

**Comment by kirlat** [comment]
A fix has been merged to master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

**Comment by monzug** [comment]
I did not see those error messages in the log anymore
