### ISSUE TITLE
Safari build, icons are misplaced on first pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#435]
I saw this issue twice today. First lookup after installation or after a long time of inactivity in Safari,
the related morphology pop-up is missing all the icons, actually they are misplaced as they moved  in the middle of the pop-up. Lookup an other word and all goes back to normal.

![Screen Shot 2020-06-08 at 5 51 54 PM](https://user-images.githubusercontent.com/41396793/84053089-bb020a00-a9b1-11ea-8cf7-df50f8d19b8d.png)

![Screen Shot 2020-06-08 at 5 51 09 PM](https://user-images.githubusercontent.com/41396793/84053354-13390c00-a9b2-11ea-8d26-de23569e408e.png)

**Comment by kirlat** [comment]
I've merged updates that, hopefully, would eliminate this.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405
