### ISSUE TITLE
words from current session missing in limit by most recent

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#442]
Chrome on PC. login as google user monzug again
1) add some new words to wordlist (Alpibus, venturum, copiis), go to wordlist and limit by this session. see screenshot (all kosher here)

![session-limit](https://user-images.githubusercontent.com/41396793/84275709-5f459700-aaff-11ea-9382-1332487e2722.JPG)

2) then limit by most recent. note that the 3 words are missing from the most recent list in wordlist. see screenshot

![most-recent-limit](https://user-images.githubusercontent.com/41396793/84275871-99169d80-aaff-11ea-81a5-745610a1ada6.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/430#issuecomment-642025990_

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Comment by monzug** [comment]
both issues have been fixed in latest build.
tested in Chrome
![wordlist-session](https://user-images.githubusercontent.com/41396793/84389199-b319b400-abc3-11ea-8a55-0a39cb9688cd.JPG)
