### ISSUE TITLE
currentSession, frequency and updatedDate not being updated when lookup is from wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#443]
Double click on a word on the wordlist, view popup, and note that currentSession, frequency and updatedDate have not channged.

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/430#issuecomment-642025990_

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Comment by monzug** [comment]
see dextris and Florus both been updated from wordlist, github #430 
![destris-florus](https://user-images.githubusercontent.com/41396793/84411825-6b535680-abdc-11ea-9867-686ff4037a0c.JPG)
