### ISSUE TITLE
wordlist: I can add a failed word to wordlist but it does not show up in limit to most recent

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#444]
in http://www.thelatinlibrary.com/petronius1.html, I double clicked on Thucydidis and got a lexical query produced no results. the word is added to the wordlist. see current session screenshot

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Comment by monzug** [comment]
can't reproduce in latest build.
![compensarium](https://user-images.githubusercontent.com/41396793/84401793-adc36600-abd1-11ea-8f32-bc25d54e4852.JPG)
