### ISSUE TITLE
wordlist sorting problems in Safari extension

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#445]
When you have a list with a mixture of words with and without updatedDate, the sort by most recent in Safari does not work as expected:

See also 
https://github.com/alpheios-project/alpheios-core/issues/382#issuecomment-642049027

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Comment by monzug** [comment]
sorting looks good in latest safari build Safari App Extension 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238
