### ISSUE TITLE
FF on PC: can't check downloading with filtering and for flashcard

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#448]
tested again on latest build  Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238 

Install latest build. login as existing user, double click on a few words from latin library. Check limit for current session in wordlist, then apply the limit to most recent. click on the download icon. The checkboxes for filtering and for flashcard cannot be checked. by reloading the page, I am able to check both checkboxes again

**Comment by balmas** [comment]
@kirlat can you take a look at this one? Thank you!

**Comment by kirlat** [comment]
Sure, will work on that

**Comment by kirlat** [comment]
I'm trying to reproduce it, but I can't do it so far. Maybe I'm doing anything wrong. My browser is FF 78 beta 5.

1. I opened a page from The Latin Library (https://www.thelatinlibrary.com/lucan/lucan2.shtml).
2. I activated a webextension on the page.
3. I logged in.
4. I looked up for several Latin words
5. I set a limit to "most recent" and then set a number of words to 5.
6. I pressed a "download" icon.
7. I was able to check the checkboxes in download options.

![image](https://user-images.githubusercontent.com/18631055/84391398-ff87e280-ac09-11ea-8a10-69310d1efeff.png)

@monzug, is my sequence to reproduce it correct?

**Comment by monzug** [comment]
yes. it does happen only after installing new build. I have seen it several
times in FF 76. I just installed FF 77 and it's not longer reproducible.
Thanks for checking.

**Comment by balmas** [comment]
so sounds like we should note FF 76 as an unsupported browser. 

@irina060981 can you make a note of this for the selenium-tests?

**Comment by monzug** [comment]
I have been using FF 76 till this aft and it does work except in this case
(and maybe few others that I cannot think of at the moment). maybe we can
just say that it's not fully supported?

**Comment by balmas** [comment]
actually I notice that 77 already looks to be  our minimum supported version per the selenium tests (alpheios-project/selenium-tests#21)

**Comment by irina060981** [comment]
I need to check, it is very strange if we lost support of all Firefox versions besides the last

**Comment by irina060981** [comment]
I have made a manual test on

Windows 10 Firefox 76

it is realy easy to do using Browserstack
Click Live (to select manual mode)
Select OS and Browser version

and I login in with test user
looked for several words
and then download with flashscard option

![image](https://user-images.githubusercontent.com/12377640/84496706-c7a79a80-acf0-11ea-9197-07b0019a5142.png)

May be there is a specific reason for such bug in Monica's environment?

I could know only the following reasons when checkbox couldn't be checked:
  - they are covered by other opacite element
  - checkbox has not unique identifire (this bug was some time before)

But I don't know any reason that it could depend on browser version

**Comment by monzug** [comment]
I don't know. it did happen occasionally and always unable to have a
reproducible scenario but I have seen it several times.

**Comment by monzug** [comment]
I was able to reproduce this issue again, FF 77 on Mac
1) cannot check the checkboxes
![Screen Shot 2020-06-21 at 1 58 33 PM](https://user-images.githubusercontent.com/41396793/85224072-e8927e80-b3c7-11ea-9473-4f6c6e2c299a.png)
2) user's options (Chinese as page language and mouse movement on)
![Screen Shot 2020-06-21 at 1 58 12 PM](https://user-images.githubusercontent.com/41396793/85224074-eaf4d880-b3c7-11ea-9b81-e60da998d8be.png)

**Comment by kirlat** [comment]
With mousemove on, I've seen some quirks with the mouse behavior within a panel, but those mostly were related to the rapid change of the cursor pointer shape in a couple of areas. Also, cursor movements were a little jerky sometimes. I was not able to find any issues with the cursor functionality so far, though. I was always able to check or uncheck the checkboxes successfully.
