### ISSUE TITLE
Lookup button not working in mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#464]
reported by @monzug 

If you paste or enter a word in the lookup box on mobile and then touch the Lookup button, nothing happens. using the keyboard "Go" or enter succeeds. It seems the handler on the button isn't using the right event.

**Comment by monzug** [comment]
it does work if I enter a word in lookup, only paste a word does not work on iPhone 11 and XR

**Comment by balmas** [comment]
it didn't for me though, at least it didn't if the word wasn't long enough to bring up the autocomplete. Once the autocomplete dropdown shows, it suddenly worked.

Maybe it's the autocomplete functionality that is causing the problem then...

**Comment by monzug** [comment]
it worked for me with oi (no autocomplete)

**Comment by balmas** [comment]
hmm. not for me on a Samsung Galaxy 7.

But the autocomplete might be a red-herring, turning the it off in options doesn't change anything.

However, interestingly, once I successfully submit the lookup with the 'Go' button on my keyboard, if I leave the lookup box open, I can then use the button to submit additional words. Once I close the box and reopen it though, the problem recurs.

**Comment by balmas** [comment]
this is similar to a problem I was seeing intermittently on the desktop too -- the initial click on the Lookup button failed, subsequent uses of it succeeded.

**Comment by kirlat** [comment]
Hmm, I've tested it on my phone on `texts-text.alpheios.net` in Chrome, and I was not able to find any single case when it fails so far. No matter whether I type the word in or select it from a list, it always starts a lookup. Will keep trying.

**Comment by balmas** [comment]
@kirlat it starts the lookup after a press on the Lookup button?

**Comment by balmas** [comment]
what if you copy/paste it in, instead of entering it?

**Comment by kirlat** [comment]
> @kirlat it starts the lookup after a press on the Lookup button?

Yes (the orange one with the "Lookup" word on it to be absolutely sure)

**Comment by kirlat** [comment]
> what if you copy/paste it in, instead of entering it?

If I copy and past it, it does not work for me. But if I type a new word after that, it does.

**Comment by balmas** [comment]
ok, then that is at least similar to what I am seeing.

**Comment by monzug** [comment]
yes, same here

**Comment by kirlat** [comment]
I've tested it and I think it is an autocomplete problem. It emits a `updateLookupText` event when text in a lookup changes. This triggers an update of a lookup text in a model. This event, however, is not triggered when text is copied into the lookup text field. As a result, text field is empty, and a lookup is not triggered.

Will think about how to fix it in a least invasive way possible.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build 20200618501
Alpheios Components 3.3.0-20200618494

@monzug please test with the release candidate build at

https://github.com/alpheios-project/webextension/releases/download/20200618501/dist.zip

**Comment by monzug** [comment]
it works now. Thanks!
