### ISSUE TITLE
popup-resize display in options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#466]
reported by @monzug 

there is some css bleeding for the display of the popup-resizing widget in the options tab

![Screen Shot 2020-06-18 at 7 04 47 PM](https://user-images.githubusercontent.com/644870/85053560-b2a38f00-b168-11ea-9f89-e1f874639d32.png)

(that's at scaife.perseus.org)

**Comment by balmas** [comment]
@kirlat could you look at how hard this would be to fix?

At the same time, could you also see if it would be easy to hide this from the options tab when the user is on a mobile device?

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build 20200618501
Alpheios Components 3.3.0-20200618494

@monzug please test with the release candidate build at

https://github.com/alpheios-project/webextension/releases/download/20200618501/dist.zip

**Comment by monzug** [comment]
fixed.
![Screen Shot 2020-06-19 at 2 46 44 PM](https://user-images.githubusercontent.com/41396793/85133885-d5eb3e80-b23b-11ea-9c47-16218af1f38e.png)
