### ISSUE TITLE
remove landscape-view notification for the diagram panel on mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#467]
@monzug is finding that the treebank display with the new arethusa/treebank template integration looks better in portrait than landscape on mobile, so we should remove that notification.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build 20200618501
Alpheios Components 3.3.0-20200618494

@monzug please test with the release candidate build at 

https://github.com/alpheios-project/webextension/releases/download/20200618501/dist.zip

**Comment by monzug** [comment]
message is not longer generated. tested on iphone XR
