### ISSUE TITLE
Remove Dual and Plural from Greek noun tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#478]
Dual and Plural should not be repeated in the Greek noun tables. we should keep only one dual for nominative, accusative, vocative and one plural for nominative, vocative.
![Screen Shot 2020-06-19 at 3 32 48 PM](https://user-images.githubusercontent.com/41396793/85582443-ba1dd900-b63d-11ea-9172-f44b822eff33.png)

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
this has been fixed in  Alpheios Reading Tools 3.3.1 build null.20200803479
Alpheios Components 3.3.0-qa.20200803296
