### ISSUE TITLE
ability to use Treebank data for disamibugation only

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#484]
requested by @nevenjovanovic

a project I did with students included using Perseids only to disambiguate
parses and lemmatizations, without creating treebanks. Is there a
possibility to say to Alpheios that I have disambiguations (in the ALDT
format), but no treebanks? That is, to show just the disambiguation
symbol, but not the diagram symbol?

This could be pedagogically useful because at the early learning stage it
helps to have a disambiguated (grammatically commented) text...

**Comment by balmas** [comment]
this should be doable. it might require a new API call to Arethusa to query whether or not any relations have been defined for a sentence.

**Comment by balmas** [comment]
this can be tested in

Alpheios Embedded Library 3.3.0-qa.20200807266
Alpheios Components 3.3.0-qa.20200807247 

At https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/test.html

In the user-report tests, with sentence Τοὺς οὖν πρώτους τῶν ἀνθρώπων μηδενὸς τῶν πρὸς βίον χρησίμων εὑρημένου ἐπιπόνως διάγειν , γυμνοὺς μὲν ἐσθῆτος ὄντας , οἰκήσεως δὲ καὶ πυρὸς ἀήθεις , τροφῆς δ’ ἡμέρου παντελῶς ἀνεννοήτους .

Any word in this sentence should produce a disambiguation icon in the popup. The tree icon will be next to the disambiguation error still, but the tooltip has been clarified to say "Disambiguated with treebank data" and there is no longer a toolbar button to produce the tree in popup header nor in the toolbar.

**Comment by monzug** [comment]
I see the tooltip with disambiguation with trrebank data. the toolbar button is gone but I do not have any other way to open the diagram. how am I supposed to open the diagram?
tested in chrome and FF on PC, build   Alpheios Embedded Library 3.3.0-qa.20200807266
Alpheios Components 3.3.0-qa.20200807377

**Comment by balmas** [comment]
>how am I supposed to open the diagram if tree display is disabled using data-alpheios_tb_morph_only=true?

That's the point -- the diagrams are disabled because in fact in this data set no relationships between words have been annotated only the morphology. So the diagram would be empty if you opened it.

**Comment by monzug** [comment]
ok. I was rewriting the sentence to check if this was the point. Thanks
