### ISSUE TITLE
add table for inquit (inquiam)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#49]
just found out that we don't have a table for inquit

**Comment by monzug** [comment]
added inquam to imperative and verb irregular

**Comment by balmas** [comment]
The main irregular table should be there for matching in qa.20200723472, still needs to be added to the inflection browser
(and infinitive/imperative are not yet available)

**Comment by balmas** [comment]
Now it's in the browser.

Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
tested in build  Alpheios Reading Tools 3.3.1 build null.20200803479
Alpheios Components 3.3.0-qa.20200803296 

the table has been added to the Latin Inflection table but if I lookup for inquit the table is missing. see screenshot

![inquit](https://user-images.githubusercontent.com/41396793/89295538-2b827b80-d62f-11ea-820d-1de47dd7e79a.JPG)

**Comment by balmas** [comment]
@monzug this is because Whitakers says the lemma is "inquiam" not "inquam". I will change the data accordingly, although it's a little weird since looking up inquiam produces no results.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200804636
Alpheios Components 3.3.0-qa.20200804505

**Comment by monzug** [comment]
right, inquiam produces no result...
there is one more thing: inquam does not have participle, infinitive or imperative. why do we show the mood with no content for the imperative and infinitive, and the table has not been implemented yet for the participle?

![inquit-no table](https://user-images.githubusercontent.com/41396793/89415665-2c341400-d6fa-11ea-917c-14f4ea7fc57a.JPG)

**Comment by monzug** [comment]
the imperative inque and inquito shows an empty inflection table with only mood.

**Comment by balmas** [comment]
@monzug we don't have any imperative of infinitive forms in the data for inquiam. Are there valid forms of it? If so, can you add them to the verb/irregular/forms.csv (NOTE -- I ended up using the forms.csv as the source for the infinitive and imperative, rather than the separate files, because they were already in there and it works fine that way)

**Comment by monzug** [comment]
infinitive is empty for inquam (that's why is inquiam -_-_-), imperative is missing from forms.csv. I will add them. where can I find a copy of the only infinitive and imperative irregular files?

**Comment by balmas** [comment]
> I will add them. where can I find a copy of the only infinitive and imperative irregular files? I need to copy the lines form there

We don't have them anymore, just add the imperative to the irregular forms.csv

**Comment by monzug** [comment]
I found them in github. will add the imperative

**Comment by monzug** [comment]
inquam forms were in the July 1st imperative table, see lines

veneo,venire_venivi(ii)_venitus,vēneuntō,active,imperative,future,plural,3rd,
inquam,-_-_-,inque,,imperative,present,singular,2nd,16
inquam,-_-_-,inquitō,,imperative,present,plural,2nd,16
odeo,odire_odivi(ii)_-,odī,active,imperative,present,singular,2nd,
odeo,odire_odivi(ii)_-,odīte,active,imperative,present,plural,2nd,
odeo,odire_odivi(ii)_-,odītō,active,imperative,future,singular,2nd,
odeo,odire_odivi(ii)_-,odītō,active,imperative,future,singular,3rd,
odeo,odire_odivi(ii)_-,odītōte,active,imperative,future,plural,2nd,
odeo,odire_odivi(ii)_-,odeuntō,active,imperative,future,plural,3rd,

**Comment by balmas** [comment]
ah, sorry I missed that when I went back to using the forms.csv . I looked for it just now but didn't find that. 

I can go ahead and add them to the main forms.csv if you want.

**Comment by monzug** [comment]
I can easily do that. will check if we are missing other forms.

**Comment by monzug** [comment]
added to forms.csv.

**Comment by balmas** [comment]
thanks!

**Comment by monzug** [comment]
No problem. Need to check all the entries for the imperative

**Comment by balmas** [comment]
should be fixed in 
webextension qa.20200807379 
components qa.20200807247

**Comment by monzug** [comment]
@balmas, are we ok with the two different approaches to empty tables? see inquiam (or inquam). the participle and infinitive are missing but the output is different (the infinitive comes from the forms.csv, participle from the participle forms.csv

![empty-vs-not-implemented](https://user-images.githubusercontent.com/41396793/89649592-08ee9d80-d88f-11ea-911a-3d38191e91f5.JPG)

**Comment by balmas** [comment]
hmm. I should probably look at why there is the difference in behavior.

**Comment by balmas** [comment]
the difference is because of the part of speech -- the participle table is built off of a different part of speech (verb_participle), for which no matching data is found.  But the infinitive and imperative are built off of the verb part of speech, which does have matching data, just not in this table. I'll enter an issue to track this, although it's not super high priority in my opinion so it may not get fixed anytime soon.
