### ISSUE TITLE
some verb participles are missing. Need to investigate

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#50]
verbs like itus  or  venitus   which are sing. perf. pass. nom (verb participle) don't have a match in the related inflection tables. need to investigate if it's whitaker giving a wrong id or if their entries is missing.

**Comment by monzug** [comment]
venitus is definitely missing from https://github.com/alpheios-project/alpheios-core/blob/monzug-patch-1/packages/inflection-tables/lib/lang/latin/data/participle/forms.csv

**Comment by monzug** [comment]
Some grammar do not have the passive forms for the verb eo as it's intransitive, but in some grammars  we have itus as perfect participle. I added it  to the table but I wouldn't mind include a footnote. same for venitus - what do you think @balmas?

**Comment by balmas** [comment]
a footnote sounds like a good idea

**Comment by monzug** [comment]
will add a footnote. Thanks!!!!

**Comment by monzug** [comment]
footnotes added

**Comment by balmas** [comment]
this should be testable in qa.20200723472

**Comment by monzug** [comment]
I do not see the footnotes 17 that I have added in https://github.com/alpheios-project/alpheios-core/blob/monzug-patch-1/packages/inflection-tables/lib/lang/latin/data/participle/form_footnotes.csv

did I miss any step here?

see attachment
![itus](https://user-images.githubusercontent.com/41396793/89189278-c1ee6880-d56d-11ea-8af7-720e57e8b55e.JPG)

**Comment by balmas** [comment]
It turned out that the footnotes hadn't been merged with this build. They'll be there with the next.

**Comment by monzug** [comment]
cool. Thanks

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200803307
Alpheios Components 3.3.0-qa.20200803296

**Comment by monzug** [comment]
footnotes 17 is there!!!
