### ISSUE TITLE
improve order of tables in verb drop-down

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#504]
not sure if this is the right time to suggest a little improvement in the verbs drop-down. see esse: it's verb participle and irregular infinitive. first we have verb participle  and verb, if I select verb, I have infinitive, then verb-irregular, then verb-irregular-infinitive and then all the others. would it be possible at least to have in the verb drop-down, infinitive irregular first, then verb irregular, then infinitive and then all the others? or highlight the verbs with a match in it

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/26#issuecomment-669195983_

**Comment by balmas** [comment]
I'll investigate how much work this would be.

**Comment by balmas** [comment]
order in the dropdown should be fixed in 
webextension qa.20200807379 
components qa.20200807247

**Comment by monzug** [comment]
verb irregular  (infinitive or imperative or supine or participle) shows up at top of drop-down
