### ISSUE TITLE
resize treebank frame with resize of panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#507]
user report from @rgorman

Is it possible to resize the treebank iframe when the panel resizes?

**Comment by balmas** [comment]
@kirlat can I ask you to interrupt what you're doing to take a quick look at this one? I think it would probably be quick for you to fix.

![Screenshot from 2020-08-07 07-54-04](https://user-images.githubusercontent.com/644870/89643161-2f0e4080-d883-11ea-9ae0-83c82db62c72.png)

**Comment by kirlat** [comment]
Sure, I will check it

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200807525
Alpheios Components 3.3.0-qa.20200807377

**Comment by balmas** [comment]
@monzug please test with a variety of trees and window/panel sizes using the texts-test.alpheios.net treebanked texts. Thanks!  Please also be sure to test on mobile.

**Comment by monzug** [comment]
on mobile the  diagram fits the screen and the panel, so there is not resize of diagram/panel.

**Comment by monzug** [comment]
in Chrome,  when enlarging the panel, sometimes I loose the pop-up (the mouse goes outside the panel area and I loose the focus on the pop-up so it closes). when I reopen the pop-up and the related diagram, the size is much smaller than regular diagram size, see screenshot
![diagram-resizing-panel](https://user-images.githubusercontent.com/41396793/89794081-90891600-daf4-11ea-8580-d3a12391a8d2.JPG)

**Comment by monzug** [comment]
this hasn't been implemented in Safari yet. see screenshot
![Screen Shot 2020-08-10 at 5 02 59 PM](https://user-images.githubusercontent.com/41396793/89797634-6ef75100-db2b-11ea-91c5-c052f225f40e.png)

**Comment by balmas** [comment]
@kirlat can you investigate the 2 issues Monica found? Thanks!

**Comment by kirlat** [comment]
> when I reopen the pop-up and the related diagram, the size is much smaller than regular diagram size.

@balmas I vaguely remember that we probably had a width of a diagram fixed in order for the Treebank to scale it correctly, but I'm not 100% sure about that. Can you please confirm that there is no requirement for the width of the diagram iframe to be set to a fixed value (if you have that info)?

**Comment by balmas** [comment]
I think we used have have problems when the width (or the height) was below a certain value. Our comment before said

```
    A minimal height of the treebank's iframe, shall be no less than 43em,	
    but no more than that because max width of panel's content is 800px and	
    treebank frame will not if in if too wide
```

So we might have run into problems with scaling before but I cannot remember the exact details and am not immediately finding anything in the Arethusa code. 

But that said, yes you're right the problem with the scaling is actually in Arethusa and not Alpheios. So I will need to look at that.  The Safari issue is in Alpheios though.

**Comment by balmas** [comment]
I've made a new issue for the resizing problem (although this could be a combination of Alpheios and Arethusa actually -- i.e. it might be that we need to send another refreshView request after the panel is resized, but I'll look into it)

**Comment by kirlat** [comment]
The problem with the incorrect width of a treebank panel in Safari seems to be the conflict with the old version of the Safari App Extension. Whenever an extension is installed and active, it injects its own CSS stylesheets. Those styles has a higher priority than the styles loaded by the webpage.

In the Safari test, texts-test.alpheios.net was defining the width of the panel as 100% in its own styles (which is correct), but the extension was loading an older stylesheet, where the width is defined as 690px (incorrect). However, because of the higher priority of the extension's styles, 690px value prevailed.

@monzug, can you please verify that this is the case? Please go to Safari's Preferences, select an Extensions tab, and uncheck the box next to the Alpheios reading tools to disable the extension. Then reload the page. This should fix the issue.

**Comment by monzug** [comment]
Yes.  @kirlat, for future references, should I always disable the extension
when testing new features in text env? Thanks

**Comment by kirlat** [comment]
> @kirlat, for future references, should I always disable the extensionwhen testing new features in text env?

I think it would make sense to always have the extension disabled while testing in the text environment. In my understanding they're not supposed to be used together. @balmas, what do you think?

**Comment by balmas** [comment]
well, I think we would like people to be able to have the extension installed and use the texts environment.  The extension should be automatically deactivated on a page with the embedded library and it would be better if it didn't load the stylesheets in the page when it's not activated.  But maybe this will be resolved automatically if we switch to the web extension api compatible architecture in Safari. I'm going to make this a new issue and we can look into it when we work on that.

**Comment by balmas** [comment]
@monzug so I think we can verify this one as it is?

**Comment by monzug** [comment]
yes. done.
