### ISSUE TITLE
typo in drop-down for superlative

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#512]
there is a typo in the superlative drop-down: it says suplerative but it should be superlative. related to issue #28 

![superlative](https://user-images.githubusercontent.com/41396793/89900857-48c8c400-dbb2-11ea-9478-ced21060a4f6.JPG)

**Comment by balmas** [comment]
oops sorry will fix.

**Comment by balmas** [comment]
Components qa.20200812380

**Comment by monzug** [comment]
typo has been fixed in  Alpheios Reading Tools 3.3.1 build qa.20200812526
Alpheios Components 3.3.0-qa.20200812380
