### ISSUE TITLE
Missing ending in the superlative table for some irregular adjectives

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#514]
Irregular adjectives, such as optimus, pessimus, dextimus, citimus, extremus, supremus, do not have a match in the superlative adjective table.
Should I add the ending mus, ma, mum to the table? in Whitaker, we have the mus, ma, mum endings but in Bennett the ending is imus. Need to check more grammars.
related to issue #28

**Comment by balmas** [comment]
I'll leave this one up to you @monzug

**Comment by monzug** [comment]
miss the Spilimbergo library!!!!!

**Comment by monzug** [comment]
after checking few grammars and considering that  "The comparative and superlative are really new stems, and are not strictly to be regarded as forms of inflection." I decided that by adding the  "mus" ending with a footnote, Bennett would not mind...

**Comment by monzug** [comment]
add footnotes 4 and endings in the superlative

**Comment by balmas** [comment]
Components qa.20200812380

**Comment by monzug** [comment]
footnotes 4 and endings in ma, mus, mum are in the superlative table
