### ISSUE TITLE
Latin adjectives with no declension

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#521]
In Whitaker, some SUPER adjectives such as postumus do not have the declension because they came from prepositions. Also we should remove the 9th declension from the list of adjectives from issue #513, so we will have few comparative and superlative with no declension. Will they still have a match in the comparative and superlative tables? I see that the declension field is populated by 1st 2nd and 3rd now (issue #28). will it work also for these adjectives?

**Comment by balmas** [comment]
I would have to make further changes to allow an empty declension value to work. I took the shortcut of using 1st 2nd 3rd to keep the code changes low.  But if there are many of these then perhaps it's worth it.

**Comment by monzug** [comment]
they are not that many. I believe most of the irregular comparative
adjectives

**Comment by balmas** [comment]
well, it's probably doable anyway. I'll take a look.

**Comment by monzug** [comment]
Thanks

**Comment by balmas** [comment]
Components qa.20200812380

**Comment by monzug** [comment]
postumus, pessimus, potissimus, intimus, proximus, imus, summus, etc. have a match in the superlative table now.
