### ISSUE TITLE
matching in the comparative and superlative table for regular adjective

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#525]
related to issue #28 
Lookup for bona which is a regular type of adjective of the 1st declension, there are some matches in the comparative table too.
see screenshot
![bona-comparative](https://user-images.githubusercontent.com/41396793/90137760-1058ef80-dd44-11ea-8e1f-b042bec8e736.JPG)

would it be possible to do the following:
1) when regular adjective, only the adjective table is generated  (and hide the comparative and superlative tables) 
2) when comparative adjective, drop-down is populated by first, the comparative table then the adjective table
3) when superlative adjective, drop-down is populated by the superlative table first, then the adjective table

in 2) and 3), I am ok also to display all tables (if it is easier) with the superlative first (if super adj) or the comparative table first (if comp adj)

**Comment by balmas** [comment]
oh, I misunderstood about the way you wanted the tables to be linked to the main adjective table.  

do you just want the adjective table to appear with the comparative and superlative, but not together with them?

**Comment by monzug** [comment]
I am ok either way but I do not like to show the matching when there
shouldn't be, e.g. bella

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.1 build qa.20200813582
Alpheios Components 3.3.0-qa.20200813570

**Comment by monzug** [comment]
Super! thanks
tested in Chrome and FF on PC
build  Alpheios Reading Tools 3.3.1 build qa.20200813582
Alpheios Components 3.3.0-qa.20200813570
