### ISSUE TITLE
limit by this session shows all words saved in wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#530]
Safari App Extension 3.3.1 build qa.20200819448
Alpheios Components 3.3.0-qa.20200813570
I have a slow connection. I signed in with Apple id (with saved id/psw) after only one lookup for esse. I opened the wordlist and limit by this session to check if esse was listed. Instead I got all words in the wordlist listed by this session (esse is missing). somehow it didn't properly load the last session information (see screenshots 2). I logged out and in again and everything was ok, except for the dates. all words in wordlist have today's date except for one Syriac word (22), dated to June 6. I did sign in Chrome with apple id and dates are today's date for all words in wordlist except for 22. see screenshot 1

1) only syriac word with other date than today's date

![Screen Shot 2020-08-19 at 6 58 53 PM](https://user-images.githubusercontent.com/41396793/90667676-453ada00-e24f-11ea-9621-e84009df552e.png)

2) limit to this session (expected only esse)

![Screen Shot 2020-08-19 at 6 34 44 PM](https://user-images.githubusercontent.com/41396793/90667776-4b30bb00-e24f-11ea-961a-9758f5853d40.png)
![Screen Shot 2020-08-19 at 6 33 58 PM](https://user-images.githubusercontent.com/41396793/90667791-54ba2300-e24f-11ea-9a72-1934755dd4bb.png)

**Comment by balmas** [comment]
@monzug i don't see anything jumping out at me in the release code that could be effecting a change in this behavior.

Just wondering though, did you by any chance download a wordlist from the same user id before this test? That *shouldn't* update the updatedDT but it's the only thing that's jumping out at me as a possibility for where this could be going wrong.

I will try to reproduce this tomorrow myself, and also run the selenium tests against the release build, but could you also see if you are able to reproduce this scenario? And if you are able to reproduce it in Safari, whether you can reproduce it in Chrome?

Thanks.

**Comment by monzug** [comment]
nope I did not download any wordlist. I was just trying to sign in with apple id.

**Comment by monzug** [comment]
could not reproduce the above scenario (sign in as apple user and also tested with different id/psw). limit to this session and log out worked fine. I'll close this one and assign to me as test case

**Comment by monzug** [comment]
to use as test case with https://github.com/alpheios-project/alpheios-core/issues/138

**Comment by monzug** [comment]
@balmas for future releases
