### ISSUE TITLE
Greek: tense not shown for participles

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#537]
reported by @rgorman

>I notice that the tense of participles is at least sometimes not given. This seems more likely to be a bug than a feature.  I give examples below. The first is a present participle, the second a perfect participle, but I don’t see that indicated

![image001](https://user-images.githubusercontent.com/644870/93762809-3f357180-fbde-11ea-9117-db2e5f0d0d3c.png)
![image002](https://user-images.githubusercontent.com/644870/93762810-3f357180-fbde-11ea-8c3d-a68f6634575e.png)

Morpheus does give us the tense for these forms so I'm not sure why we aren't showing it.

**Comment by monzug** [comment]
looks like https://github.com/alpheios-project/alpheios-core/issues/55#issuecomment-575289415

**Comment by balmas** [comment]
ah yes you are right.  lets close this as a dupe then. And revisit 55 to see what can be done. tx
