### ISSUE TITLE
matching problems with verb εἰμί to be:

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#54]
an other one is related the verb   εἰμί    to be:
1) εἶναι 
2) ἔσεσθαι
the 1) does the match with the εἰμί  inflection table    <stemtype>irreg_mi</stemtype>
2) does the match with   Future System (Active and Middle) with contraction in -έω                                             <stemtype>reg_fut</stemtype> .  (an other example is ἔσεσθον)

this is a situation in which we have the exact verb inflection tables (the verb  εἰμί  table). would it be possible to do the match like we do for the Latin irregular verbs?

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/846#issuecomment-549869035_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
we do display the correct paradigm table now but we are not doing the match with the εἰμί inflection table irreg_mi.
e.g.  ἔσομαι
 verb, singular, future, middle, indicative, 1st, reg_fut
does not have the cell highlighted in the irreg_mi   -  is it because of middle???? any idea?

**Comment by balmas** [comment]
yes, it's because of the voice. The data on the table has this property set to "active". We could remove it if it doesn't apply - i.e. if the all the forms are the same regardless of voice. What do you think @monzug ?

**Comment by monzug** [comment]
I think we have both form, active and middle. need to check

**Comment by monzug** [comment]
the future is middle (accordingly to Morpheus) all the other are active
see also issue #76

**Comment by balmas** [comment]
ok, so I should change the voice on the future column to middle. Will do that.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
all good except for  ἔσεσθαι   that we do not have the cell highlighted for the future infinitive. it does share the cell withthe present infinitive:  εἶναι, fut.ἔσεσθαι  
is this an other situation in which the cell have the active voice only?

**Comment by balmas** [comment]
yes, I'll remove the voice from that cell.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200501441

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200504341

**Comment by monzug** [comment]
it's till not highlighted
lookup for  ἔσεσθαι   the table does not have any cell highlighted. it does when I lookup εἶναι  (present infinitive active)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
cell is highlighted now. Thanks
