### ISSUE TITLE
enable further lookups when no definition found

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#541]
Requested by @rgorman

Because of the date and subject matter of the text (and Marcus' own annoying predilection for obscure technical terms), many words are returned by Alph. as "no definitions found." In the nature of things, many of these are compounds.  E.G., πρό-ἀπολέγω. It would be great if we could click on either part of the lemma and be taken to the dictionary entry, since it is easy to guess the meaning of a compound from its parts, usually.

Similarly, Alph. sometimes says that the definition for some late term is the same as an earlier term (new = old, is the usual form). It would be great if we could call up the dictionary entry to the old form from this window.

**Comment by balmas** [comment]
Another test case for this: ἐπεκυλίνδουν

**Comment by balmas** [comment]
the fix to enable lookups on compound lemmas can be tested in Alpheios Components 3.3.1-qa.20210108437

lookups on greek words in definitions requires updated defs files, shoube tested via those issues.

**Comment by monzug** [comment]
ἐπεκυλίνδουν   - 
1)  in the pop-up, can we highlight only the compound part that has been selected ( ἐπε    or   κυλίνδουν )  not the all word?

2) Would it be possible in this case to keep the original pop-up open so I can select also the other compound word (like nesting)? right now, when I click on ἐπε  , a new pop-up is generated and the original one is gone. if I want to lookup for the second word κυλίνδουν,  I have to enter the ἐπεκυλίνδουν word again.

**Comment by balmas** [comment]
>Would it be possible in this case to keep the original pop-up open so I can select also the other compound word (like nesting)? right now, when I click on ἐπε , a new pop-up is generated and the original one is gone. if I want to lookup for the second word κυλίνδουν, I have to enter the ἐπεκυλίνδουν word again.

For this we really need session history, which will be part of the next major release

**Comment by balmas** [comment]
>in the pop-up, can we highlight only the compound part that has been selected ( ἐπε or κυλίνδουν ) not the all word?

I think that change is too big for the incremental too unfortunately. The selection code is tricky. I'm going to enter a new issue for it to be considered for the future.

**Comment by monzug** [comment]
will close this one as all questions have been addressed in new issues. Thanks
