### ISSUE TITLE
missing the tense and voice in Greek participle verbs (and Latin verbs too)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#55]
lookup  κατασκευάσας     - see screenshot below

![verb-participle](https://user-images.githubusercontent.com/41396793/68480294-75564680-0202-11ea-98b5-d205a54ac0f5.JPG)

@balmas: I think because it has a case, which is overriding the voice and tense information.

Comparing with the latin verbs (e.g. reputantis), I realized that tense and voice are also missing from the latin morphology pop-up but we do show the conjugation which we don't have in Greek verbs and in Morpheus. to add more info, should we consider the stemtype?

**Comment by balmas** [comment]
requested also by @rgorman in #537

**Comment by balmas** [comment]
this can be tested in Alpheios Components 3.3.1-qa.20210108437

**Comment by monzug** [comment]
so happy to see this one fixed. tested in FF and Chrome (mac and pc). see screenshots
![Screen Shot 2021-01-08 at 4 42 06 PM](https://user-images.githubusercontent.com/41396793/104034150-cf6ce600-51d0-11eb-8ba9-b604ca958a73.png)
