### ISSUE TITLE
ἐπι-κῠλινδέω no definition

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/alpheios-core#572]
ἐπεκυλίνδουν is analyzed (correctly) as ἐπι-κῠλινδέω, but then it says NO DEFINITIONS FOUND. Is the hyphen messing it up?

**Comment by balmas** [comment]
there are 2 separate problems here:

1) yes, the - in the lemma is creating a problem for the lookup. We should include stripping these in our alternate word encodings lookup

2) morpheus reports ἐπί-κυλινδέω as the lemma, with the ί being iota with tonos/oxia. The entry in lsj does not have the tonos/oxia on the iota.   I think this has come up before, so I think we might want to normalize that for a retry of a failed lookup too

**Comment by balmas** [comment]
#135 tracks changes for the first issue (dealing with compound words properly).

In the meantime, #541 has changes for enabling users to do the lookup on the compound word parts in the popup as a temporary solution until we can do this better. 

I think I was wrong about the 2nd problem.

Closing this as a dupe therefore, as it will be addressed with the other issues.
