### ISSUE TITLE
interpret morph attribute irreg_comp as comparative

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#573]
> it looks like the issue is that we just take the first sense from the lexicon, "single" for the short definition and it would probably be better to extend this to e.g. "single, simple straightforward".

It's not about the sense, it's about the degree of comparison of the adjective, which should be presented in the form definition.
Like you do in similar cases:
![image](https://user-images.githubusercontent.com/7735754/101799425-32f5ec00-3b1d-11eb-945c-3aa37017a3cc.png)

_Originally posted by @demophobos in https://github.com/alpheios-project/webextension/issues/316#issuecomment-742627445_

**Comment by balmas** [comment]
morpheus normally reports the comparative in the `comp` field, as in:

```
<entry uri="">
          <dict>
            <hdwd xml:lang="grc">ἥμερος</hdwd>
            <pofs order="2">adjective</pofs>
            <decl>1st &amp; 2nd</decl>
          </dict>
          <infl>
            <term xml:lang="grc">
              <stem>ἡμερ</stem>
              <suff>ώτερον</suff>
            </term>
            <pofs order="2">adjective</pofs>
            <decl>1st &amp; 2nd</decl>
            <gend>adverbial</gend>
            <comp>comparative</comp>
            <stemtype>os_h_on</stemtype>
          </infl>
....
```

But for ἁπλούστερον (and probably others) the `comp` field is missing and instead we have `irreg_comp` in the `morph` field.  

```
  <entry uri="">
          <dict>
            <hdwd xml:lang="grc">ἁπλόος</hdwd>
            <pofs order="2">adjective</pofs>
            <decl>1st &amp; 2nd</decl>
          </dict>
          <infl>
            <term xml:lang="grc">
              <stem>ἁπλουστερ</stem>
              <suff>ον</suff>
            </term>
            <pofs order="2">adjective</pofs>
            <decl>1st &amp; 2nd</decl>
            <case order="4">accusative</case>
            <gend>masculine</gend>
            <num>singular</num>
            <stemtype>os_h_on</stemtype>
            <morph>irreg_comp</morph>
          </infl>
...
```

We could normalize this in the client adapter code.

**Comment by balmas** [comment]
we should also catch and map the irreg_superl morph attribute value to comp=superlative

e.g. as in  ἥδιστα and ἄριστα

**Comment by balmas** [comment]
can be tested in Alpheios Components 3.3.1-qa.20210106574

**Comment by monzug** [comment]
tested in FF/Mac in  Alpheios Reading Tools 3.3.1 build qa.20210106631
Alpheios Components 3.3.1-qa.20210106574 
I am getting the comparative and super attribute now. Would it be possible to add the attribute only once e.g. next to plural? see attachment

![Screen Shot 2021-01-07 at 3 15 26 PM](https://user-images.githubusercontent.com/41396793/103903808-a9761180-50fc-11eb-9584-e6d958e189e3.png)

**Comment by balmas** [comment]
I think the grouping is a similar issue to #101 and #336. I don't think I can fix that now but the grouping needs to be redone in the next major release.

**Comment by balmas** [comment]
>ἄριστα does not have the super attribute in the morphology pop-up. I did also checked on morpheus and there is nothing that says it's a superlative.

Yeah that's a morpheus bug. Will record it there.

**Comment by monzug** [comment]
yep, remember the grouping issues. I thought that maybe the superlative and
comparative could be handled differently. Oh well, soon

**Comment by monzug** [comment]
tested also with  Greek comparative : θειότερον    σεμνότερόν   γλύκιόν
