### ISSUE TITLE
fix betacode helper for )a

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#574]
from @monzug : I have just realized that we have )a => ἀ    and again  )a => ἁ      ->     the last one should be (a

**Comment by balmas** [comment]
can be tested in Alpheios Components 3.3.1-qa.20210106574

**Comment by monzug** [comment]
this is fix in Alpheios Reading Tools 3.3.1 build qa.20210106631
Alpheios Components 3.3.1-qa.20210106574
