### ISSUE TITLE
tokenization adapter misses the 'ignore' option for the tei endpoint

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#587]
reported by @monzug 

The 'ignore' option if supplied in the parameters to the tokenize adapter fetchOptions does not get passed on to the service.

I think it would be better if the adapter did not hard code the option names, but instead retrieved them from the service schema.

**Comment by monzug** [comment]
similar behavior with Supply a comma-separated list of elements in the text that represent visual blocks
I added "l,p" to the list and compare with an empty list, (removed all the elements), the line breaks in the alignment looked the same. I did also try with 'div". the origin and target text had l,p and div tags.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Supply a comma-separated list of elements in the text that represent visual blocks works now. tested with l, p and div.
