### ISSUE TITLE
tokenizer adapter - catch and report errors

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#590]
with the fix to alpheios-project/tokenizer#26, the tokenizer service will report client errors (400) in a JSON error object that has the status code and message.  

the tokenizer adapter should catch these and return them to its clients so that they can be displayed to the user. These are likely to be errors with the content the user has supplied totokenize.

500 errors should be caught and reported to its clients as unexpected system errors.

**Comment by irina060981** [comment]
Merged and closed

**Comment by irina060981** [comment]
it is the same as https://github.com/alpheios-project/alignment-editor-new/issues/101
it doesn't need aditional verification - would be verified with https://github.com/alpheios-project/alignment-editor-new/issues/101

**Comment by irina060981** [comment]
Verified with https://github.com/alpheios-project/alignment-editor-new/issues/101
