### ISSUE TITLE
lemma alignment problems with disamibugation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#599]
Reported by @rgorman

> I noticed that when I use Alpheios linked to trees, the system gets confused when the lemma is disambiguated by a number, for example, dico2.  It will say that it can't find a definition.
But dico2 is the way the word is offered to the annotator by Arethusa.
Perhaps there is a way to make the two systems more friendly to each other?"

This needs to be done better but it's tricky, because sometimes we DO want to use the number to disambiguate the lemma. But it depends upon the source.  For Greek, we use the same parser (Morpheus) in Alpheios as in the Perseids/Arethusa environment, so we should normally be able to match the enumerated lemma with one of our results.  But in Latin, because Alpheios uses Whitaker while Perseids/Arethusa uses Morpheus, the lemmas are not quite aligned.

Here, retaining the dico2 from the treebank should mean that we actually get the right FULL definition (since we can match dico2 to the dico2 entry in Lewis and Short). So what we probably want is the best of both worlds -- to keep the short definition from Whitaker for dico and and link to the dico2 entry for the full definition.

**Comment by balmas** [comment]
additional use cases from @rgorman

> In the first, the "disambiguated" tag is added to two forms. I hope students don't try to make sense out of "poplar tree," but someone inevitably will.

![image](https://user-images.githubusercontent.com/644870/103412777-cd59b600-4b44-11eb-950d-d34884f2fec3.png)

>  In the second, the numeral on the lemma has led to a "no definition found," and I don't know how I can disambiguate between the two definitions that are offered.

![image](https://user-images.githubusercontent.com/644870/103412826-06922600-4b45-11eb-9a46-7e47a494a887.png)


> In the next example, we see the same phenomenon, and I would really like to be able to tell students that carmen is not a card for wool.

![image](https://user-images.githubusercontent.com/644870/103412856-2f1a2000-4b45-11eb-8eda-5ea76f722c16.png)

> Finally, I would prefer to point my students at the adjective definition for doctus, but the choice is not offered in Arethusa.

![image](https://user-images.githubusercontent.com/644870/103412860-36412e00-4b45-11eb-96a6-6104ce1220b8.png)

For populus, this identifies a gap in our disambiguation logic -- here we could use the masculine gender to disambiguaate between the two lemmas but we instead are creating a masculine inflection the second populus. I think we can add the logic for this. We would still have a problem if there are instances of nouns with the same lemma and gender, but  hopefully that is rare. 

For lego, I think, if we ignore the number after the lemma, it's a similar solution.  Is the correct definition in this case the first (the 3rd conjugation verb "read, gather, collect" )? If so, I should should be able to use the inflection to distinguish which of the two legos to match (as only the first has the inflection identified in the treebank).

For carmen, it's more difficult. One possibility for this (and other such situations) would be for you to annotate the "gloss" attribute in the treebank with your preferred. #133 will enable us to to display those extra attributes when they are present, and if the gloss is present we could indicate that as the preferred "definition".


For doctus, in Arethusa, you can create a new form for doctus that is the adjective and when you save that to the tree it should match with the adjective in Alpheios.

**Comment by balmas** [comment]
The dico2, lego2, and populo scenarios are fixed and can be tested in Alpheios Components 3.3.1-qa.20210106574

carmine is partially fixed, but to be able to refine the definition further requires #133 which isn't fixed yet.

**Comment by monzug** [comment]
Populo can also be a verb, while in the treebank test environment we used populos that cannot be a verb.
![Screen Shot 2021-01-13 at 4 01 55 PM](https://user-images.githubusercontent.com/41396793/104469427-cc02a180-55b8-11eb-989c-afcb04b436d8.png)

all good with legat dicta and populos
