### ISSUE TITLE
Latin verb with mood=gerundive matches whitaker mood=participle

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#608]
another interesting point here, which @rgorman helped clarify -- the treebank reports this as mood=gerundive. The Whitake parser used by Alpheios reports all Gerunds as verb participles (see alpheios-project/morphsvc#11).  

I think perhaps we should make a change to the Alpheios treebank adapter to consider a Latin verb with mood=gerundive as being the same as a verb participle. That way we will at least be comparing apples to apples. We'd still have a disconnect here, because the tense in the treebank is present. But we would at least be matching the part of speech.

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios-core/issues/540#issuecomment-758232342_

**Comment by balmas** [comment]
this is fixed in Alpheios Components 3.3.3-qa.20210113579

the code change was to consider a gerundive the same as a verb participle -- @monzug note that for now this change applies only to the treebank disambiguation and not the inflection matching.

There is also a corresponding change to the treebank data alpheios-project/alpheios-trees#15  to remove the incorrect tense

**Comment by monzug** [comment]
fugiendo (https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1) is only verb participle fut. pass. - the present form is gone

![Screen Shot 2021-01-14 at 1 08 59 PM](https://user-images.githubusercontent.com/41396793/104589446-2ad42380-566a-11eb-9b79-2de7adc4ac4e.png)

**Comment by balmas** [comment]
I went a little too far with this change, per #615 

It's not actually that Whitaker reports the whole lexeme as being a verb participle when an inflection has the gerundive mood, but rather that the inflection itself has a part of speech which is verb participle but the lexeme itself is a verb.  So I need to make this change a little less encompassing and more specific:
1) a gerundive mood to match a participle mood.  
2) when retrieving the data from the treebank, set the pofs of the inflection of a gerundive to verb participle instead of verb

**Comment by balmas** [comment]
@monzug please reverify in Alpheios Components 3.3.3-qa.20210115626 (changes for #615 directly impacted this fix)

**Comment by monzug** [comment]
retested in Alpheios Embedded Library 3.3.1-20200821383
Alpheios Components 3.3.3-qa.20210119683  on Mac
