### ISSUE TITLE
Greek particle == Greek adverb

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#609]
go to line 46 of https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg001.alpheios-text-grc1/passage/1.1-1.30,
both words δ᾽   and ἄρ᾽ are in the tree but we do not show any treebank icons in the pop-up. this is also on texts.alpheios.net

**Comment by balmas** [comment]
this is similar to #608 

upon disambiguation of inflections we need to be able to match a greek particle to a greek adverb

**Comment by balmas** [comment]
Alpheios Components 3.3.3-qa.20210113579

The code fix was to all a particle (i.e. as reported by morpheus) to be disambiguated by an adverb from a tree.

E.g. now we will get

![d2010edb-6ec6-480e-9b18-1b22e5d1c7a4](https://user-images.githubusercontent.com/644870/104510419-269bfd80-55b9-11eb-8c52-124ac2992a16.png)

for the above example

**Comment by monzug** [comment]
cool. to clarify, it's not that all adverb are now particle. adverb are still present e.g. αὐτοῦ   in the same tree as the example in this issue. this fix is to match a greek particle to a greek adverb, if a greek word has both in the tree (e.g. δ᾽ ἄρ᾽)

**Comment by balmas** [comment]
@monzug please reverify in Alpheios Components 3.3.3-qa.20210115626 (changes for #615 directly impacted this fix)

**Comment by monzug** [comment]
question: have interjection and exclamation also merged? see latest build vs release

![Screen Shot 2021-01-18 at 4 33 06 PM](https://user-images.githubusercontent.com/41396793/104934905-e1a60b80-59aa-11eb-86aa-9d67aeac0f30.png)

![Screen Shot 2021-01-18 at 4 32 29 PM](https://user-images.githubusercontent.com/41396793/104934910-e2d73880-59aa-11eb-8ea2-63637bee591e.png)

**Comment by balmas** [comment]
oh, this is a good catch! No, that's actually a bug.  I need to fix the bug.

But you're right, it's better when we consider exclamation and interjection the same. Do you think there is any reason not to?  Is  exclamation a more granular form of an interjection ?  (@vgorman1 and @rgorman I welcome your input on this question - Whitaker parses agedum as an interjection; it's treed as an exclamation. Is there ever a reason to say an exclamation is not an interjection?)

**Comment by vgorman1** [comment]
All interjections is best.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by monzug** [comment]
*h.* Interjections are mere exclamations and are not strictly to be classed
as parts of speech. Thus, *heus* (halloo!),*ō* (oh!).

**Comment by balmas** [comment]
It seems we also at some point normalized the Greek treebank to interjection so Arethusa isn't correctly mapping parsing exclamation in a treebank file anymore. I'll need to update the Alpheios trees for this too.

**Comment by monzug** [comment]
getting back this one to finish retesting on mac

**Comment by balmas** [comment]
ok the exclamation/interjection normalization is in Alpheios Components 3.3.3-qa.20210118566

**Comment by monzug** [comment]
tested for agendum  and heu   for interjection and exclamation
γάρ   and  κ᾽  and  μέν   for particle and adverb
