### ISSUE TITLE
fixes to verbpdgm13 and verbpdgm14

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#61]
related to issue alpheios-project/inflection-tables#289 
lookup for μεμνῄμεθα   produces no results.
need to verify the endings for this verb and also the duals of the optative plural of Perfect System Middle-Passive: simple subjunctive, optative, imperative table

**Comment by monzug** [comment]
uhm, this is complicated. in Smyth the perfect imperative looks like the simple perfect imperative with more endings (duals and 3rd person plural). also, the perfect subjunctive and Optative are periphrastic forms.because I ma not able to search such forms in orpheus, I am not able to dig in deeper. 
it looks like verbpdgm14 should be a perfp_p, reg_conj  but I am not able to find the Smyth subjunctive and optative forms that could match Mastronarde table.

**Comment by balmas** [comment]
tagging @vgorman1 in case she has thoughts about this one

**Comment by monzug** [comment]
good idea. I was waiting to ask for her help after having a better idea of Smyth perfect system vs Mastronarde perfect system.

**Comment by vgorman1** [comment]
I am not sure what you are asking.  Can you tell me what exactly you are looking at in the two sources?
There is no “simple perfect” but just a perfect.

Yes, the perfect subjunctive and optative are periphrastic.  They also rarely occur.  It is just the perfect participle and the appropriate subj/opt forms of the verb εἰμί.  Likewise with the perfect imperatives.

I am looking at Mastronarde, and I am seeing a bunch of forms mixed into the λύω conjugation at Perf Active System that are forms of λείπω, and a whole paradigm labeled «opt (simple) that Diogenes cannot find at all.

λελοίποιμι
λελοίποις
Etc.

When in doubt, trust Smith.  He has been around a long time and typos are virtually unheard of.


Vanessa B. Gorman
Professor, Ancient History
Undergraduate Chair
Dept. of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by monzug** [comment]
that's the form that puzzled me. the imperative in mastronarde is periphrastic while in Smyth is not + I don't get where this simple perfect come from. will dig in more tomorrow.
Thanks Vanessa.

**Comment by vgorman1** [comment]
There is a periphrastic perfect active imperative in Smyth  [bottom of pg. 115]  in section 383: λελυκὼς ἴσθι, etc.

Vanessa B. Gorman
Professor, Ancient History
Undergraduate Chair
Dept. of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by monzug** [comment]
that's the active system, here we are only considering the perfect middle-passive forms

**Comment by vgorman1** [comment]
I do not know where Mastronarde is getting those!

Vanessa B. Gorman
Professor, Ancient History
Undergraduate Chair
Dept. of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by monzug** [comment]
what I will do based on Smyth:
the imperative in verbpdgm13 table should not be periphrastic (see Smyth section 382 page 113 with the conjugation of λύ̄ω loose).
the imperative should be changed as follow (which is the correct form for λύ̄ω )
λέλυσο  2nd person singular
λελύσθω  3rd person singular
λέλυσθε  2nd person plural
the dual and 3rd plural are wanting (section 712.a)

as per verbpdgm14, there is such a simple form constructed in Smyth, section 709  such as perf. μέμνημαι remember: με-μνά-ω-μαι = μεμνῶμαι, μεμνη-ώ-μεθα = μεμνώμεθα
in Smyth section 711.b : μιμνῄσκω (μνα-) remind perf. μέμνημαι remember; opt. μεμνη-ί̄-μην = μεμνῄμην, μεμνή-ῑ-σο = μεμνῇο, μεμνή-ῑ-το = μεμνῇτο, etc. The forms μεμνῴμην, -ῷο, -ῷτο, etc., from μεμνη-ο-ί̄-μην, etc., are uncommon and suspected. 
based on this comment, what I would do:
1) I would remove the second column in the simple Optative
(also not found in Morpheus).
2) to make it simple (and avoid confusion), I would restrict this table to the lemma μιμνήσκω - remind, put in mind; (o μιμνῄσκω) - after all there are only few verbs listed in Smyth which would do a match with this table, the other one is κεκτῆται
(lemma  κτάομαι acquire)
@balmas, what do u think? 

going back to this issue's title, to have a match we should change μεμνῄμεθα into μεμνήμεθα , but I could not find the exact ending in Smyth. I found it by changing the accent in Morpheus. the dual 3rd person plural is μεμνήσθην in Morpheus and not μεμνῄσθην (the accent, again). could not find a match in Morpheus for the 2nd dual.

**Comment by balmas** [comment]
>I would remove the second column in the simple Optative
(also not found in Morpheus).
to make it simple (and avoid confusion), I would restrict this table to the lemma μιμνήσκω - remind, put in mind; (o μιμνῄσκω) - after all there are only few verbs listed in Smyth which would do a match with this table, the other one is κεκτῆται
(lemma κτάομαι acquire)
@balmas, what do u think?

this sounds good to me

**Comment by monzug** [comment]
how about the change in verbpdgm13 on the imperative column?

**Comment by balmas** [comment]
> how about the change in verbpdgm13 on the imperative column?

yes, agree

**Comment by monzug** [comment]
Thanks!

**Comment by balmas** [comment]
>to have a match we should change μεμνῄμεθα into μεμνήμεθα , but I could not find the exact ending in Smyth. I found it by changing the accent in Morpheus. the dual 3rd person plural is μεμνήσθην in Morpheus and not μεμνῄσθην (the accent, again). could not find a match in Morpheus for the 2nd dual.

This part of the issue is now alpheios-project/morpheus#32

**Comment by vgorman1** [comment]
No dual that I know of ends in –μεθα.  That is the 1st person plural m/p ending.  In this case, Diogenes identifies μεμνήμεθα:
1.    μιμνήσκω (remind, put in mind): perf ind mp 1st pl
2.    μιμνήσκω (remind, put in mind): plup ind mp 1st pl (homeric ionic)


Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
looks all good to me. Thanks
