### ISSUE TITLE
Contactum does not match with the contigo intransitive and transitive verbs

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#615]
contactum (second line of https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1) does not match the contingo intransitive and transitive verb entries, instead we have a new contigo1 entry with no definition found. In the release, we have the treebank icon in both the intransitive and transitive contingo1 verbs. maybe a little confusion btw verb intransitive and transitive? 
<word id="9" form="contactum" lemma="contingo1" postag="v-srppma-" head="5" relation="ATR"/>

also can we add a space between the transitive and 3rd conj? see screenshot

![Screen Shot 2021-01-15 at 3 14 52 PM](https://user-images.githubusercontent.com/41396793/104742245-7f4ed000-574a-11eb-8e9d-ea4478860017.png)

**Comment by monzug** [comment]
in the release:
![Screen Shot 2021-01-15 at 3 59 55 PM](https://user-images.githubusercontent.com/41396793/104742456-bde48a80-574a-11eb-8edd-c4a65e44977c.png)

**Comment by balmas** [comment]
Should be fixed in Alpheios Components 3.3.3-qa.20210115626

**Comment by monzug** [comment]
Now the popup with treebank icons is exactly what I was expecting, including the extra space. Thanks

![Screen Shot 2021-01-18 at 3 26 22 PM](https://user-images.githubusercontent.com/41396793/104927400-abb05980-59a1-11eb-8d93-a86277d922bb.png)
