### ISSUE TITLE
disambiguation error when source and disambiguator lemmas have different digits

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#618]
found by @monzug 

ine 78 of https://texts.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg001.alpheios-text-grc1/passage/1.1-1.30

look at   ὃς

in the release we have ὃς1  and ὃς2  with the tree icon on ὃς1
in the latest build, we have ὃς twice  as pronoun ὃς1: who, which, that and treebank icon on both

question: if we have ὃς1 in both pronoun, why is ὃς  repeated twice?
the only difference is that in one there is no person specified and in the second one is masculine.

then, the lookup for ὃς  gives pronoun ὃς   and pronoun  ὃς2 , that would explain  why we have two entries as they could be two different type of pronoun. said so, why in the latest build, the two type of pronoun in the treebank are ὃς1 ?

**Comment by balmas** [comment]
this is caused by the fix for #599

**Comment by balmas** [comment]
fixed in Alpheios Components 3.3.1-20200821376

**Comment by monzug** [comment]
ὃς is fixed now in Alpheios Embedded Library 3.3.1-20200821383
Alpheios Components 3.3.3-qa.20210119683

![Screen Shot 2021-01-20 at 2 55 34 PM](https://user-images.githubusercontent.com/41396793/105184392-9701cc00-5b2f-11eb-8222-b642cb52f1f8.png)
