### ISSUE TITLE
Ignore a specific character around a Greek word 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#620]
Double click does not work for  †οὖνπερ
ἱεροδόκα†  in  https://texts.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg001.alpheios-text-grc1/passage/1-30    line 362 and 363 because of the †.  could we ignore it?

**Comment by balmas** [comment]
yes this would be easy but it needs to wait for the next release.

**Comment by monzug** [comment]
No problem. Thanks

**Comment by balmas** [comment]
please make the fix in a branch off of the incr-3.3.x branch

**Comment by kirlat** [comment]
Has been merged into ` incr-3.3.x`.

**Comment by irina060981** [comment]
It should be implemented (it was merged to the code before)

@monzug , could you check?
