### ISSUE TITLE
Wordlist: number of times looked up a word after login set to 1

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#628]
@irina060981 question for you: why does the number of times you have looked up a word in wordlist go back to 1 after login?

e.g. as guest user, double click on few latin words 2 or 3 times, then log in and go to wordlist and limit to this session.
the number of times you have looked up a word in wordlist goes back to 1 

as guest user
![Screen Shot 2021-01-27 at 2 57 53 PM](https://user-images.githubusercontent.com/41396793/106001735-9da0be00-60b0-11eb-9644-1450fe986a8c.png)

after login (note that caro was already saved in wordlist)
![Screen Shot 2021-01-27 at 3 00 09 PM](https://user-images.githubusercontent.com/41396793/106001856-be691380-60b0-11eb-86af-9bb33dabaf55.png)

**Comment by monzug** [comment]
maybe this would be a question for @kirlat

**Comment by irina060981** [comment]
I work now only with alignment-editor - but I could check - as I was creating this code

**Comment by monzug** [comment]
Irina, Thanks. it's just a question so if it's not too much of a burden for
you, it would be nice. Thanks

**Comment by irina060981** [comment]
@balmas, I found the problem - and created PR for fixing it

**Comment by monzug** [comment]
Great! Thanks

**Comment by irina060981** [comment]
Merged and closed (to both master and incr-3.3.x)

**Comment by monzug** [comment]
@balmas, for future releases
