### ISSUE TITLE
Possibly invalid forms in verbpdgm17b "θνῄσκω (in addition to forms from τέθνηκα)" 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#63]
lookup for τέθνατον (3rd dual indicative) it will highlight the 2nd dual person but it's also 3rd person. need to find out if it's a mistake in the paradigm table or missing an entry in morpheus

lookup for τέθνατε  2nd plural indicative, it produces no results

lookup for    τεθναῖτον  or    τεθναίτην  (dual),   τεθναῖμεν , τεθναῖτε  (optative poetic) it produces no results

**Comment by monzug** [comment]
Finally I was able to find this verb on Smyth (I could not find any reference in the Greek index and the list of verbs, though).  in Smyth section 417 there is a reference to this verb in section 704.c
there are fewer endings than in Mastronarde e.g. 2 perf dual τέθνατον but not mention to the 3rd person dual. Probably Morpheus does not have this ending as it is not in Smyth too like all the other endings reported above except for τέθνατε 2nd plural indicative which is listed in Smyth.
Either we remove some endings from the table to match Smyth and we 'fix' Morpheus for τέθνατε  or we leave as is.

**Comment by balmas** [comment]
Let's leave the Mastronarde table as-is, we can add the form to the list of additions needed for Morpheus.
