### ISSUE TITLE
Add ability to define language of the text from the character's set

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#639]
- investigate libraries/methods to define language for the lookup words from character's set
- add ability to define language from the character's set
- merge it to production `incr-3.3.x`

**Comment by irina060981** [comment]
Priorities for language definition:
1. html markup
2. language detection from unicode
3. default language

if a user updates language in a popup for empty lexical query - it would have the biggest priority

**Comment by irina060981** [comment]
@monzug , this is ready for testing

**Comment by monzug** [comment]
I uploaded a file with Arabic text set as Italian. the language detection failed, offering to choose a new language from drop-down. As Arabic is one of the supported languages in pop-up, I was expecting to be able to detect the language. maybe, I misunderstood this fix. see attachment

![Screen Shot 2021-03-30 at 2 57 55 PM](https://user-images.githubusercontent.com/41396793/112993331-65c5fd80-9169-11eb-8cf0-243b85c4a768.png)

**Comment by monzug** [comment]
still to test in web extension

**Comment by irina060981** [comment]
>question 1): if I have the wrong language in markup (priority 1), priority 2 will never kick in, right? the wrong language has priority 1, correct? the only option to change language is in pop-up or by changing language in Origin or Target texts.

quite right

**Comment by irina060981** [comment]
>Not sure if it would make sense to reverse the priorities as follow: application detects the language (as priority 1), if not able to detect the language then it takes the one from markup (priority 2)? at the meeting we all agreed in the above workflow, right?

We talked about this on the meeting and agreed, that we should consider - if a language was defined in HTML markup, than we should trust it more than language detection

**Comment by irina060981** [comment]
>question 2): how can I test a scenario in which there is no lang in markup?

With the help of webextension I believe

**Comment by monzug** [comment]
> > question 2): how can I test a scenario in which there is no lang in markup?
> 
> With the help of webextension I believe on the sites without html markup.
> I created a specific index.html and test with its help.
> @monzug , I published it for you - may be it would be helpful
> https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/alignment-editor/index-detect.html

Thanks Irina, I did also use the test.html file that is very similar to yours

**Comment by monzug** [comment]
> still to do: test in web extension

test on build  Alpheios Reading Tools 3.3.3 build incr-3.3.x.20210331291
Alpheios Components 3.3.3-incr-3.3.x.20210326.58 build i639-language-detect-2.20210331450  in  FF/PC

in the latin library, I did not experience any difference with the new build. On the contrary in the Scaife site, the priority is now 
on eng as markup language. this is new because I was always able to lookup Latin words without having to change the language. this is a very undesired side effect of this fix.  see screenshot

![scaife-cicero-en](https://user-images.githubusercontent.com/41396793/113152563-3f08d500-9204-11eb-825a-21f25ec2b1a5.JPG)

**Comment by irina060981** [comment]
I believe the problem here - is in incorect markup that is set by site developers.
But the behaviour should be the same as it was with previous version.
The priority of markup was always set.

could you give me a link? I would check with previous version of webextension

**Comment by monzug** [comment]
I checked against the previous version and the behaviour is not the same.
see this link
https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0085.tlg001.perseus-grc2:1-30/
and compare latest build vs build

**Comment by monzug** [comment]
![Screen Shot 2021-04-01 at 7 55 33 AM](https://user-images.githubusercontent.com/41396793/113250380-ac7a3b80-92c0-11eb-8404-e8bf72acb00c.png)

**Comment by monzug** [comment]
![Screen Shot 2021-04-01 at 7 52 55 AM](https://user-images.githubusercontent.com/41396793/113250413-bd2ab180-92c0-11eb-8ceb-d9d86bd902e3.png)

**Comment by monzug** [comment]
I am experiencing Github issues. let me reload jpg one by one

**Comment by monzug** [comment]
![chrome-latin](https://user-images.githubusercontent.com/41396793/113250710-06faa400-928f-11eb-91c8-9d8ef814a61c.JPG)

**Comment by irina060981** [comment]
I checked the code of previous version and found out why behaviour is changed.

Previously there were the following workflow:

- get the language of the page
if it is defined but not supported by us then we get language from the options

I would describe the results of language detection to the meeting

**Comment by irina060981** [comment]
Decided on the meeting:

if defined language is unsupported - use default language (as it was before)
if a user chose another language it is used as priority without limitation for the page

**Comment by monzug** [comment]
Tested in FF, Chrome and Safari Alpheios Translation Alignment editor 1.3.2 (build development.20210412682)
Irina, I do not see any change compare with previous version. When I have a Latin text that has been saved as English, I can select Latin from dropdown (it's an empty box in the pop-up), then I can doble click on a Latin word and the morphology popup is generated for the Latin word. For any subsequent words, I need to reselect Latin from drop-down. 
See screenshots

![Screen Shot 2021-04-14 at 3 50 23 PM](https://user-images.githubusercontent.com/41396793/114721990-b593ef80-9d39-11eb-9331-c89eae2333d3.png)

![Screen Shot 2021-04-14 at 3 44 50 PM](https://user-images.githubusercontent.com/41396793/114721996-b6c51c80-9d39-11eb-8538-433a8807d7e4.png)

**Comment by irina060981** [comment]
Yes, changes are not pushed to the environment - these changes are waiting a review from Zack :)

**Comment by monzug** [comment]
Great. Thanks

**Comment by irina060981** [comment]
@monzug , changes are implemented
the fresh release of webextension is here - https://github.com/alpheios-project/webextension/releases

also changes are in the Alignment Editor

**Comment by monzug** [comment]
Preliminary testing is positive. Need to do extensive testing also in webextension

**Comment by monzug** [comment]
example of improvement: page language set to Arabic but text is in Latin
latest release
 Alpheios Reading Tools 3.3.3 build 20210122645
Alpheios Components 3.3.3-20210122585 


build Alpheios Reading Tools 3.3.3 build incr-3.3.x.20210415330
Alpheios Components 3.3.3-incr-3.3.x.20210331255 build i644-language-detect-adapter.20210415365

![monstrifero](https://user-images.githubusercontent.com/41396793/120656630-c4ea0c00-c451-11eb-965e-cd9f0509e0a4.JPG)

![signa](https://user-images.githubusercontent.com/41396793/120656670-cfa4a100-c451-11eb-92f8-65dcdb7067b4.JPG)

**Comment by monzug** [comment]
in scaife.perseus.org, any greek text with page language set to latin or arabic does still give the language is not found in xxx resources message.
