### ISSUE TITLE
Greek Interrogative pronouns - no pronoun views

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#64]
While working on https://github.com/alpheios-project/inflection-tables/issues/289
I was not able to find examples for getting Interrogative pronouns.

For **τι**, 
Indefinite Pronoun Declension

For **ποιος**, **ποια**, **ποιο**
No lexical result

For **τίνος**, **τίνων**
returns irregular instead of pronoun

![image](https://user-images.githubusercontent.com/12377640/70515342-eb8ef580-1b80-11ea-9267-364fbcae6a7f.png)

![image](https://user-images.githubusercontent.com/12377640/70515411-05303d00-1b81-11ea-9180-ea8c14511f96.png)

For **πόσος**, **πόση**
returns adjective

![image](https://user-images.githubusercontent.com/12377640/70515495-255ffc00-1b81-11ea-8a34-2f268e3c512d.png)

![image](https://user-images.githubusercontent.com/12377640/70515571-49bbd880-1b81-11ea-8f9b-50bad56db3da.png)

For  **πόσο**
returns no lexical results

So I am not sure if Greek Interrogative pronouns works.
@balmas, I have created issue here not to forget about this problem.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
Now it works fine for some pronouns.
there is still some clean up to improve the view of the pronoun:
1) it looks like the relative and indefinite tables in the browser are identical, which I did mention in GitHub 75
2) if I enter ἀττα from Vanessa's indefinite pronoun list, it does display the Greek Pronoun declension which we do not have in the browse inflection tables, then the Reflexive, Demonstrative, Personal pronoun tables. so, why do we still have the Greek Pronoun table?
this is the output from Morpheus:
<hdwd xml:lang="grc">τις</hdwd>
<pofs order="5">pronoun</pofs>
</dict>
<infl>
<term xml:lang="grc">
<stem>ἄσσα</stem>
</term>
<pofs order="5">pronoun</pofs>
<case order="4">accusative</case>
<gend>neuter</gend>
<num>plural</num>
<dial>epic</dial>
<stemtype>indef</stemtype>
<morph>enclitic indeclform</morph>
</infl>

see attachment
![Screen Shot 2020-03-23 at 4 42 11 PM](https://user-images.githubusercontent.com/41396793/77335880-0d267e00-6d27-11ea-89ff-e53101343d8a.png)

**Comment by balmas** [comment]
will investigate. thank you!

**Comment by balmas** [comment]
I have found the error with the relative table in browse mode and can fix that.

For ἀττα I need a little expert advice.

In our pronoun inflection data file, we have the form as 

ἅσσα

Where the first character is unicode 1f05 Greek Small Letter Alpha with Dasia and Oxia

Morpheus reports it as 

ἄσσα

Where the first character is unicode 1f04 Greek Small Letter Alpha with Psili and Oxia

And these diacritics are not ones we have in our list of those that we drop when we compare Greek forms for matching (we normally drop vowel length (vrachy and macron) and diaeresis (Dialytika)

So my questions are these:

1) Is the form we have in the table data, i.e. ἅσσα with Greek Small Letter Alpha with Dasia and Oxia actually incorrect and it should be ἄσσα with Greek Small Letter Alpha with Psili and Oxia?

2) if both are valid forms, are they functionality equivalent? I.e. should we consider Greek Small Letter Alpha with Dasia and Oxia to be the same character as Greek Small Letter Alpha with Psili and Oxia?

@vgorman1 do you have an opinion on this? Thanks!

**Comment by balmas** [comment]
The problem with ἅσσα will be addressed via #209 and/or #208 

This item will cover just remaining issue with the relative pronoun browser table which is fixed now.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
fixed in Alpheios Reading Tools 3.1.0 build qa.20200330265
Alpheios Components 3.3.0-qa.20200327479
