### ISSUE TITLE
Link to Grammar from pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#648]
Alpheios Reading Tools 3.3.3 build incr-3.3.x.20210415330
Alpheios Components 3.3.3-incr-3.3.x.20210331255 build i644-language-detect-adapter.20210415365

Just noticed that when I link an element from the morphology pop-up to the grammar (e.g. click on conjugation), The tab opens to the list of Grammars with no default selection. Link should take to the pertinent part of the Grammar based on the setting set in Resources. Note that this works fine in the release.

![link-to-grammar](https://user-images.githubusercontent.com/41396793/123281753-f0539a00-d4d7-11eb-86d4-4bb86033058e.JPG)

**Comment by irina060981** [comment]
@monzug - I was not able to reproduce this bug on the current version
![image](https://user-images.githubusercontent.com/12377640/128506349-c00e7798-09a4-4e62-8131-369bf511d752.png)

if you could still reproduce it - give me more details

**Comment by monzug** [comment]
You are right, it is not longer reproducible in Alpheios Translation Alignment editor 1.4.1 (build development.20210806356)
but still reproducible in  Alpheios Embedded Library 3.3.1-incr-3.3.x.20210415085
Alpheios Components 3.3.3-incr-3.3.x.20210331255 build i644-language-detect-adapter.20210415365 


![Screen Shot 2021-08-06 at 12 12 54 PM](https://user-images.githubusercontent.com/41396793/128540413-db136d59-965b-4ea3-8a92-92e5c9982012.png)
