### ISSUE TITLE
Add ability not to close popup on click out of the modal

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#655]
For the using along with annotations - https://github.com/alpheios-project/alignment-editor-new/issues/462

**Comment by irina060981** [comment]
Added an option:

![image](https://user-images.githubusercontent.com/12377640/128505382-8ca693ed-b287-4c1e-bc53-06b685d3ef85.png)

Also this options could be pre-defined in embed-lib properties

**Comment by monzug** [comment]
tested in Chrome/Mac. works as described.

**Comment by irina060981** [comment]
This issue is only about clickaway for alignment editor - it is only for Alpheios Reading Tools.
So this clickway only about this popup and not any popup else:

![image](https://user-images.githubusercontent.com/12377640/129643530-abd6691a-7559-4baa-b089-9086815645ca.png)

So it is by design
