### ISSUE TITLE
Change lexical dictionaries error

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#662]
I did also add/remove lexicons from short definitions but it does not properly work. I can't add/remove any lexicons and I do not see any changes in the drop-down, even if I do see differences in lookup (e.g. getting no definition found rather than lexical data is loading). By clicking on Reset all, I go back to error: Lexical data is loading.

![Screen Shot 2021-11-17 at 2 44 16 PM](https://user-images.githubusercontent.com/41396793/142211978-fc37dcf2-9193-4ebf-acaf-c73229949d23.png)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/622#issuecomment-971543748_

**Comment by irina060981** [comment]
I think that it was because of another bug that I solved in webextension - see new Release
https://github.com/alpheios-project/webextension/releases

**Comment by monzug** [comment]
perfect. this works now in build  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211118345
Alpheios Components 3.3.3-incr-3.4.x.20211116233 build i662-lexical-dicts.20211118457
