### ISSUE TITLE
add a note in the Credits that Mastronarde tables have been updated

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#68]
I was thinking that as we are updating the paradigm tables to be more in sync with Morpheus, we should add a note in the credits, next to
Verb paradigm tables derived from Ancient Greek Tutorials, by Donald J. Mastronarde, Berkeley Language Center of the University of California, Berkeley.
©1999-2005 The Regents of the University of California.
what do you think @balmas?

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
Verb paradigm tables derived from Ancient Greek Tutorials, by Donald J. Mastronarde, Berkeley Language Center of the University of California, Berkeley.
©1999-2005 The Regents of the University of California.
Edited by the Alpheios Project, Ltd.

**Comment by monzug** [comment]
just a comment here: the credits of the participles haven't been updated and this is ok because no change has been made to these tables.
