### ISSUE TITLE
remove duals optative in verbpdgm24 table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#69]
lookup for     ὁρῴσθην     or        ὁρῷσθον    duals optative in the Present System Middle-Passive of Contract Verbs in -άω table (verbpdgm24). lexical  query produced no results. either the forms are not correct in Mastronarde table or Morpheus has different endings.

**Comment by monzug** [comment]
so Smyth has both endings in the dual optative mp + two extra in () that Morpheus still does not find:  ὁράοισθον  and  ὁραοίσθην
both Mastronarde and Smyth tables have these endings so it's Morpheus's fault. do we want to 'fix' it? Vanessa said that those endings are unlikely used. shall we keep as is?

**Comment by balmas** [comment]
I think let's keep them in the table, and we can make a note of the missing parses in Morpheus for the database of forms that will augment Morpheus.
