### ISSUE TITLE
reduce or clarify rules for verbpdgm3 and verbpdgm4

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#74]
...
for the verbpdgm3 and 4, I need sometimes to review it, I strongly believe there should NOT be a verbpdgm3,1,verb,aw_fut,,,,,,
verbpdgm4,2,verb,aw_fut,,,,,contr,

I would do like this
verbpdgm3     1       verb reg_fut
verbpdgm4     2      verb ew_fut 
verbpdgm5	3	verb	aw_fut						

flag contr is not used anyway.

_Originally posted by @monzug in https://github.com/alpheios-project/inflection-tables/issues/289#issuecomment-560420110_

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
looks ok in Alpheios Reading Tools 3.1.0 build qa.20200410484
Alpheios Components 3.3.0-qa.20200410462
