### ISSUE TITLE
inflection browser shows indefinite data for interrogative pronoun

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#75]
I think the standard form data for the greek interrogative pronoun table is incorrect - it's showing the indefinite table instead of the interrogative

![Screenshot from 2020-01-15 15-07-31](https://user-images.githubusercontent.com/644870/72467369-c6595c80-37a8-11ea-9039-27f8fb36dcb3.png)

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200320403

**Comment by monzug** [comment]
much better, still I believe there are some clean up needed in the Browse Indefinite Pronoun Decl.
see attachment
![Screen Shot 2020-03-23 at 4 11 28 PM](https://user-images.githubusercontent.com/41396793/77332238-18c37600-6d22-11ea-8d2d-4746ae9435d2.png)

**Comment by balmas** [comment]
ok thanks.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
looks good in Alpheios Reading Tools 3.1.0 build qa.20200330265
Alpheios Components 3.3.0-qa.20200327479
