### ISSUE TITLE
missing forms in the verb εἰμί (be)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#76]
related to issue alpheios-project/alpheios-core#54 

1) missing one form of verb to be from Mastronarde table which is present in Smith and Morpheus
ἔστωσαν      imperative plural 3rd pers present, stemtype irreg_mi

2) missing  2nd person dual  imperfect    ἦτον  in Mastronarde table, this form is present in Smith but not in Morpheus  

3) missing 3rd person dual imperfect   ἤτην  in Mastronarde table. this form exist in both Smith and Morpheus

4) Morpheus adds an other form to the 3rd person plural imperfect which is ἦν (dialects)  not present in Smith or Mastronarde table

5) Smith adds an other form ἔσει to the second person sing future besides ἔσῃ  (Morpheus has it as reg_fut)

6) related to issue alpheios-project/alpheios-core#54,  in Morpheus all the future of εἰμί (be) goes to reg_fut (voice is middle) and not to the future indicative irreg_mi  in verbpdgm46

7) also the future infinitive (not the infinitive) goes to reg_fut  and not irreg_mi table

8) we are missing the future optative (voice is middle) in Mastronarde table. the future optative does exist in Smith and in Morpheos, even if it goes to reg_fut (voice is middle) e.g. ἔσοιτο

**Comment by balmas** [comment]
@monzug the only one of these I think I'm going to do anything for is to add '(or ἔστωσαν)' to mperative plural 3rd pers present in table 46 (εἰμί (be): Present System and Future). 

I'm not adding '(or ἔσει)' to 2nd person sing future or ἐσοίμην (future optative) because these are both middle voice which we don't have in the mastronarde table.

Let me know if you disagree with this plan. Thanks!

**Comment by monzug** [comment]
need to refresh the issue here... and I do not have any of the greek books with me

**Comment by balmas** [comment]
ok, don't worry. it's not urgent.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
see also issue #54

**Comment by monzug** [comment]
all good here. I wasn't sure about ἔσει, the present active indicative is not highlighted but then I realized that εἴσειμι is a compound of εἰμί so it does need the fix to #56
