### ISSUE TITLE
add mediopassive to rules.csv for verbpdgm31 table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#81]
lookup for θέσθαι infinitive mediopassive aorist, it should do a match in the τίθημι: Aorist System Middle table but there is not inflection icon because we don't have the voice mediopassive in rules.csv
<mood>infinitive</mood>
<tense>aorist</tense>
<voice>mediopassive</voice>
<stemtype>emi_aor</stemtype>

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
we do display the table now, but we do not highlight the infinitive cell. I am lost here, any idea? where is located the latest csv? I used to look at https://github.com/alpheios-project/inflection-tables/blob/master/src/paradigm/data/greek/verb/rules.csv

**Comment by balmas** [comment]
the csv is now at https://github.com/alpheios-project/alpheios-core/tree/master/packages/inflection-tables/src/paradigm/data/greek/verb

Will take a look

**Comment by balmas** [comment]
sigh, it's because the table cells themselves have middle and not mediopassive .  I think we can remove the voice from the cell matching on any table which is restricted by voice in the rules and which doesn't have multiple voices within the table.

I will do this...

**Comment by balmas** [comment]
I made this change now in the rest of the tables which match on both middle and mediopassive. Changed greek verb paradigm tables: 31, 35, 39

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
the infinitive is highlighted now.
