### ISSUE TITLE
add mediopassive to some tables in rules.csv

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#82]
Moving this issue from github alpheios-project/alpheios-core#56 

1) in verbpdgm35, there is a dup line, we should change middle in mediopassive as follow:
verbpdgm35	3	verb		mediopassive		aorist	ἵημι

2) in verbpdgm39, there is only one line with middle, we should add mediopassive for consistency
verbpdgm39	2	verb 	omi_aor	mediopassive
	
3) add mediopassive to
verbpdgm31	2	verb	 emi_aor	middle

maybe the aorist verbs do not have a mediopassive but to be safe, I would rather add the lines

**Comment by balmas** [comment]
this one should be fixed too in Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
mediopassive has been added to rules.csv file. I did test few verbs belonging to those tables and all looks good.
