### ISSUE TITLE
extra columns in paradigm tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#83]
1) I did notice that in the Aorist Passive System table we have an extra column not present in Mastronarde tables: 2nd aorist indicative, stem_type aor2_pass
an example of form in the 2nd aorist column (the added column that is not in the paradigm table) is ἐγράφην (lemma γράφω which means scratch, graze)
The other columns matching Mastronarde use lemma βουλεύω which means take counsel, deliberate
shall we just ignore it and delete it from out tables?

2) in the Perfect Active System table we do also have a column for the 2nd perf. ind. such as λέλοιπα (λείπω: leave, quit).
lookup for λέλυκα does highlight also λέλοιπα (1st perfect indicative, deriv_type reg_conj)
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>singular</num>
<pers>1st</pers>
<tense>perfect</tense>
<voice>active</voice>
perf_act stemtype

in Smyth, these columns would make the second aorist (active and middle), second perfect and pluperfect active table. see Smyth 368.

I am trying to match Mastronarde tables with Smyth tables but it's not so obvious. will wait for the list of Greek verbs that Vanessa should provide and test the matching.

**Comment by balmas** [comment]
@monzug just to be sure I understand, which column in table 11 (Perfect Active System) should matching be restricted to forms with deriv_type=reg_conj? The 1st or the 2nd column (1st perfect or 2nd perfect)?

**Comment by monzug** [comment]
if I remember correctly the regular conjugation should be the first but I will check again tomorrow

**Comment by monzug** [comment]
yes, first column should be the deriv_type reg_conj

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200410462

**Comment by monzug** [comment]
question for issue 1)  - we do not have any match with this table.  if only the column has been removed, why do we not longer have a match?
2) works beautifully

**Comment by balmas** [comment]
>question for issue 1) - we do not have any match with this table. if only the column has been removed, why do we not longer have a match?

ah, it's because all the data in the table other than the column I removed has the restriction stemtype=aor_pass  

So now that I've removed the aor2_pass  column, I guess I should remove that restriction on the cell matching.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
column is gone and matching are working for table 10 too!!!!
