### ISSUE TITLE
εἷκα does not have a match highlighted in the inflection table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#85]
εἷκα is one of the Greek verb from the DCC list.
εἷκα  is 

```
<hdwd xml:lang="grc">ἵημι</hdwd>
<pofs order="1">verb</pofs>
</dict>
<infl>
<term xml:lang="grc">
<stem>εἱκ</stem>
<suff>α</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>singular</num>
<pers>1st</pers>
<tense>perfect</tense>
<voice>active</voice>
<stemtype>perf_act</stemtype>
```

it should open the  Perfect Active System table, verbpdgm11. the lemma ἵημι  has its own set of tables (verbpdgm32,33,34,35) but the perfect indicative is missing from this table. 
I think we should still make a match in the perfect system table for the lemma  ἵημι, unless we want to add a new perfect table for  ἵημι.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200309431

**Comment by monzug** [comment]
εἷκα  works fine. we should ask for Vanessa's feedback at one point.
as per εἷμαι: it should just open one table verbpdgm12.  we do not have a perfect  indicative mp column in the  ἵημι: Present System Middle-Passive table, so we should not generate this table.

**Comment by balmas** [comment]
@monzug just checking re εἷμαι - it's opening verbpdgm12 and verbpdgm11 (Perfect Active System) but as far as I can see, not ἵημι: Present System Middle-Passive . Is it Perfect Active System we shouldn't be opening in this case?

**Comment by monzug** [comment]
εἷμαι in texts.alpheios.net has two tables: 
1) ἵημι: Present System Middle-Passive (with no match) and
2) verbpdgm12, Perfect System Middle-Passive: indicative, infinitive, participle
I do not think we should show the ἵημι table with no match.
what you are seeing now in latest builds, it's wrong. it should only be verbpdgm12 table.

**Comment by balmas** [comment]
got it.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200327479

**Comment by monzug** [comment]
I think this is ok. build Alpheios Reading Tools 3.1.0 build qa.20200330265
Alpheios Components 3.3.0-qa.20200327479
